import type { Unit } from '../../types/content'
import { au, img } from '../helpers'

export const leadIn: Unit = {
  id: 'lead-in',
  number: 0,
  title: 'Lead-in',
  phrase: 'get started',
  overviewPage: 6,
  pages: [6, 6],
  intro:
    'Warm up and get going: check the grammar you already know, hear Yusuf talk about London, practise your vowel sounds and review everyday phrases you use all the time.',
  objectives: ['Review grammar from previous levels', 'Read and listen to a personal story', 'Practise common everyday phrases'],
  video: [],
  lessons: [
    {
      id: 'li',
      code: 'Lead-in',
      title: 'Welcome!',
      pages: [6, 6],
      labels: {
        grammar: 'present simple and continuous; present perfect; future plans',
        vocabulary: 'common everyday phrases',
        pronunciation: 'vowel sounds',
      },
      objectives: ['choose the correct verb forms', 'talk about your life', 'practise common phrases for work and free time'],
      blocks: [
        {
          type: 'text',
          title: 'Grammar: choose the correct word',
          paragraphs: [
            'Complete the sentences by choosing the correct word. They cover tenses you have met before \u2013 present simple, present continuous, present perfect, past simple and future plans \u2013 so it\u2019s a quick memory check.',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'li-1a-grammar',
            title: '1A Choose the correct word',
            kind: 'mcq',
            instructions: 'Choose the correct word to complete each sentence.',
            page: 6,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: '\u2026 you studying at university?',
                options: [
                  { label: 'Are', correct: true },
                  { label: 'Do' },
                  { label: 'What' },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'What \u2026 you eat last night?',
                options: [
                  { label: 'did', correct: true },
                  { label: 'do' },
                  { label: 'have' },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'How many countries \u2026 you been to?',
                options: [
                  { label: 'have', correct: true },
                  { label: 'do' },
                  { label: 'did' },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'What \u2026 you doing next weekend?',
                options: [
                  { label: 'are', correct: true },
                  { label: 'will' },
                  { label: 'do' },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'Where \u2026 your best friend live?',
                options: [
                  { label: 'does', correct: true },
                  { label: 'is' },
                  { label: 'has' },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'I \u2026 working when she arrived.',
                options: [
                  { label: 'wasn\u2019t', correct: true },
                  { label: 'didn\u2019t' },
                  { label: 'not' },
                ],
              },
              {
                id: 'q7',
                kind: 'mcq',
                prompt: 'I\u2019m sure the school \u2026 be open tomorrow.',
                options: [
                  { label: 'won\u2019t', correct: true },
                  { label: 'isn\u2019t' },
                  { label: 'doesn\u2019t' },
                ],
              },
              {
                id: 'q8',
                kind: 'mcq',
                prompt: 'She \u2026 worked in several cities.',
                options: [
                  { label: 'has', correct: true },
                  { label: 'is' },
                  { label: 'did' },
                ],
              },
            ],
          },
        },
        {
          type: 'callout',
          title: 'Work in pairs',
          tone: 'tip',
          text: 'Check your answers together, then choose two questions to ask and answer with your partner.',
        },
        {
          type: 'text',
          title: 'Reading: What do you have in common with Yusuf?',
          paragraphs: [
            "Hi, I\u2019m Yusuf. I\u2019m from Turkey, but at the moment I\u2019m living in London, which is an amazing city. I\u2019m going to stay here for six months so that I can improve my English. I love getting to know new cities, and I\u2019m really happy that I chose to come to London. I\u2019ve been to seven or eight fantastic museums and art galleries, and I also really like the parks.",
            'The best thing about London is that there are so many interesting things to do, especially for someone in their twenties, like me. The worst thing is the weather. I really hate cold weather. I arrived in January and it was freezing!',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'li-2b-reading',
            title: '2B Find the structures in the text',
            kind: 'mcq',
            instructions: 'Read the text again and match each structure with an example from Yusuf\u2019s story.',
            page: 6,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'Which example contains a present continuous verb?',
                options: [
                  { label: "at the moment I\u2019m living in London", correct: true },
                  { label: 'I arrived in January' },
                  { label: "I\u2019ve been to seven or eight fantastic museums" },
                  { label: "I\u2019m going to stay here for six months" },
                  { label: 'The best thing about London' },
                  { label: 'so that I can improve my English' },
                  { label: 'which is an amazing city' },
                  { label: 'I love getting to know new cities' },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'Which example contains a past simple verb?',
                options: [
                  { label: "at the moment I\u2019m living in London" },
                  { label: 'I arrived in January', correct: true },
                  { label: "I\u2019ve been to seven or eight fantastic museums" },
                  { label: "I\u2019m going to stay here for six months" },
                  { label: 'The best thing about London' },
                  { label: 'so that I can improve my English' },
                  { label: 'which is an amazing city' },
                  { label: 'I love getting to know new cities' },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'Which example contains a present perfect verb?',
                options: [
                  { label: "at the moment I\u2019m living in London" },
                  { label: 'I arrived in January' },
                  { label: "I\u2019ve been to seven or eight fantastic museums", correct: true },
                  { label: "I\u2019m going to stay here for six months" },
                  { label: 'The best thing about London' },
                  { label: 'so that I can improve my English' },
                  { label: 'which is an amazing city' },
                  { label: 'I love getting to know new cities' },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'Which example shows a verb form for future plans?',
                options: [
                  { label: "at the moment I\u2019m living in London" },
                  { label: 'I arrived in January' },
                  { label: "I\u2019ve been to seven or eight fantastic museums" },
                  { label: "I\u2019m going to stay here for six months", correct: true },
                  { label: 'The best thing about London' },
                  { label: 'so that I can improve my English' },
                  { label: 'which is an amazing city' },
                  { label: 'I love getting to know new cities' },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'Which example contains a superlative?',
                options: [
                  { label: "at the moment I\u2019m living in London" },
                  { label: 'I arrived in January' },
                  { label: "I\u2019ve been to seven or eight fantastic museums" },
                  { label: "I\u2019m going to stay here for six months" },
                  { label: 'The best thing about London', correct: true },
                  { label: 'so that I can improve my English' },
                  { label: 'which is an amazing city' },
                  { label: 'I love getting to know new cities' },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'Which example contains a modal verb?',
                options: [
                  { label: "at the moment I\u2019m living in London" },
                  { label: 'I arrived in January' },
                  { label: "I\u2019ve been to seven or eight fantastic museums" },
                  { label: "I\u2019m going to stay here for six months" },
                  { label: 'The best thing about London' },
                  { label: 'so that I can improve my English', correct: true },
                  { label: 'which is an amazing city' },
                  { label: 'I love getting to know new cities' },
                ],
              },
              {
                id: 'q7',
                kind: 'mcq',
                prompt: 'Which example contains a relative clause?',
                options: [
                  { label: "at the moment I\u2019m living in London" },
                  { label: 'I arrived in January' },
                  { label: "I\u2019ve been to seven or eight fantastic museums" },
                  { label: "I\u2019m going to stay here for six months" },
                  { label: 'The best thing about London' },
                  { label: 'so that I can improve my English' },
                  { label: 'which is an amazing city', correct: true },
                  { label: 'I love getting to know new cities' },
                ],
              },
              {
                id: 'q8',
                kind: 'mcq',
                prompt: 'Which example contains a verb + -ing form?',
                options: [
                  { label: "at the moment I\u2019m living in London" },
                  { label: 'I arrived in January' },
                  { label: "I\u2019ve been to seven or eight fantastic museums" },
                  { label: "I\u2019m going to stay here for six months" },
                  { label: 'The best thing about London' },
                  { label: 'so that I can improve my English' },
                  { label: 'which is an amazing city' },
                  { label: 'I love getting to know new cities', correct: true },
                ],
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Pronunciation: vowel sounds',
          paragraphs: [
            'Find pairs of words in the box that have the same vowel sound, then listen and check: bar, boat, fight, heat, heart, mail, oil, put, queue, seen, show, shy, take, through, took, toy.',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'li-3a-pronunciation',
            title: '3A Same vowel sound',
            kind: 'mcq',
            instructions: 'Match the two words that share the same vowel sound.',
            page: 6,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: "Which word has the same vowel sound as 'bar'?",
                options: [
                  { label: 'heart', correct: true },
                  { label: 'show' },
                  { label: 'shy' },
                  { label: 'seen' },
                  { label: 'take' },
                  { label: 'toy' },
                  { label: 'took' },
                  { label: 'through' },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: "Which word has the same vowel sound as 'boat'?",
                options: [
                  { label: 'heart' },
                  { label: 'show', correct: true },
                  { label: 'shy' },
                  { label: 'seen' },
                  { label: 'take' },
                  { label: 'toy' },
                  { label: 'took' },
                  { label: 'through' },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: "Which word has the same vowel sound as 'fight'?",
                options: [
                  { label: 'heart' },
                  { label: 'show' },
                  { label: 'shy', correct: true },
                  { label: 'seen' },
                  { label: 'take' },
                  { label: 'toy' },
                  { label: 'took' },
                  { label: 'through' },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: "Which word has the same vowel sound as 'heat'?",
                options: [
                  { label: 'heart' },
                  { label: 'show' },
                  { label: 'shy' },
                  { label: 'seen', correct: true },
                  { label: 'take' },
                  { label: 'toy' },
                  { label: 'took' },
                  { label: 'through' },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: "Which word has the same vowel sound as 'mail'?",
                options: [
                  { label: 'heart' },
                  { label: 'show' },
                  { label: 'shy' },
                  { label: 'seen' },
                  { label: 'take', correct: true },
                  { label: 'toy' },
                  { label: 'took' },
                  { label: 'through' },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: "Which word has the same vowel sound as 'oil'?",
                options: [
                  { label: 'heart' },
                  { label: 'show' },
                  { label: 'shy' },
                  { label: 'seen' },
                  { label: 'take' },
                  { label: 'toy', correct: true },
                  { label: 'took' },
                  { label: 'through' },
                ],
              },
              {
                id: 'q7',
                kind: 'mcq',
                prompt: "Which word has the same vowel sound as 'put'?",
                options: [
                  { label: 'heart' },
                  { label: 'show' },
                  { label: 'shy' },
                  { label: 'seen' },
                  { label: 'take' },
                  { label: 'toy' },
                  { label: 'took', correct: true },
                  { label: 'through' },
                ],
              },
              {
                id: 'q8',
                kind: 'mcq',
                prompt: "Which word has the same vowel sound as 'queue'?",
                options: [
                  { label: 'heart' },
                  { label: 'show' },
                  { label: 'shy' },
                  { label: 'seen' },
                  { label: 'take' },
                  { label: 'toy' },
                  { label: 'took' },
                  { label: 'through', correct: true },
                ],
              },
            ],
          },
        },
        {
          type: 'audio',
          title: '3B Listen and check your answers',
          tracks: au(['L.01']),
        },
        {
          type: 'text',
          title: 'Common errors',
          paragraphs: [
            'There are eight sentences below, each with a common mistake. Correct them, then decide which kind of mistake each sentence contains.',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'li-4a-common-errors',
            title: '4A Correct the mistakes',
            kind: 'mcq',
            instructions: 'Choose the correct version of each sentence.',
            page: 6,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: "My sister don't like football.",
                options: [
                  { label: 'My sister doesn\u2019t like football.', correct: true },
                  { label: "My sister don't likes football." },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'Which film you watch last night?',
                options: [
                  { label: 'Which film did you watch last night?', correct: true },
                  { label: 'Which film you watched last night?' },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: "I'm from france.",
                options: [
                  { label: 'I\u2019m from France.', correct: true },
                  { label: "I'm from the France." },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'We love listening music.',
                options: [
                  { label: 'We love listening to music.', correct: true },
                  { label: 'We love listen music.' },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: "Let's discuss about this later.",
                options: [
                  { label: 'Let\u2019s discuss this later.', correct: true },
                  { label: 'Let\u2019s discuss about it later.' },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'When I can go home?',
                options: [
                  { label: 'When can I go home?', correct: true },
                  { label: 'When I can go home?' },
                ],
              },
              {
                id: 'q7',
                kind: 'mcq',
                prompt: "I'm teacher.",
                options: [
                  { label: 'I\u2019m a teacher.', correct: true },
                  { label: 'I\u2019m the teacher.' },
                ],
              },
              {
                id: 'q8',
                kind: 'mcq',
                prompt: 'I live here since 2018.',
                options: [
                  { label: 'I\u2019ve lived here since 2018.', correct: true },
                  { label: 'I live here for 2018.' },
                ],
              },
            ],
          },
        },
        {
          type: 'exercise',
          exercise: {
            id: 'li-4b-common-errors',
            title: '4B What kind of mistake?',
            kind: 'mcq',
            instructions: 'Match each kind of mistake with the corrected sentence from Ex 4A.',
            page: 6,
            verified: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: 'Which sentence is an example of a missing preposition?',
                options: [
                  { label: 'We love listening to music.', correct: true },
                  { label: 'Let\u2019s discuss this later.' },
                  { label: 'I\u2019ve lived here since 2018.' },
                  { label: 'When can I go home?' },
                  { label: 'Which film did you watch last night?' },
                  { label: 'I\u2019m from France.' },
                  { label: 'My sister doesn\u2019t like football.' },
                  { label: 'I\u2019m a teacher.' },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: 'Which sentence is an example of an extra preposition?',
                options: [
                  { label: 'We love listening to music.' },
                  { label: 'Let\u2019s discuss this later.', correct: true },
                  { label: 'I\u2019ve lived here since 2018.' },
                  { label: 'When can I go home?' },
                  { label: 'Which film did you watch last night?' },
                  { label: 'I\u2019m from France.' },
                  { label: 'My sister doesn\u2019t like football.' },
                  { label: 'I\u2019m a teacher.' },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: 'Which sentence is an example of a verb tense mistake?',
                options: [
                  { label: 'We love listening to music.' },
                  { label: 'Let\u2019s discuss this later.' },
                  { label: 'I\u2019ve lived here since 2018.', correct: true },
                  { label: 'When can I go home?' },
                  { label: 'Which film did you watch last night?' },
                  { label: 'I\u2019m from France.' },
                  { label: 'My sister doesn\u2019t like football.' },
                  { label: 'I\u2019m a teacher.' },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: 'Which sentence is an example of a word order mistake?',
                options: [
                  { label: 'We love listening to music.' },
                  { label: 'Let\u2019s discuss this later.' },
                  { label: 'I\u2019ve lived here since 2018.' },
                  { label: 'When can I go home?', correct: true },
                  { label: 'Which film did you watch last night?' },
                  { label: 'I\u2019m from France.' },
                  { label: 'My sister doesn\u2019t like football.' },
                  { label: 'I\u2019m a teacher.' },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: 'Which sentence corrects a missing auxiliary verb?',
                options: [
                  { label: 'We love listening to music.' },
                  { label: 'Let\u2019s discuss this later.' },
                  { label: 'I\u2019ve lived here since 2018.' },
                  { label: 'When can I go home?' },
                  { label: 'Which film did you watch last night?', correct: true },
                  { label: 'I\u2019m from France.' },
                  { label: 'My sister doesn\u2019t like football.' },
                  { label: 'I\u2019m a teacher.' },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: 'Which sentence corrects a punctuation or capitalisation mistake?',
                options: [
                  { label: 'We love listening to music.' },
                  { label: 'Let\u2019s discuss this later.' },
                  { label: 'I\u2019ve lived here since 2018.' },
                  { label: 'When can I go home?' },
                  { label: 'Which film did you watch last night?' },
                  { label: 'I\u2019m from France.', correct: true },
                  { label: 'My sister doesn\u2019t like football.' },
                  { label: 'I\u2019m a teacher.' },
                ],
              },
              {
                id: 'q7',
                kind: 'mcq',
                prompt: 'Which sentence corrects a verb\u2013noun agreement mistake?',
                options: [
                  { label: 'We love listening to music.' },
                  { label: 'Let\u2019s discuss this later.' },
                  { label: 'I\u2019ve lived here since 2018.' },
                  { label: 'When can I go home?' },
                  { label: 'Which film did you watch last night?' },
                  { label: 'I\u2019m from France.' },
                  { label: 'My sister doesn\u2019t like football.', correct: true },
                  { label: 'I\u2019m a teacher.' },
                ],
              },
              {
                id: 'q8',
                kind: 'mcq',
                prompt: 'Which sentence corrects a missing article?',
                options: [
                  { label: 'We love listening to music.' },
                  { label: 'Let\u2019s discuss this later.' },
                  { label: 'I\u2019ve lived here since 2018.' },
                  { label: 'When can I go home?' },
                  { label: 'Which film did you watch last night?' },
                  { label: 'I\u2019m from France.' },
                  { label: 'My sister doesn\u2019t like football.' },
                  { label: 'I\u2019m a teacher.', correct: true },
                ],
              },
            ],
          },
        },
        {
          type: 'text',
          title: 'Vocabulary: common phrases',
          paragraphs: [
            'Complete the common phrases with the verbs in the box: chat, do (x2), go, listen to, post, send, take, watch. Some verbs are used more than once.',
          ],
        },
        {
          type: 'exercise',
          exercise: {
            id: 'li-5a-vocabulary',
            title: '5A Common phrases',
            kind: 'mcq',
            instructions: 'Complete each phrase with the correct verb.',
            page: 6,
            verified: true,
            needsReview: true,
            questions: [
              {
                id: 'q1',
                kind: 'mcq',
                prompt: '\u2026 a meeting',
                options: [
                  { label: 'have', correct: true },
                  { label: 'do' },
                  { label: 'take' },
                ],
              },
              {
                id: 'q2',
                kind: 'mcq',
                prompt: '\u2026 out with friends',
                options: [
                  { label: 'go', correct: true },
                  { label: 'post' },
                  { label: 'take' },
                ],
              },
              {
                id: 'q3',
                kind: 'mcq',
                prompt: '\u2026 a photo on social media',
                options: [
                  { label: 'post', correct: true },
                  { label: 'send' },
                  { label: 'chat' },
                ],
              },
              {
                id: 'q4',
                kind: 'mcq',
                prompt: '\u2026 to a colleague',
                options: [
                  { label: 'send', correct: true },
                  { label: 'post' },
                  { label: 'go' },
                ],
              },
              {
                id: 'q5',
                kind: 'mcq',
                prompt: '\u2026 some work',
                options: [
                  { label: 'do', correct: true },
                  { label: 'make' },
                  { label: 'take' },
                ],
              },
              {
                id: 'q6',
                kind: 'mcq',
                prompt: '\u2026 an email',
                options: [
                  { label: 'send', correct: true },
                  { label: 'chat' },
                  { label: 'watch' },
                ],
              },
              {
                id: 'q7',
                kind: 'mcq',
                prompt: '\u2026 a film',
                options: [
                  { label: 'watch', correct: true },
                  { label: 'listen to' },
                  { label: 'go' },
                ],
              },
              {
                id: 'q8',
                kind: 'mcq',
                prompt: '\u2026 some music',
                options: [
                  { label: 'listen to', correct: true },
                  { label: 'watch' },
                  { label: 'do' },
                ],
              },
              {
                id: 'q9',
                kind: 'mcq',
                prompt: '\u2026 some sport / exercise',
                options: [
                  { label: 'do', correct: true },
                  { label: 'make' },
                  { label: 'have' },
                ],
              },
              {
                id: 'q10',
                kind: 'mcq',
                prompt: '\u2026 a break',
                options: [
                  { label: 'take', correct: true },
                  { label: 'have' },
                  { label: 'go' },
                ],
              },
            ],
          },
        },
        {
          type: 'exercise',
          exercise: {
            id: 'li-5b-vocabulary',
            title: '5B Work or free time?',
            kind: 'fill-blank',
            instructions: 'Write \u201cwork\u201d or \u201cfree time\u201d for each phrase.',
            page: 6,
            verified: true,
            needsReview: true,
            questions: [
              {
                id: 'q1',
                kind: 'fill-blank',
                before: 'have a meeting \u2014',
                answer: 'work',
                after: '',
              },
              {
                id: 'q2',
                kind: 'fill-blank',
                before: 'do some work \u2014',
                answer: 'work',
                after: '',
              },
              {
                id: 'q3',
                kind: 'fill-blank',
                before: 'send an email to a colleague \u2014',
                answer: 'work',
                after: '',
              },
              {
                id: 'q4',
                kind: 'fill-blank',
                before: 'chat online \u2014',
                answer: 'free time',
                after: '',
              },
              {
                id: 'q5',
                kind: 'fill-blank',
                before: 'go out with friends \u2014',
                answer: 'free time',
                after: '',
              },
              {
                id: 'q6',
                kind: 'fill-blank',
                before: 'watch a film \u2014',
                answer: 'free time',
                after: '',
              },
              {
                id: 'q7',
                kind: 'fill-blank',
                before: 'listen to some music \u2014',
                answer: 'free time',
                after: '',
              },
              {
                id: 'q8',
                kind: 'fill-blank',
                before: 'take a break \u2014',
                answer: 'free time',
                after: '',
              },
            ],
          },
        },
        {
          type: 'callout',
          title: 'Talk about it',
          tone: 'tip',
          text: 'Work in pairs. Can you add any more phrases to the table in Ex 5B? Which of these things do you do in a normal day?',
        },
        {
          type: 'pages',
          images: [img(20, 'Lead-in, page 6')],
        },
      ],
    },
  ],
}