// ديالوج متزامن مع الفيديو (اتجاب من ترجمة يوتيوب الإنجليزية الأوتوماتيكية).
// مفتاح = آي دي المقطع في shadowing.ts — الستوديو بيستخدمه لو المقطع مالهوش scenes مكتوبة إيدويًا.
import type { ShadowScene } from './shadowing'

export const HT_DIALOGUE: Record<string, ShadowScene[]> = {
  'ht-trailer-1': [
    { time: 35.5, en: "But there is one place where monsters" },
    { time: 38.5, en: "where monsters can finally rest in peace." },
    { time: 41.8, en: "can finally rest in peace. Drac, sir, we have an urgent plumbing" },
    { time: 43.9, en: "Drac, sir, we have an urgent plumbing issue." },
    { time: 44.3, en: "issue. Plumbing?" },
    { time: 44.8, en: "Plumbing? There is a clogged toilet in room 348." },
    { time: 52.2, en: "IT'S OKAY, WE ALL GET stomach aches, Mr. BIGFOOT." },
    { time: 59.1, en: "WELCOME to Hotel Transylvania. Do not disturb." },
    { time: 60.2, en: "Do not disturb. Do not disturb." },
    { time: 61.2, en: "Do not disturb. DO NOT DISTURB." },
    { time: 62.2, en: "DO NOT DISTURB. Human free since 1898." },
    { time: 69.4, en: "I LOVE THIS GUY. HELLO?" },
    { time: 71, en: "HELLO? A human!" },
    { time: 72.3, en: "A human! What is this place?" },
    { time: 74.4, en: "What is this place? It's just a normal hotel. Nothing going" },
    { time: 76.4, en: "It's just a normal hotel. Nothing going on here." },
    { time: 81.7, en: "WHAT'S HAPPENING? SORRY. IT'S MY MISTAKE." },
    { time: 83, en: "SORRY. IT'S MY MISTAKE. WHAT IS WRONG WITH YOU PEOPLE?" },
    { time: 89.6, en: "HOTEL TRANSYLVANIA. So much for do not disturb." },
  ],
  'ht-best-scenes': [
    { time: 22.1, en: "peekaboo no no no no no I didn't mean to startle you my little baby" },
    { time: 25.8, en: "startle you my little baby sh Hush little vampire don't say a word" },
    { time: 30.5, en: "sh Hush little vampire don't say a word Papa's going to bite the head off a" },
    { time: 34.3, en: "Papa's going to bite the head off a" },
    { time: 37.4, en: "bird I want to kiss your tool I want to" },
    { time: 41.8, en: "bird I want to kiss your tool I want to kiss your" },
    { time: 56.7, en: "tool nice but maybe a little more square footage I want a lot of monsters here" },
    { time: 60.4, en: "footage I want a lot of monsters here" },
    { time: 68.3, en: "I'm going to get you little babies I'm going to cat" },
    { time: 70.9, en: "going to cat you what out there oh we never go out" },
    { time: 75.5, en: "you what out there oh we never go out there" },
    { time: 78.3, en: "there ever and then the monsters ran away and" },
    { time: 81.1, en: "ever and then the monsters ran away and were forced into hiding but Harry the" },
    { time: 84.1, en: "were forced into hiding but Harry the human found them and jumped out from" },
    { time: 86.2, en: "human found them and jumped out from under their beds I'm scared and burned" },
    { time: 88, en: "under their beds I'm scared and burned their clothes and beat their toes and" },
    { time: 91.5, en: "their clothes and beat their toes and took their" },
    { time: 98.3, en: "candy don't take my candy baby claw you don't need to be frightened I promised" },
    { time: 100.7, en: "don't need to be frightened I promised your mommy I would protect you" },
    { time: 110.3, en: "forever my beautiful maybe let me wipe all your poop" },
    { time: 114.3, en: "maybe let me wipe all your poop away those humans are" },
    { time: 117.9, en: "away those humans are nasty so with that dad you will" },
    { time: 122, en: "nasty so with that dad you will stay and if a human tries to harm you" },
    { time: 127.3, en: "stay and if a human tries to harm you I'll simply" },
    { time: 137, en: "say because your daddy's girl daddy's girl just bend the legs and push off" },
    { time: 140.5, en: "girl just bend the legs and push off trust me" },
    { time: 142.1, en: "trust me" },
    { time: 145.7, en: "mouse look at you faster baby faster got" },
    { time: 150.2, en: "mouse look at you faster baby faster got it my little voodoo" },
    { time: 152.7, en: "it my little voodoo" },
    { time: 157.8, en: "doll oh it's you glad you can make it is" },
    { time: 161.4, en: "doll oh it's you glad you can make it is she up yet oh she's up she's ready to go" },
    { time: 164.4, en: "she up yet oh she's up she's ready to go and by Go I mean go as then go check the" },
    { time: 167.2, en: "and by Go I mean go as then go check the world out what you going to do what you" },
    { time: 169.3, en: "world out what you going to do what you going to say I got it covered please" },
    { time: 171.1, en: "going to say I got it covered please relax just do your" },
    { time: 173.2, en: "relax just do your job good morning mayy wavy happy" },
    { time: 176.4, en: "job good morning mayy wavy happy birthday my little mouse thank you Dad I" },
    { time: 179.4, en: "birthday my little mouse thank you Dad I know it's my birthday I have so much fun" },
    { time: 182, en: "know it's my birthday I have so much fun planned woohoo but first we go catch" },
    { time: 184.8, en: "planned woohoo but first we go catch some scorpions together just the two of" },
    { time: 186.9, en: "some scorpions together just the two of us yes D Dad please let me speak there's" },
    { time: 190.2, en: "us yes D Dad please let me speak there's something we have to talk about you want" },
    { time: 191.9, en: "something we have to talk about you want to go out into the world you can aha I" },
    { time: 195.2, en: "to go out into the world you can aha I knew you were going to say that but Dad" },
    { time: 197.1, en: "knew you were going to say that but Dad you gave me your word and you know that" },
    { time: 198.9, en: "you gave me your word and you know that I know that a Dracula's word is sacred" },
    { time: 200.8, en: "I know that a Dracula's word is sacred that our trust is the core of our wait" },
    { time: 202.9, en: "that our trust is the core of our wait what I said you can go you're just" },
    { time: 205.5, en: "what I said you can go you're just playing with me no no no no you're old" },
    { time: 207.4, en: "playing with me no no no no you're old enough to drive a hearse now you're old" },
    { time: 209.2, en: "enough to drive a hearse now you're old enough to make make your own choices you" },
    { time: 211.2, en: "enough to make make your own choices you can go holy rabies holy" },
    { time: 214, en: "can go holy rabies holy" },
    { time: 222.9, en: "rabies stop wait a second sweet fanks where are you going oh well I'm going to" },
    { time: 225.6, en: "where are you going oh well I'm going to paradise and this is some stuff that I" },
    { time: 227.5, en: "paradise and this is some stuff that I thought I would need Paradise yeah you" },
    { time: 230.3, en: "thought I would need Paradise yeah you know it's that place out there where you" },
    { time: 232.1, en: "know it's that place out there where you and Mom met aunti Wanda says you two" },
    { time: 234.6, en: "and Mom met aunti Wanda says you two were just like Zing I don't know from" },
    { time: 237.7, en: "were just like Zing I don't know from Zing where did you find that card in one" },
    { time: 240.1, en: "Zing where did you find that card in one of your drawers why won't you ever tell" },
    { time: 242.2, en: "of your drawers why won't you ever tell me about how you met it's actually" },
    { time: 244, en: "me about how you met it's actually Hawaii ha what look honey I know you're" },
    { time: 248.3, en: "Hawaii ha what look honey I know you're excited but everyone has gone to Great" },
    { time: 250.1, en: "excited but everyone has gone to Great Lanes to come see you on your birthday I" },
    { time: 253.1, en: "Lanes to come see you on your birthday I know they always do aren't it getting a" },
    { time: 256, en: "know they always do aren't it getting a little old for these parties I love them" },
    { time: 258.7, en: "little old for these parties I love them but I really want to see new things" },
    { time: 261.8, en: "but I really want to see new things maybe meet somebody my" },
    { time: 263.9, en: "maybe meet somebody my age come on no no don't do that don't" },
    { time: 267.5, en: "age come on no no don't do that don't give me the pouty bat face okay there is" },
    { time: 270.6, en: "give me the pouty bat face okay there is a human Village just a little ways past" },
    { time: 273.1, en: "a human Village just a little ways past the cemetery you could go there and be" },
    { time: 275.4, en: "the cemetery you could go there and be back in like 30 minutes or so it should" },
    { time: 277.7, en: "back in like 30 minutes or so it should be plenty for your first time well it's" },
    { time: 281.2, en: "be plenty for your first time well it's not hwi but I guess it's still" },
    { time: 284, en: "not hwi but I guess it's still technically out there okay okay" },
    { time: 287.9, en: "technically out there okay okay" },
    { time: 291.1, en: "okay thanks for trusting me of course my" },
    { time: 294.2, en: "okay thanks for trusting me of course my little one I gave you my" },
    { time: 303.7, en: "yeah it's a mess back" },
    { time: 305.6, en: "yeah it's a mess back" },
    { time: 328, en: "Transylvania human tree since 1898 your safest destination take itinerary I have" },
    { time: 330.8, en: "safest destination take itinerary I have personally designed a spectacular" },
    { time: 332.6, en: "personally designed a spectacular schedule of events all leading to my" },
    { time: 334.5, en: "schedule of events all leading to my daughter's birthday Extravaganza" },
    { time: 336.4, en: "daughter's birthday Extravaganza tomorrow we always look forward to" },
    { time: 338.3, en: "tomorrow we always look forward to coming every year Cal we enjoy the" },
    { time: 340.5, en: "coming every year Cal we enjoy the safety so much of course that's why we" },
    { time: 342.9, en: "safety so much of course that's why we built it yes good" },
    { time: 344.7, en: "built it yes good evening you Marty you look pale as well" },
    { time: 348.7, en: "evening you Marty you look pale as well sir sir sir we have an urgent plumbing" },
    { time: 351.4, en: "sir sir sir we have an urgent plumbing issue Plumbing on it Mr gou again there" },
    { time: 355.1, en: "issue Plumbing on it Mr gou again there is a clog toilet in room" },
    { time: 358.2, en: "is a clog toilet in room 348 it's all okay we all get stomach AES" },
    { time: 360.9, en: "348 it's all okay we all get stomach AES Mr" },
    { time: 362.8, en: "Mr" },
    { time: 371, en: "Bigfoot hey kids reel it in you're only supposed to make Mom and Dad" },
    { time: 372.9, en: "supposed to make Mom and Dad miserable no no is that any way to" },
    { time: 375.4, en: "miserable no no is that any way to behave this is a hotel not a cemetery hi" },
    { time: 378.7, en: "behave this is a hotel not a cemetery hi Uncle" },
    { time: 379.9, en: "Uncle TR track how are you way my old friend" },
    { time: 383.7, en: "TR track how are you way my old friend couldn't wait for this weekend always" },
    { time: 385.2, en: "couldn't wait for this weekend always great to be out of the Shadows for a" },
    { time: 386.3, en: "great to be out of the Shadows for a couple days the family looks beautiful" },
    { time: 388.6, en: "couple days the family looks beautiful let me just clean up their filled" },
    { time: 391.1, en: "let me just clean up their filled" },
    { time: 409.3, en: "housekeeping Franky my boy look at you still traveling by mail Mr Cheapo huh" },
    { time: 411.7, en: "still traveling by mail Mr Cheapo huh it's not a money thing I have a plane" },
    { time: 413.6, en: "it's not a money thing I have a plane phobia okay I mean at any moment those" },
    { time: 415.7, en: "phobia okay I mean at any moment those engines could catch fire yeah yeah fire" },
    { time: 418.5, en: "engines could catch fire yeah yeah fire bad we" },
    { time: 420.3, en: "bad we know August this for come on does that" },
    { time: 423.8, en: "know August this for come on does that look like Frankenstein's head hey dra" },
    { time: 425.8, en: "look like Frankenstein's head hey dra buddy what's going on with your cape tip" },
    { time: 427.2, en: "buddy what's going on with your cape tip what do you mean who pitched me guilty" },
    { time: 430.3, en: "what do you mean who pitched me guilty you're irresistible yes very amusing" },
    { time: 433, en: "you're irresistible yes very amusing Invisible Man hello great to see" },
    { time: 436.7, en: "Invisible Man hello great to see you I never get" },
    { time: 440.3, en: "you I never get old missed me miss me miss me miss me" },
    { time: 444.2, en: "old missed me miss me miss me miss me okay you win hold this bacon why am I" },
    { time: 446.7, en: "okay you win hold this bacon why am I holding bacon ah no get him off" },
    { time: 457.2, en: "ow here comes the party hello Murray dra what's up buddy" },
    { time: 461.4, en: "party hello Murray dra what's up buddy the sand Murray the sand always with the" },
    { time: 466.1, en: "the sand Murray the sand always with the sand wolfy W" },
    { time: 474.1, en: "Frank I love this guy you're always bringing in Full Tilt you're looking" },
    { time: 475.9, en: "bringing in Full Tilt you're looking skinny too now that you're just a head" },
    { time: 479, en: "skinny too now that you're just a head okay you'll pay for" },
    { time: 480.2, en: "okay you'll pay for" },
    { time: 482, en: "that so what's up dra the hotel is" },
    { time: 484.6, en: "that so what's up dra the hotel is looking off the hook hey guys watch" },
    { time: 492.3, en: "this by the way you were right about those directions oh good good yeah I" },
    { time: 494.7, en: "those directions oh good good yeah I took the Tigers through the Nile and" },
    { time: 496.2, en: "took the Tigers through the Nile and there was absolutely no" },
    { time: 507.7, en: "traffic I thought I found a love but she was just a fling and then I at a felt a" },
    { time: 509.7, en: "was just a fling and then I at a felt a different thing it's like you're hit in" },
    { time: 510.9, en: "different thing it's like you're hit in the ring like you're pulled by a string" },
    { time: 512.3, en: "the ring like you're pulled by a string can't breath like you're choking on a" },
    { time: 513.4, en: "can't breath like you're choking on a chicken wing it was a thing called a" },
    { time: 514.9, en: "chicken wing it was a thing called a sing and I wanted to sing and listen to" },
    { time: 516.6, en: "sing and I wanted to sing and listen to the Ballads of the man s looks in your" },
    { time: 518.7, en: "the Ballads of the man s looks in your eyes and itly spring like in The Lion" },
    { time: 526.4, en: "King don't I'm Z" },
    { time: 530.4, en: "don't I'm Z we Singing in the Rain now I'm feeling" },
    { time: 533.8, en: "we Singing in the Rain now I'm feeling no pain it's a real time of" },
    { time: 537.6, en: "no pain it's a real time of cating cuz you're" },
    { time: 540.5, en: "cating cuz you're my D you ready to throw down no no I" },
    { time: 543.9, en: "my D you ready to throw down no no I just came closer to to hear you better" },
    { time: 546.4, en: "just came closer to to hear you better oh come on just give it a try all right" },
    { time: 548.8, en: "oh come on just give it a try all right maybe just a little so listen all you" },
    { time: 550.7, en: "maybe just a little so listen all you sing is from here to Beijing you better" },
    { time: 552.3, en: "sing is from here to Beijing you better the boxing get ready to cling cuz if" },
    { time: 554.1, en: "the boxing get ready to cling cuz if love was money you" },
    { time: 556.6, en: "love was money you be was aing a and it was only one lady" },
    { time: 560.4, en: "be was aing a and it was only one lady in the for me you better know one thing" },
    { time: 563.1, en: "in the for me you better know one thing the only thing you're going to sing is" },
    { time: 564.3, en: "the only thing you're going to sing is the wed" },
    { time: 573.2, en: "ring singing in now I don't have care I'm winning from The Zing that we Shar" },
    { time: 577.2, en: "I'm winning from The Zing that we Shar singing in the ring now I'm" },
    { time: 579.4, en: "singing in the ring now I'm" },
    { time: 580.7, en: "feeling" },
    { time: 586.5, en: "of you're knock you right out of that ring" },
    { time: 590.1, en: "you're knock you right out of that ring bettering pay ATT to the unde" },
    { time: 605, en: "no no no no you mustn't give in to your Cravings it's not good for the baby you" },
    { time: 607.7, en: "Cravings it's not good for the baby you need to increase your spider intake so" },
    { time: 609.4, en: "need to increase your spider intake so he'll be able to climb ceilings properly" },
    { time: 611.4, en: "he'll be able to climb ceilings properly and eat lots of sheep" },
    { time: 613.8, en: "and eat lots of sheep fire I love you Dad but we don't even" },
    { time: 616.4, en: "fire I love you Dad but we don't even know if the kid's going to be a vampire" },
    { time: 618.4, en: "know if the kid's going to be a vampire I'd be thrilled if the baby's humany" },
    { time: 620.2, en: "I'd be thrilled if the baby's humany just like Johnny humany with thousands" },
    { time: 622.8, en: "just like Johnny humany with thousands of years of Dracula jeans not going to" },
    { time: 625.4, en: "of years of Dracula jeans not going to happen as long as the baby's healthy of" },
    { time: 627.9, en: "happen as long as the baby's healthy of course a healthy little vampire or human" },
    { time: 631.3, en: "course a healthy little vampire or human yes a human who can fly as a bat here" },
    { time: 634.8, en: "yes a human who can fly as a bat here just have some monster ball soup it's" },
    { time: 637.1, en: "just have some monster ball soup it's your mommy's" },
    { time: 645.2, en: "recipe a thank you Dad just like you made it when I was a kid my" },
    { time: 647.5, en: "made it when I was a kid my" },
    { time: 659.7, en: "favorite" },
    { time: 673.7, en: "sorry sir only the father is allowed the" },
    { time: 676.8, en: "sorry sir only the father is allowed the delivery room really I mean okay he he's" },
    { time: 680.3, en: "delivery room really I mean okay he he's the family I" },
    { time: 690.8, en: "guess oh look it's a boy it's a boy the Dracula bloodline carries on no one will" },
    { time: 694.9, en: "Dracula bloodline carries on no one will ever harm you as long as I'm here my" },
    { time: 697.6, en: "ever harm you as long as I'm here my little devil dog dad can I hold my baby" },
    { time: 701.3, en: "little devil dog dad can I hold my baby if I were dad I'd say yes but I'm the" },
    { time: 704, en: "if I were dad I'd say yes but I'm the nurse Francine hey here you go" },
    { time: 719.7, en: "b little Dennis is a year old now" },
    { time: 723.3, en: "little Dennis is a year old now" },
    { time: 725, en: "wow nice yeah cute" },
    { time: 736.4, en: "kid why are we doing this you'd rather be listening to those putrid new songs" },
    { time: 738.6, en: "be listening to those putrid new songs what happened to Michael Royer corpse" },
    { time: 740.4, en: "what happened to Michael Royer corpse aore or old MC whale wolf had an" },
    { time: 750.5, en: "axe we you shouldn't be up here dra who's ready to fly see me like a" },
    { time: 753.6, en: "who's ready to fly see me like a superhero better like a vampire this" },
    { time: 757.5, en: "superhero better like a vampire this thing is rickety you know maybe the kid" },
    { time: 759.6, en: "thing is rickety you know maybe the kid isn't supposed to fly quiet this is how" },
    { time: 762.2, en: "isn't supposed to fly quiet this is how they learn you throw them and they" },
    { time: 763.9, en: "they learn you throw them and they figure it out it's how I was taught I" },
    { time: 767, en: "figure it out it's how I was taught I want to fly now ah the bad you know papa" },
    { time: 770.1, en: "want to fly now ah the bad you know papa is right here if you need him uh I can't" },
    { time: 772.9, en: "is right here if you need him uh I can't watch this please don't here we" },
    { time: 777.8, en: "watch this please don't here we go" },
    { time: 785.8, en: "he's still not flying he will still not it'll" },
    { time: 789.1, en: "will still not it'll happen this is a tll tower that's why" },
    { time: 791.7, en: "happen this is a tll tower that's why it's good you you should get him he's" },
    { time: 794.2, en: "it's good you you should get him he's going to fall to his death he's taking" },
    { time: 795.9, en: "going to fall to his death he's taking his" },
    { time: 797.5, en: "his time track I did that my first time he's" },
    { time: 802, en: "time track I did that my first time he's getting too close to the" },
    { time: 803.6, en: "getting too close to the ground you know what he's not going to" },
    { time: 807.8, en: "ground you know what he's not going to fly" },
    { time: 819.6, en: "I told you Papa's always here for you again again oh dear oh my devil we're" },
    { time: 822.9, en: "again again oh dear oh my devil we're going to have to report this you mean to" },
    { time: 824.8, en: "going to have to report this you mean to the papers I guess it was pretty cool" },
    { time: 827.1, en: "the papers I guess it was pretty cool but I'm not about getting pressed no sir" },
    { time: 829.6, en: "but I'm not about getting pressed no sir I mean the authorities I I can't not" },
    { time: 832, en: "I mean the authorities I I can't not report child endangerment whoa listen to" },
    { time: 834.6, en: "report child endangerment whoa listen to me that was fun your singing is child" },
    { time: 837.9, en: "me that was fun your singing is child endangerment should we go down and help" },
    { time: 840.1, en: "endangerment should we go down and help him nope I told him this was nuts he's" },
    { time: 842.6, en: "him nope I told him this was nuts he's on his own we have to call the boy's" },
    { time: 844.6, en: "on his own we have to call the boy's mother no that ain't happening his" },
    { time: 846.9, en: "mother no that ain't happening his mother's already Nazi cuckoo I have to" },
    { time: 849.8, en: "mother's already Nazi cuckoo I have to follow protocol you will not follow" },
    { time: 854, en: "follow protocol you will not follow protocol I'm a vampire I can't be" },
    { time: 857.1, en: "protocol I'm a vampire I can't be hypnotized all right now please don't" },
    { time: 860, en: "hypnotized all right now please don't make me call the police no one's calling" },
    { time: 870.6, en: "nobody stop that Ro we make that" },
    { time: 883.9, en: "Happ are we bad guys Papa dra bad no you're the best kid in the world" },
    { time: 887.7, en: "bad no you're the best kid in the world We Didn't Start the Fire it was the" },
    { time: 889.9, en: "We Didn't Start the Fire it was the tower that's a very unsafe Tower you're" },
    { time: 893, en: "tower that's a very unsafe Tower you're lucky we don't call the authorities" },
    { time: 895.6, en: "lucky we don't call the authorities let's go my hero keep eyes I'm Batman to" },
    { time: 899, en: "let's go my hero keep eyes I'm Batman to the" },
    { time: 899.7, en: "the Batmobile yes to" },
    { time: 911.3, en: "the oh my goodness leard if you really look That Hideous I don't think I can" },
    { time: 912.9, en: "look That Hideous I don't think I can hang out with you guys what's the deal" },
    { time: 915.6, en: "hang out with you guys what's the deal is this a party pick up a phone I don't" },
    { time: 918.7, en: "is this a party pick up a phone I don't care if Johnny said it's a cool app" },
    { time: 921.2, en: "care if Johnny said it's a cool app Johnny's still new here now parriage" },
    { time: 924, en: "Johnny's still new here now parriage head did you call a hearse for the" },
    { time: 925.3, en: "head did you call a hearse for the gremlin Birds no you're checking your" },
    { time: 928, en: "gremlin Birds no you're checking your Facebook page again dra I told the guys" },
    { time: 931.2, en: "Facebook page again dra I told the guys social media is the best way to promote" },
    { time: 932.9, en: "social media is the best way to promote the hotel right" },
    { time: 935.2, en: "the hotel right Clifton so dra I wanted to go through" },
    { time: 937.8, en: "Clifton so dra I wanted to go through some thoughts I had as your new human" },
    { time: 939.4, en: "some thoughts I had as your new human relations coordinating co-assistant sure" },
    { time: 941.9, en: "relations coordinating co-assistant sure it's a real job not a cheap excuse to" },
    { time: 943.7, en: "it's a real job not a cheap excuse to keep M happy so you'll never leave here" },
    { time: 946.2, en: "keep M happy so you'll never leave here right so I was thinking since we have so" },
    { time: 948.8, en: "right so I was thinking since we have so many humans now maybe uh update some of" },
    { time: 951.7, en: "many humans now maybe uh update some of the acts like maybe the magician what's" },
    { time: 954, en: "the acts like maybe the magician what's wrong with Harry 3i well he might be a" },
    { time: 956.5, en: "wrong with Harry 3i well he might be a little old school for the humans tell me" },
    { time: 959, en: "little old school for the humans tell me sir what was your card uh the three of" },
    { time: 963.1, en: "sir what was your card uh the three of Spades is this your card my friend" },
    { time: 969.2, en: "Spades is this your card my friend whoa no Harry's great can't blame Harry" },
    { time: 972.4, en: "whoa no Harry's great can't blame Harry for the crowd not being Hipp okay what" },
    { time: 974.7, en: "for the crowd not being Hipp okay what about Wayne Wayne are you not he's my" },
    { time: 977, en: "about Wayne Wayne are you not he's my boy he maybe something other than tennis" },
    { time: 979.7, en: "boy he maybe something other than tennis okay so what you want to do is lift the" },
    { time: 981.8, en: "okay so what you want to do is lift the racket right on impact so you get that" },
    { time: 983.7, en: "racket right on impact so you get that nice Top Spin try and hit" },
    { time: 997.2, en: "what is that what's the noise it it's on me it's just the cell phone I got you" },
    { time: 999.2, en: "me it's just the cell phone I got you Clifton's sending you a text so you can" },
    { time: 1000.7, en: "Clifton's sending you a text so you can practice how to write" },
    { time: 1002.9, en: "practice how to write" },
    { time: 1005.4, en: "back what it's not doing it I got it" },
    { time: 1009.8, en: "back what it's not doing it I got it dear" },
    { time: 1017.3, en: "dra now you can text Clifton all right fine how how do you do this maybe it's" },
    { time: 1020, en: "fine how how do you do this maybe it's your fingernails it's easy look I'll" },
    { time: 1022.1, en: "your fingernails it's easy look I'll text Mavis psyched for datee night see" },
    { time: 1026.4, en: "text Mavis psyched for datee night see and now look she texted right back got" },
    { time: 1028.4, en: "and now look she texted right back got to cancel can't leave" },
    { time: 1030.4, en: "to cancel can't leave Dennis okay are we never allowed to be" },
    { time: 1035.5, en: "Dennis okay are we never allowed to be alone again I need to feel loved too and" },
    { time: 1042.2, en: "alone again I need to feel loved too and sent okay all that taught me is that" },
    { time: 1044.9, en: "sent okay all that taught me is that you're pathetic yeah got it maybe you" },
    { time: 1047.3, en: "you're pathetic yeah got it maybe you should just get Bluetooth" },
    { time: 1048.9, en: "should just get Bluetooth okay Bluetooth come over" },
    { time: 1059.9, en: "what stop squirming why are you doing this because this is wrong why doesn't" },
    { time: 1063.2, en: "this because this is wrong why doesn't anybody get that humans don't belong" },
    { time: 1066.6, en: "anybody get that humans don't belong with monsters you're wrong I am not I am" },
    { time: 1071.3, en: "with monsters you're wrong I am not I am holding you hostage and me and my crew" },
    { time: 1074.5, en: "holding you hostage and me and my crew are going to tear that human hugging" },
    { time: 1076.6, en: "are going to tear that human hugging hotel to shred you can't really why not" },
    { time: 1082, en: "hotel to shred you can't really why not keep keepa why keep will make Papa track" },
    { time: 1086.6, en: "keep keepa why keep will make Papa track sad oh sad and what are you going to do" },
    { time: 1090.9, en: "sad oh sad and what are you going to do about it I don't know you know why you" },
    { time: 1094.4, en: "about it I don't know you know why you don't know keepa you're just a weak let" },
    { time: 1098.2, en: "don't know keepa you're just a weak let her" },
    { time: 1132.6, en: "what was that Dennis we're coming you okay Winnie yes" },
    { time: 1137.3, en: "coming you okay Winnie yes mying" },
    { time: 1169.5, en: "having fun oh I'm having even more fun now that you're here you know Dad I feel" },
    { time: 1172.5, en: "now that you're here you know Dad I feel really lucky to have this time with you" },
    { time: 1174.9, en: "really lucky to have this time with you all of us together it's really special" },
    { time: 1177.8, en: "all of us together it's really special me too spider monkey now are you ready" },
    { time: 1181.3, en: "me too spider monkey now are you ready for me to destroy you in Monster Ball" },
    { time: 1185.2, en: "for me to destroy you in Monster Ball woohoo come on Papa oh bring it on for I" },
    { time: 1189.4, en: "woohoo come on Papa oh bring it on for I am king of family" },
    { time: 1199.1, en: "fun all right who is ready to get pummel I got to warn you I played second team" },
    { time: 1201.4, en: "I got to warn you I played second team co-ed intral volleyball at Santa Cruz" },
    { time: 1204.9, en: "co-ed intral volleyball at Santa Cruz sure pal whatever you say everybody just" },
    { time: 1207.9, en: "sure pal whatever you say everybody just please watch the hair watch the hair oh" },
    { time: 1211.9, en: "please watch the hair watch the hair oh let's go let's do this oh my gosh this" },
    { time: 1214.1, en: "let's go let's do this oh my gosh this is going to be so much fun get ready" },
    { time: 1217.2, en: "is going to be so much fun get ready here comes the" },
    { time: 1222, en: "pain not the hair not the" },
    { time: 1230.6, en: "hair no no no no no no" },
    { time: 1233.6, en: "no Captain Erica you are needed on death" },
    { time: 1237.7, en: "no Captain Erica you are needed on death next up bye-bye" },
    { time: 1240.8, en: "next up bye-bye Dracula" },
    { time: 1284.2, en: "destination the underwater volcano everyone grab your scuba gear" },
    { time: 1287, en: "volcano everyone grab your scuba gear and get ready to explore the wonders of" },
    { time: 1290.1, en: "and get ready to explore the wonders of the" },
    { time: 1291.2, en: "the sea especially you Count" },
    { time: 1301.3, en: "Dracula you see that P She Likes you oh no no no no no no no no that sounds like" },
    { time: 1303, en: "no no no no no no no no that sounds like a zing in full effect oh no no no no no" },
    { time: 1305.6, en: "a zing in full effect oh no no no no no no no oh yes yes yes yes yes I'm just" },
    { time: 1308.5, en: "no no oh yes yes yes yes yes I'm just here to have family fun family family" },
    { time: 1311.4, en: "here to have family fun family family fun" },
    { time: 1312, en: "fun" },
    { time: 1327.2, en: "you look ravishing oh uh thank you I just" },
    { time: 1340.3, en: "woo so um does Captain Erica have a last name uh uh uh uh oh guacamole Erica" },
    { time: 1345, en: "name uh uh uh uh oh guacamole Erica guacamole that's so International no" },
    { time: 1350.1, en: "guacamole that's so International no guacamole for us to share oh how" },
    { time: 1353.3, en: "guacamole for us to share oh how beautiful is that full moon tonight look" },
    { time: 1355.4, en: "beautiful is that full moon tonight look right behind" },
    { time: 1356.9, en: "right behind" },
    { time: 1360.4, en: "you the food here is to die" },
    { time: 1364.1, en: "you the food here is to die" },
    { time: 1373.3, en: "for holy moly that was a lot of" },
    { time: 1377, en: "for holy moly that was a lot of guacamole are you feeling all right" },
    { time: 1380.1, en: "guacamole are you feeling all right totally fine why no" },
    { time: 1383.8, en: "totally fine why no reason oh there must have been garlic in" },
    { time: 1388.4, en: "reason oh there must have been garlic in the guacamole oh no isn't that deadly" },
    { time: 1391.6, en: "the guacamole oh no isn't that deadly for you no no no it's just" },
    { time: 1394.1, en: "for you no no no it's just that garlic" },
    { time: 1395.9, en: "that garlic" },
    { time: 1406.9, en: "intolerant was that you" },
    { time: 1409, en: "you woo oh yeah dolphin" },
    { time: 1412.6, en: "woo oh yeah dolphin" },
    { time: 1426.3, en: "Surin whoa hi Mama Hi Papa hi hi oh hey there" },
    { time: 1429.2, en: "there HiHo is my dad in there" },
    { time: 1432.2, en: "HiHo is my dad in there too don't worry I'm over here blah blah" },
    { time: 1436.1, en: "too don't worry I'm over here blah blah blah no papa dra's not here he's on his" },
    { time: 1439.8, en: "blah no papa dra's not here he's on his date" },
    { time: 1441.1, en: "date" },
    { time: 1443.6, en: "date please forgive me I I'm just very" },
    { time: 1448, en: "date please forgive me I I'm just very nervous you" },
    { time: 1449.6, en: "nervous you see I haven't had a date since my wife" },
    { time: 1456.7, en: "see I haven't had a date since my wife died how old was your daughter she was" },
    { time: 1459.9, en: "died how old was your daughter she was just an infant it was hard being a" },
    { time: 1462.3, en: "just an infant it was hard being a single dad but I I did my" },
    { time: 1466.8, en: "single dad but I I did my best" },
    { time: 1468.4, en: "best I never knew my mother either or my" },
    { time: 1471.2, en: "I never knew my mother either or my father oh I'm so sorry who raised you my" },
    { time: 1476.5, en: "father oh I'm so sorry who raised you my great-grandfather I basically grew up on" },
    { time: 1478.8, en: "great-grandfather I basically grew up on this ship that's why you're a captain" },
    { time: 1482.2, en: "this ship that's why you're a captain yeah it's all I've ever known it was" },
    { time: 1485.9, en: "yeah it's all I've ever known it was just" },
    { time: 1487.4, en: "just expected you know a family thing I" },
    { time: 1490.9, en: "expected you know a family thing I understand family is everything you have" },
    { time: 1494.4, en: "understand family is everything you have to honor the past but we make our own" },
    { time: 1497.8, en: "to honor the past but we make our own own" },
    { time: 1510.7, en: "future dad" },
    { time: 1512.7, en: "future dad" },
    { time: 1514, en: "mayis" },
    { time: 1520.4, en: "Johnny Captain Erica and I were just discussing the hospitality industry you" },
    { time: 1523.1, en: "discussing the hospitality industry you know just work stuff you're working now" },
    { time: 1526.2, en: "know just work stuff you're working now this is supposed to be a vacation a" },
    { time: 1528.4, en: "this is supposed to be a vacation a family vacation I I should really go do" },
    { time: 1531.7, en: "family vacation I I should really go do Cy" },
    { time: 1543.4, en: "things" },
    { time: 1546.2, en: "things the girls what y'all trying to" },
    { time: 1550.7, en: "the girls what y'all trying to do car magic in the" },
    { time: 1558.9, en: "air it's so look" },
    { time: 1560.1, en: "look at pop show" },
    { time: 1563.1, en: "at pop show time gu back" },
    { time: 1566.1, en: "time gu back" },
    { time: 1567.5, en: "again" },
    { time: 1582.5, en: "the what trying to do me what you trying to do it's" },
    { time: 1584.8, en: "to do it's" },
    { time: 1586.6, en: "magic" },
    { time: 1597.4, en: "whaty to" },
    { time: 1598.8, en: "whaty to" },
    { time: 1616.6, en: "do what y'all trying to do" },
    { time: 1629.4, en: "work good" },
    { time: 1630.7, en: "work good Dracula you know it B hing's beats are" },
    { time: 1634.5, en: "Dracula you know it B hing's beats are controlling the Giant Octopus thingy if" },
    { time: 1636.7, en: "controlling the Giant Octopus thingy if there's one thing I hate it's an evil DJ" },
    { time: 1640.2, en: "there's one thing I hate it's an evil DJ we need positive" },
    { time: 1647.8, en: "energy" },
    { time: 1649.2, en: "get ready for a DJ battle you just carry" },
    { time: 1653.1, en: "get ready for a DJ battle you just carry all that stuff around with you once a" },
    { time: 1655.1, en: "all that stuff around with you once a bar mitz for DJ always the bar mitz for" },
    { time: 1657.3, en: "bar mitz for DJ always the bar mitz for DJ we're going to use good music to" },
    { time: 1659.9, en: "DJ we're going to use good music to defeat his evil music what trust me I" },
    { time: 1663.2, en: "defeat his evil music what trust me I know the tunes but you've got the power" },
    { time: 1666.2, en: "know the tunes but you've got the power all right okay opening song needs to be" },
    { time: 1669.1, en: "all right okay opening song needs to be off the" },
    { time: 1670.3, en: "off the shizak got it play" },
    { time: 1679.4, en: "this I'm picking up Good Vibrations she's giving me the" },
    { time: 1681.7, en: "she's giving me the excitations I'm fing up good Vib" },
    { time: 1707.7, en: "good" },
    { time: 1732.3, en: "who this music is too powerful we're going to need something even more" },
    { time: 1733.7, en: "going to need something even more positive now" },
    { time: 1736.4, en: "positive now dra" },
    { time: 1743.8, en: "so don't" },
    { time: 1746.5, en: "so don't worry be happy don't worry be happy it" },
    { time: 1750.9, en: "worry be happy don't worry be happy it has a nice" },
    { time: 1758.1, en: "message don't worry be" },
    { time: 1760.9, en: "worry be happy I've had enough of this" },
    { time: 1768.7, en: "nonsense" },
  ],
}
