// ديالوج متزامن مع الفيديو للأجزاء الخمسين من فيلم هتل ترانسلفانيا (2012).
// التوقيت اتجاب تلقائيًا عن طريق التعرف على الكلام على صوت كل جزء (whisper base.en) — وقت كل جزء مقاس من بداية الجزء نفسه.
// مفتاح = آي دي المقطع في shadowing.ts — الستوديو بيستخدمه لو المقطع مالهوش scenes جاهزة.
import type { ShadowScene } from './shadowing'

export const HT_PARTS_DIALOGUE: Record<string, ShadowScene[]> = {
  'ht-part-01': [
    { time: 4.9, en: "Oh, look at you little babies." },
    { time: 7.1, en: "I told you, look at you!" },
    { time: 8.1, en: "Hey, hey, hey, hey!" },
    { time: 8.7, en: "Ugh." },
    { time: 10.7, en: "Right out there." },
    { time: 12.4, en: "Oh, we never go out there." },
    { time: 15.5, en: "Ever." },
    { time: 18.6, en: "And then the monsters ran away and were forced into hiding." },
    { time: 22.9, en: "But Harry the human found them and jumped out from under their bed." },
    { time: 26.7, en: "I'm scared." },
    { time: 27.3, en: "And burned their clothes and beat their toes and took their candy!" },
    { time: 32.4, en: "Don't take my candy." },
    { time: 37.4, en: "Baby Claus, you don't need to be frightened." },
    { time: 40.4, en: "I promised your mommy I would protect you forever." },
    { time: 47.8, en: "My beautiful maybe." },
    { time: 51.5, en: "Let me wipe all your poopy way." },
    { time: 55.7, en: "Those humans are nasty." },
    { time: 60.1, en: "So with daddy you will stay." },
    { time: 63.7, en: "And if a human tries to harm you, I'll simply say..." },
    { time: 73.1, en: "Because you're daddy's girl, daddy's girl." },
    { time: 78.6, en: "I'm your daddy." },
    { time: 79.7, en: "Just bend the legs and push off." },
    { time: 82.6, en: "Trust me, mouse." },
    { time: 89.7, en: "Oh, faster, baby, faster!" },
    { time: 91.9, en: "You got it, my little Buddha doll!" },
    { time: 100.1, en: "Excuse me, sir." },
    { time: 102.1, en: "What? What?" },
    { time: 103.7, en: "Ow! I'm okay." },
  ],
  'ht-part-02': [
    { time: 0.9, en: "Excuse me sir." },
    { time: 2.8, en: "Wipe, wipe!" },
    { time: 4.3, en: "Ow! I'm okay." },
    { time: 6, en: "It's ready." },
    { time: 9.6, en: "Looks good." },
    { time: 11.6, en: "Only monsters can get in." },
    { time: 13.4, en: "Oh, absolutely. It's hidden real nicely." },
    { time: 16.8, en: "You've got 400 acres of haunted forest in front of you." },
    { time: 20, en: "You've got the land of the undead on the perimeter." },
    { time: 22.4, en: "Any humans daring to even look over there will run away real quick." },
    { time: 38.9, en: "Errrr." },
    { time: 41.7, en: "But of course, Beastmark. No bonfires. No far work shows." },
    { time: 45.7, en: "Yeah, yeah, no, no fire. I get it. I get it." },
    { time: 52, en: "It's time, my darling Martha." },
    { time: 54.4, en: "The place we always talked about for Mavis." },
    { time: 57.6, en: "No one will ever honor here." },
  ],
  'ht-part-03': [
    { time: 6.3, en: "Yeah, it's a mess back there." },
    { time: 23.5, en: "Welcome to Hotel Transylvania!" },
    { time: 29.1, en: "Human pre-since 1890 years." },
    { time: 31.8, en: "Your safest destination. Take an itinerary." },
    { time: 34.5, en: "I have personally designed this spectacular schedule of events." },
    { time: 37.8, en: "I'll leave you with my daughter's birthday extra." },
    { time: 39.9, en: "Grab a ganza tomorrow." },
    { time: 41.5, en: "We always look forward to coming every year, Cal." },
    { time: 44, en: "We enjoy the safety so much." },
    { time: 45.9, en: "Of course, that's why we build you." },
    { time: 48.2, en: "Yes, good evening." },
    { time: 49.8, en: "Thank you, Marty. You look pale as well." },
    { time: 53.2, en: "Sir, sir, sir! We have an urgent plumbing issue." },
    { time: 56.7, en: "Plumbing?" },
    { time: 57.5, en: "On it. Mr. Gooligan." },
    { time: 59.4, en: "There is a clogged toilet in room 340." },
    { time: 64.2, en: "It's okay. We all get stomach aches, Mr. Big Foot." },
    { time: 72.6, en: "Hey, kids. Rail it in." },
    { time: 76.4, en: "You're only supposed to make mom and dad miserable." },
    { time: 79.4, en: "Now, now, is that any way to behave?" },
    { time: 81.5, en: "Okay, this is a hotel, not a cemetery." },
    { time: 84.2, en: "Hi, Uncle Jack." },
    { time: 86.9, en: "Track. How are you?" },
    { time: 88.4, en: "Way in my old friend!" },
    { time: 90, en: "Couldn't wait for this weekend." },
    { time: 91.4, en: "Always great to be out of the shadows for a couple of days." },
    { time: 93.3, en: "The family looks beautiful. Let me just clean up their fields." },
    { time: 97.1, en: "How's keeping?" },
  ],
  'ht-part-04': [
    { time: 1.2, en: "Huh?" },
    { time: 2, en: "Huh?" },
    { time: 11.1, en: "Thank you, my boy." },
    { time: 12.4, en: "Look at you." },
    { time: 13.2, en: "Still traveling by mail, Mr. Chippo." },
    { time: 15.3, en: "It's not a money thing." },
    { time: 16.8, en: "I have a plain phobia." },
    { time: 18.1, en: "I mean, at any moment, those engines could catch you." },
    { time: 20.4, en: "Fire!" },
    { time: 21, en: "Yeah, yeah." },
    { time: 21.8, en: "All your fun." },
    { time: 23.3, en: "We know." },
    { time: 25.3, en: "August is part of Ted." },
    { time: 27, en: "Come on." },
    { time: 27.7, en: "Does that look like Frankenstein's head?" },
    { time: 29.7, en: "Hey, Trek." },
    { time: 30.3, en: "Buddy, what's going on with your cape?" },
    { time: 31.5, en: "What are you doing?" },
    { time: 32.9, en: "Who bitched me?" },
    { time: 34, en: "Guilty." },
    { time: 35, en: "You're irresistible." },
    { time: 35.4, en: "Yes, very amusing, invisible man." },
    { time: 38.4, en: "Hello, great to see you." },
    { time: 41.3, en: "Oh, never gets old." },
    { time: 44.5, en: "Oh, oh, oh, oh." },
    { time: 46.1, en: "Missed me." },
    { time: 47.1, en: "Missed me, missed me, missed me." },
    { time: 49.1, en: "Okay, you win." },
    { time: 50.5, en: "Hold this bacon." },
    { time: 51.5, en: "Why am I holding big?" },
    { time: 53.3, en: "No, get him off." },
    { time: 54.9, en: "Ah!" },
    { time: 60.2, en: "Here comes the party!" },
    { time: 63.6, en: "Hello, Murray!" },
    { time: 65.2, en: "Drac, what's up, buddy?" },
    { time: 67.2, en: "The sand, Murray, the sand." },
    { time: 69.5, en: "The worries with the sand." },
    { time: 71.8, en: "Whoa!" },
    { time: 72.3, en: "Whoa!" },
    { time: 73, en: "Whoa!" },
    { time: 73.9, en: "One dog!" },
    { time: 75.2, en: "Frac!" },
    { time: 76.2, en: "Whoa!" },
    { time: 78.6, en: "I love this guy." },
    { time: 80.1, en: "He's always bringing it full tilt." },
    { time: 82.1, en: "You're looking skinny, too." },
    { time: 83.5, en: "Now that you're just ahead." },
    { time: 84.7, en: "Oh, okay." },
    { time: 86.3, en: "You'll pay for that." },
    { time: 89.7, en: "So what's up, Drac?" },
    { time: 90.8, en: "The hotel is looking off the hook." },
    { time: 93.6, en: "Hey, guys, watch this." },
    { time: 97.8, en: "By the way, you were right about those directions." },
    { time: 100.3, en: "Oh, good, good." },
    { time: 101.1, en: "Yeah, I took the titers through the now," },
    { time: 103.5, en: "and it was absolutely good traffic." },
  ],
  'ht-part-05': [
    { time: 4.4, en: "You're kidding me right in my lobby a swam and I don't like that" },
    { time: 9.7, en: "I was keeping I was not the cause of that" },
    { time: 28.9, en: "Only Martha were here to see this she's always here" },
    { time: 32.8, en: "Okay friends, I am so glad you are here to celebrate another birthday for my sweet little Mavis and another" },
    { time: 43, en: "successful year of refuge from them" },
    { time: 48.5, en: "These are recent human images our surveillance has uncovered they are getting fatter so as to overpower us and" },
    { time: 56.5, en: "They are wearing less clothing allowing more movement to strangle us or cut open our heads and put candy in it" },
    { time: 63, en: "But they will never find us here evil villain you will never win" },
    { time: 68.6, en: "Okay, dog the fun starts in 30 minutes right now. I have to see my little girl. She's not so little anymore. Yes. She" },
    { time: 83.6, en: "Frank did you book us for a time the massage?" },
    { time: 86.2, en: "Did you get us a table at hunchbacks? Did you do anything?" },
    { time: 91.4, en: "You're welcome" },
    { time: 95.2, en: "Dad you said that when I turned 118 I could go out into the world like every other adult that gets to come and go from this hotel" },
    { time: 102.1, en: "But maybe way the instant safe bla bla bla dad" },
  ],
  'ht-part-06': [
    { time: 0, en: "Blah, blah, blah." },
    { time: 1, en: "Dad, 30 years ago you promised." },
    { time: 3.5, en: "I remember when we were both eating mice" },
    { time: 5.1, en: "and you specifically said that you gave me your work." },
    { time: 11.8, en: "Ooh, not disturbed." },
    { time: 13.3, en: "Ooh, not disturbed." },
    { time: 14.9, en: "Ooh, not disturbed." },
    { time: 16.2, en: "Ooh, not disturbed." },
    { time: 16.6, en: "Not disturbed." },
    { time: 17.6, en: "Ooh, not disturbed." },
    { time: 17.9, en: "Good morning, your evidence." },
    { time: 19.6, en: "Made clean up this room." },
    { time: 22.9, en: "Oh, it's you." },
    { time: 24.9, en: "Glad you could make it." },
    { time: 25.8, en: "Is she up yet?" },
    { time: 26.7, en: "Oh, she's up." },
    { time: 27.9, en: "She's ready to go." },
    { time: 29.1, en: "And by go, I mean go." },
    { time: 31.1, en: "As in go check the world out." },
    { time: 32.5, en: "What you gonna do?" },
    { time: 34, en: "What you gonna say?" },
    { time: 34.8, en: "I got it covered." },
    { time: 35.6, en: "Please relax." },
    { time: 36.6, en: "Just do your job." },
    { time: 39, en: "Good morning, maybe wavy." },
    { time: 41.3, en: "Happy birthday, my little mouse." },
    { time: 43.6, en: "Thank you, Dad." },
    { time: 44.5, en: "I know it's my birthday." },
    { time: 46.2, en: "I have so much fun planned." },
    { time: 48.1, en: "Woo-hoo!" },
    { time: 49, en: "But first, we go catch some scorpions together." },
    { time: 51.9, en: "Just the two of us." },
    { time: 52.9, en: "Yes, Dad." },
    { time: 53.5, en: "Dad, please let me speak." },
    { time: 55.8, en: "There's something we have to talk about." },
    { time: 57.4, en: "You want to go out into the world, you can't." },
    { time: 59.7, en: "Ah-ha!" },
    { time: 61.1, en: "I knew you were gonna say that." },
    { time: 62.7, en: "But Dad, you gave me your word." },
    { time: 64.4, en: "And you know that I know that a Dracula's word is sacred." },
    { time: 67.1, en: "That our trust is the core of our..." },
    { time: 68.6, en: "Wait, what?" },
    { time: 69.8, en: "I said you can go." },
    { time: 71.4, en: "You're just playing with me." },
    { time: 72.7, en: "No, no, no." },
    { time: 73.5, en: "You're old enough to drive a horse now." },
    { time: 75.5, en: "You're old enough to make your own choices." },
    { time: 77.8, en: "You can go." },
    { time: 78.9, en: "Holy rabies!" },
    { time: 80.1, en: "Holy rabies!" },
    { time: 87.6, en: "Whoa, stop!" },
    { time: 88.6, en: "Wait a second, sweet thing." },
    { time: 90.1, en: "Where are you going?" },
    { time: 91.4, en: "Oh, well, I'm going to paradise." },
    { time: 93.1, en: "And this is some stuff that I thought I would need." },
    { time: 95.8, en: "Paradise!" },
    { time: 97, en: "Yeah, you know." },
    { time: 98.4, en: "Is that place out there where you and Mom met?" },
    { time: 101, en: "Antoine de says you two were just like zing." },
    { time: 104.2, en: "I don't know from zing." },
  ],
  'ht-part-07': [
    { time: 0, en: "In one of your drawers." },
    { time: 1.4, en: "Why won't you ever tell me about how you met?" },
    { time: 3.5, en: "It's actually Hawaii." },
    { time: 5.1, en: "How what?" },
    { time: 6.4, en: "Look, honey, I know you're excited," },
    { time: 9.2, en: "but everyone has gone to great lengths" },
    { time: 10.9, en: "to come see you on your birthday." },
    { time: 13.2, en: "I know, they always do." },
    { time: 15.8, en: "Aren't it getting a little old for these parties?" },
    { time: 18.6, en: "I love them, but I really want to see new things." },
    { time: 22.8, en: "Maybe meet somebody my age." },
    { time: 25.6, en: "Come on, no, no, don't do that." },
    { time: 28.1, en: "Don't give me the pouty bad face." },
    { time: 31, en: "Okay, there is a human village" },
    { time: 32.9, en: "just a little ways past the cemetery." },
    { time: 35.7, en: "You could go there and be back in like 30 minutes or so." },
    { time: 38.8, en: "It should be plenty for your first time." },
    { time: 41.5, en: "Well, it's not hoe-y, but I guess it's still technically out there." },
    { time: 47.4, en: "Okay, okay, okay." },
    { time: 49.2, en: "Thanks for trusting me." },
    { time: 55.7, en: "Of course, my little one." },
    { time: 57.5, en: "I gave you my word." },
    { time: 63.6, en: "You excited about tomorrow?" },
    { time: 64.9, en: "Not as excited as I am right now." },
    { time: 67.5, en: "You're not gonna believe this," },
    { time: 68.6, en: "but Dad is letting me go out on my own to see a human village." },
    { time: 71.4, en: "What?" },
    { time: 72.4, en: "Excuse me." },
    { time: 73.4, en: "What? You track?" },
    { time: 74.6, en: "Have you lost it?" },
    { time: 76, en: "Let me your own daughter out there with those horrible humans." },
    { time: 78.9, en: "You always tell us about?" },
    { time: 80.2, en: "That's why you built this place." },
    { time: 82.4, en: "They hate us." },
    { time: 83.5, en: "They're vicious." },
    { time: 84.5, en: "And they're very loud." },
    { time: 86.2, en: "Anti-unice, maybe they've changed." },
    { time: 88.9, en: "I'm just gonna fly down the street and see how it goes." },
    { time: 91.4, en: "Okay, honey, be safe." },
    { time: 93.4, en: "Bring warm clothes in a sword." },
    { time: 95.5, en: "And look out for pitchforks." },
    { time: 96.7, en: "Don't you let anyone scoop your brains out, Eva?" },
    { time: 99.1, en: "Maybe stay in the shadows." },
    { time: 100.2, en: "It's more fun to just observe from under a house." },
    { time: 102.7, en: "Guys, guys, she can handle it." },
    { time: 104.8, en: "She's a Dracula f-" },
    { time: 105.2, en: "Dracula f-" },
  ],
  'ht-part-08': [
    { time: 0, en: "She can handle it. She's a Dracula for Pete's sake." },
    { time: 3.4, en: "But seriously, watch out for Fire." },
    { time: 5.9, en: "Fire bad." },
    { time: 18.3, en: "Everyone!" },
    { time: 32.9, en: "I can't believe how calm you are about her leaving. I'm proud of you." },
    { time: 36.8, en: "Drag? Drag." },
    { time: 39.4, en: "Where'd a drag go?" },
    { time: 50.8, en: "There's the cemetery, just like Dad said." },
    { time: 87.9, en: "Hello? Anybody out there?" },
    { time: 103.6, en: "Ooh!" },
    { time: 104.3, en: "Oh! Hi!" },
  ],
  'ht-part-09': [
    { time: 2.4, en: "Everything okay? My name is Mavis Dracula and..." },
    { time: 6.4, en: "Vampire! Vampire!" },
    { time: 8.9, en: "You're gonna close? Really?" },
    { time: 10.3, en: "Vampire! We take your candy!" },
    { time: 15.2, en: "I'm friendly! I really am!" },
    { time: 18.1, en: "I'm down now! I just wanted to say hi!" },
    { time: 22.7, en: "Vampire!" },
    { time: 24.9, en: "Two! Two!" },
    { time: 25.5, en: "Two!" },
    { time: 25.9, en: "Aah! Aah!" },
    { time: 31.1, en: "Aah! Aah!" },
    { time: 38.7, en: "Aah! Aah! Aah!" },
    { time: 39.3, en: "Aah! Aah!" },
    { time: 40.9, en: "Please! I've never heard anyone! I'm homeschooled!" },
    { time: 45.1, en: "Is that garlic?" },
    { time: 46.1, en: "Holy babies! You're up fire! Can I do anything? Can I help you?" },
    { time: 63.4, en: "Dad was right!" },
    { time: 65.9, en: "Dad was right!" },
    { time: 75.1, en: "It's won't!" },
    { time: 76.9, en: "Now my baby will be safe... forever." },
    { time: 84, en: "Alright everybody, get back to work!" },
    { time: 89.9, en: "Hey! You don't need a mannequin! Leave the mannequin here! Come on!" },
  ],
  'ht-part-10': [
    { time: 13.2, en: "I'm sneaking around." },
    { time: 14.2, en: "Shh quiet." },
    { time: 17, en: "Sweetheart, have you returned so soon?" },
    { time: 19.8, en: "Um, come in dad." },
    { time: 21.5, en: "How did it go?" },
    { time: 22.9, en: "How was the big world?" },
    { time: 24, en: "How was it out there?" },
    { time: 25.4, en: "It was okay dad." },
    { time: 26.9, en: "What?" },
    { time: 27.8, en: "What's the matter?" },
    { time: 28.8, en: "Dad, you were right." },
    { time: 30.9, en: "Humans are awful." },
    { time: 32.1, en: "They were everything you said." },
    { time: 33.8, en: "They wanted to bite my toes." },
    { time: 35.4, en: "You're tall." },
    { time: 36, en: "And they had garlic on bread." },
    { time: 38.2, en: "What?" },
    { time: 39.2, en: "Look at me." },
    { time: 40.2, en: "I'm getting goosebumps." },
    { time: 41.9, en: "I'm so scared." },
    { time: 42.6, en: "I'm so sorry, sweetheart." },
    { time: 47.8, en: "I hate that you had to see that." },
    { time: 50.5, en: "I'm so sorry I doubted you." },
    { time: 54.5, en: "I'll never leave here again." },
    { time: 58.2, en: "Okay." },
    { time: 59.3, en: "Okay." },
    { time: 60.5, en: "Look, daddy's gonna make you the best this birthday ever." },
    { time: 65.3, en: "Look what I brought you." },
    { time: 67.2, en: "Your wormcakes." },
    { time: 70.5, en: "Don't be sad anymore." },
    { time: 72.3, en: "Remember, this is the year we opened Mummy's present for you." },
    { time: 76.7, en: "What did she get me?" },
    { time: 77.7, en: "We'll see." },
    { time: 79.6, en: "She said never to open until you're 118." },
    { time: 84.1, en: "We've waited this long." },
    { time: 85.9, en: "You eat your wormcakes." },
    { time: 87.5, en: "You come down whenever you're ready, honey." },
    { time: 89.5, en: "What did you do?" },
    { time: 95.9, en: "What I had to." },
    { time: 96.8, en: "Mm-hmm." },
    { time: 98.2, en: "Sure thank me one day." },
    { time: 99.8, en: "Yeah." },
    { time: 100.3, en: "That's what the guy who struck my hand said." },
    { time: 102.8, en: "Okay." },
  ],
  'ht-part-11': [
    { time: 2.7, en: "Hey, what do you want, the cookie?" },
    { time: 11.7, en: "You did all right, man." },
    { time: 12.7, en: "Move on, there you go." },
    { time: 29.3, en: "Who are you, and how did you find this place?" },
    { time: 32, en: "Oh, I'm Jonathan, and I was just mountain climbing" },
    { time: 34.1, en: "with some dudes." },
    { time: 35.3, en: "Ah!" },
    { time: 36.4, en: "And heard this story about a spooky forest." },
    { time: 38.8, en: "And who's not going to go into a spooky forest, right?" },
    { time: 45.1, en: "Ah!" },
    { time: 46.7, en: "So then I see these goofy looking dudes on fire," },
    { time: 52, en: "and I just kind of follow them to this amazing castle." },
    { time: 55.9, en: "But of course, B-snot, no bonfires, no far work shows." },
    { time: 63.4, en: "How many of you are there?" },
    { time: 65.1, en: "Just me, I like to hit it alone." },
    { time: 67.2, en: "You meet so many awesome people in the youth hostels." },
    { time: 69.6, en: "Hey, speaking of awesome, that cape thing is killing it!" },
    { time: 73.3, en: "Does there look like a costume party here?" },
    { time: 75.3, en: "What's at my time?" },
    { time: 76.4, en: "He's just on my phone." },
    { time: 78.3, en: "You have to leave." },
    { time: 80.5, en: "Oh, no." },
    { time: 81.7, en: "Excuse me, one of your piranhas in the lake is very rude." },
    { time: 84.9, en: "He ate my sister-in-law." },
    { time: 86.9, en: "Be right with you." },
    { time: 88.8, en: "Mr. Dracula, we asked for a room with a mirror with a pole." },
    { time: 91.7, en: "The room's fine." },
    { time: 92.5, en: "We want a book of massage." },
    { time: 93.6, en: "Yes, Swedish." },
    { time: 94.4, en: "She got a room of therapy." },
    { time: 96.2, en: "We don't want a stone." },
    { time: 97.5, en: "I'll get back to you, Mr. Hydro-vac." },
    { time: 99, en: "Oh, sir." },
    { time: 99.6, en: "I need a towel, too." },
    { time: 100.6, en: "That's me, side to bed." },
    { time: 102.2, en: "I'm not here." },
    { time: 103.2, en: "Seriously, what's that?" },
    { time: 104.3, en: "It's kind of fucking breath." },
    { time: 104.9, en: "I can't breathe." },
  ],
  'ht-part-12': [
    { time: 0, en: "Seriously what's that?" },
    { time: 1.7, en: "It's kind of fucking breathe under here." },
    { time: 3.5, en: "Track!" },
    { time: 4.4, en: "Track! How to go with me!" },
    { time: 6.3, en: "Hey! Where'd you go?" },
    { time: 11, en: "Wow! The stream's kind of small for big castle. No bed, but check out these awesome dust pans they give you." },
    { time: 17.5, en: "Quiet your fool." },
    { time: 18.7, en: "What weapons are you keeping in this container? Your pitchforks?" },
    { time: 23.4, en: "Oh! I can't breathe! It's killing me!" },
    { time: 27.4, en: "Yeah, I definitely do for a fluff and fold." },
    { time: 29.9, en: "What is this?" },
    { time: 30.8, en: "A torture device. A secret mind controller. You won't read my thoughts. I won't let you." },
    { time: 38.2, en: "Dude, it's just music. Here try it." },
    { time: 42.9, en: "Ooh! It's taking my soul!" },
    { time: 47.4, en: "What? It's a good jam! W-gram bomb." },
    { time: 51.2, en: "You need to go. No human has ever entered this castle. And if someone should see you, the safety of the hotel." },
    { time: 59.2, en: "Well, this sanctuary. No one would ever come again!" },
    { time: 64, en: "Oh yeah, go for it!" },
    { time: 65.8, en: "Hey, I'd ever come again! I love your Dracula voice. It's over the top." },
    { time: 71.1, en: "And maybe if she saw you, she would know that I lied. No!" },
    { time: 76.3, en: "Who's Mavis? Is this her room? I'm good with a roommate. I had six brothers growing up, so I could totally share." },
    { time: 81.3, en: "I can't kill him. It would set monsters back hundreds of years." },
    { time: 84.6, en: "One time in Hamburg, I roomed with this dude who I caught stealing my shampoo. I said, whoa man!" },
    { time: 88.7, en: "And he threw a flower pot at me, but he was cool. What are you babbling about?" },
    { time: 92.8, en: "What? Whoa! Check out these awesome costumes. Costumes." },
    { time: 98.4, en: "Uh, what's this? Uh, sorry, man. I can't be without my backpack. You know, everything I own's in there." },
    { time: 103.2, en: "It'll be right here. Okay, I just... I love my backpack." },
  ],
  'ht-part-13': [
    { time: 0.3, en: "Oh, hey!" },
    { time: 0.9, en: "What are you doing?" },
    { time: 1.6, en: "What are you doing?" },
    { time: 3, en: "What are you doing in here?" },
    { time: 3.4, en: "Oh, oh, oh!" },
    { time: 4.8, en: "Oh, oh, oh!" },
    { time: 6.9, en: "Oh, oh, oh!" },
    { time: 7.7, en: "Oh, oh!" },
    { time: 8, en: "Oh, oh!" },
    { time: 11.9, en: "Check it out, I'm a franking homie." },
    { time: 14.2, en: "Yes, hello." },
    { time: 15.3, en: "Look at me!" },
    { time: 16.2, en: "This is totally normal, not the problem here." },
    { time: 18.7, en: "This is just a monster." },
    { time: 19.4, en: "It would be easy." },
    { time: 20.2, en: "Everybody stepped it up tonight." },
    { time: 22.5, en: "Wait, why are we going in front door?" },
    { time: 24, en: "Are we leaving?" },
    { time: 25.8, en: "Who's yours?" },
    { time: 27.8, en: "Hey, Sniffy." },
    { time: 28.8, en: "What's going on?" },
    { time: 29.6, en: "Not right now, Quasimodo." },
    { time: 31.2, en: "What?" },
    { time: 35.8, en: "No, don't be absurd." },
    { time: 37.4, en: "It's not a human, but mess your Dracula." },
    { time: 40.2, en: "How ridiculous." },
    { time: 41.7, en: "It's me!" },
    { time: 44.5, en: "Doesn't it, yeah?" },
    { time: 45.8, en: "The devil lizard finger." },
    { time: 47.4, en: "The devil lizard fingers?" },
    { time: 48.7, en: "I ask for spoons and blankets." },
    { time: 50.4, en: "Swiggly fool!" },
    { time: 51.2, en: "I told you!" },
    { time: 51.7, en: "He doesn't like the lizard fingers." },
    { time: 53.4, en: "But you, sir." },
    { time: 54, en: "Get back into the air!" },
    { time: 55.2, en: "You're young!" },
    { time: 56, en: "Yeah!" },
    { time: 56.6, en: "Check that costume out." },
    { time: 58.1, en: "Wow, seriously, I just have to ask you." },
    { time: 61.1, en: "How are you pulling this off?" },
    { time: 62.9, en: "I mean..." },
    { time: 63.5, en: "It looks so real." },
    { time: 64.5, en: "Like, I could just put my hand right through." },
    { time: 67.2, en: "What do you think you're doing?" },
    { time: 70.7, en: "She's..." },
    { time: 71.1, en: "She's real." },
    { time: 72.4, en: "You're real." },
    { time: 73.2, en: "Yeah, and I'll give you a real beat." },
    { time: 75.1, en: "Keep your hands out of my wife!" },
    { time: 82.3, en: "No!" },
  ],
  'ht-part-14': [
    { time: 16.1, en: "I just didn't know where you were. We thought you were still out." },
    { time: 19, en: "Oh no. I don't know why I ever wanted to leave." },
    { time: 22.1, en: "The humans are so boring." },
    { time: 37.6, en: "Mavis, honey, are you alright?" },
    { time: 39.7, en: "Yeah, I think so. That was weird." },
    { time: 42.5, en: "Oh, my head hurts." },
    { time: 44.3, en: "Um, who is that?" },
    { time: 46, en: "Who is what? Oh, oh, that! That is nobody." },
    { time: 50.6, en: "Seriously, Dad?" },
    { time: 51.4, en: "Dad?" },
    { time: 52.2, en: "Yeah, I know. Dracula's daughter. Everyone freaks out at first." },
    { time: 56.3, en: "Dracula?" },
    { time: 57.3, en: "Okay, we gotta go." },
    { time: 58.5, en: "Please don't kill me. I'm so young. I'm so in places I wanna see." },
    { time: 66.7, en: "I've got tickets to six-day Matthews being captured." },
    { time: 69.4, en: "I'm getting out of here." },
    { time: 74, en: "Shada, Paredi. It's impossible for me to think with all your noise." },
    { time: 78.6, en: "Saarigland, go back to sleep." },
    { time: 82.1, en: "Wait, aren't you gonna suck my blood?" },
    { time: 84.8, en: "Classic human paranoia. Human blood is so fatty and you never know where it's been." },
    { time: 90.8, en: "So, Dracula doesn't drink blood?" },
    { time: 93.6, en: "No, I use a blood substitute. Either near blood or blood beaters." },
    { time: 98.8, en: "You can't tell the difference." },
    { time: 100.5, en: "So, wow, you're like the real Count Dracula. Like, I am Dracula." },
    { time: 105.1, en: "Blah, blah, blah." },
  ],
  'ht-part-15': [
    { time: 0, en: "Ask what exactly is this place? What is this place?" },
    { time: 8.7, en: "It's a place I build it for all those monsters out there lurking in the shadows" },
    { time: 14.8, en: "hiding from the persecution of humankind a place for them and their families to come to and be themselves a" },
    { time: 22.9, en: "place void of torches pitch for sangry mobs a place of peace" },
    { time: 28.8, en: "relaxation and tranquility" },
    { time: 31.9, en: "Cool, so it's like a hotel for monsters" },
    { time: 35.2, en: "Yes, exactly a hotel for monsters way to sum it up" },
    { time: 40.2, en: "Okay hop on my back. We're leaving" },
    { time: 42.3, en: "Oh, man, you're about now. I always wanted to fly. What's it like?" },
    { time: 47.5, en: "This is insane wait wait. I want to stay to bring this nine sign my costume" },
    { time: 51.9, en: "Can I meet the invisible man? Hey if I stuck my hand in the invisible man's mouth would it disappear?" },
    { time: 56.8, en: "Hi" },
    { time: 57, en: "Maybe what what are you doing my sweet little blood orange?" },
    { time: 63.2, en: "Yeah, he was flying me out the window" },
    { time: 70.2, en: "Play along if you ever want to see your precious backpack" },
    { time: 77.1, en: "Whoa" },
    { time: 77.7, en: "So wait, you didn't have any clothes on when you were a bat or were they bat sized who exactly is that?" },
    { time: 84.3, en: "Honey bat you see it's your birthday and you know" },
    { time: 90.2, en: "I want you to have the bestest specialist party of your life. So well" },
    { time: 95.2, en: "I need it some help you need it help well look I am very good" },
    { time: 100.8, en: "But I thought it would be even more best is specialist if someone closer to" },
  ],
  'ht-part-16': [
    { time: 0, en: "You needed help." },
    { time: 1.4, en: "Well, look, I am very good, but I thought it would be even more best," },
    { time: 6, en: "as specialist, if someone closer to your age helped plan the part." },
    { time: 10, en: "You're my age?" },
    { time: 11, en: "Sure." },
    { time: 11.8, en: "Well, how old are you?" },
    { time: 14.5, en: "118?" },
    { time: 16.4, en: "Yeah, I'm 121." },
    { time: 19.2, en: "Really?" },
    { time: 20.2, en: "Mm-hmm." },
    { time: 21, en: "You see, everything is very, very normal." },
    { time: 25.1, en: "I'm throwing a party and he's helping." },
    { time: 27.6, en: "Sir, taste of emergency!" },
    { time: 29.2, en: "Not now." },
    { time: 30.4, en: "Can't you see we're in the middle of something very normal here?" },
    { time: 33.7, en: "Wait, what's going on here?" },
    { time: 35.6, en: "There's an emergency in your precious hotel and you're not running to fix it?" },
    { time: 39.9, en: "Why?" },
    { time: 40.7, en: "Is it because of him?" },
    { time: 41.4, en: "Whoa, look at my face!" },
    { time: 43.5, en: "Grrrr!" },
    { time: 44.4, en: "No, precious bones." },
    { time: 45.7, en: "It's not because of him." },
    { time: 47.2, en: "Good." },
    { time: 47.9, en: "Then go check on the emergency and I'll keep him company." },
    { time: 50.4, en: "No!" },
    { time: 51.3, en: "Anything but that!" },
    { time: 52.5, en: "What?" },
    { time: 53.1, en: "I mean, because he needs time to plan." },
    { time: 55.7, en: "And if you're keeping him company, then he's not planning." },
    { time: 59.1, en: "He's a company keeping." },
    { time: 60.8, en: "And then the plan, it doesn't get planned." },
    { time: 63.3, en: "Mm-hmm." },
    { time: 64.1, en: "Good one." },
    { time: 64.9, en: "Shut up!" },
    { time: 65.9, en: "Okay, so maybe if you're not planning later, we can hang out." },
    { time: 69.9, en: "Sounds good." },
    { time: 70.8, en: "Yes!" },
    { time: 71.7, en: "You hear that?" },
    { time: 72.6, en: "It sounds good." },
    { time: 74.3, en: "So you will hang out." },
    { time: 75.7, en: "See you later, my honey." },
    { time: 77.4, en: "Lovely." },
    { time: 78.9, en: "Okay, you're not hanging out." },
    { time: 81, en: "Because you are leaving." },
    { time: 83, en: "Put the opposite, you said." },
    { time: 88.2, en: "But sir, the emergency." },
    { time: 90.4, en: "Follow me." },
    { time: 96.4, en: "Boy, that kid smelled." },
    { time: 102.8, en: "Where are we going?" },
    { time: 104.2, en: "Just getting rid of you." },
  ],
  'ht-part-17': [
    { time: 0, en: "So she does not see us." },
    { time: 2.4, en: "So can I ask you a question? Is that real about the garlic thing?" },
    { time: 6.5, en: "Yes, I cannot have my throat swells." },
    { time: 9.7, en: "Huh?" },
    { time: 10.6, en: "Wouldn't stick to the heart?" },
    { time: 11.9, en: "Yeah, well who wouldn't that kill?" },
    { time: 23, en: "Ah, here we go." },
    { time: 24.3, en: "Oh, I'm sorry I'm a little lost." },
    { time: 31, en: "Yes, I know it's your honeymoon. I apologize. Go back to doing what you were doing." },
    { time: 40.5, en: "I'm not down here much. It's meant to be an exit that humans ever invade." },
    { time: 45.7, en: "So I'm like the first human here, huh?" },
    { time: 47.6, en: "That's really cool." },
    { time: 50.6, en: "Ah boy, I think this is it." },
    { time: 57.6, en: "I'm telling me sorry, isn't it my mistake?" },
    { time: 59.8, en: "What is wrong with you people?" },
    { time: 61.9, en: "Oh man, this place is amazing." },
    { time: 66.6, en: "Okay, I could really use some silence right now." },
    { time: 75.7, en: "Alright, third time." },
    { time: 86.6, en: "Yes, Frankie." },
    { time: 88.3, en: "Hey buddy, what you been doing?" },
    { time: 89.5, en: "Don't move." },
    { time: 90.8, en: "Never mind that." },
    { time: 92, en: "What you been doing?" },
    { time: 93.1, en: "We want to practice our big numbers from the innocent party" },
    { time: 95.5, en: "and then these looters won't get off the fence." },
    { time: 97.6, en: "Okay, put down zombie Mozart, Bark and Beethoven this instant." },
  ],
  'ht-part-18': [
    { time: 0.4, en: "Did you get to rehearse at all zombie mates open?" },
    { time: 5.9, en: "Listen, Drak, we wanted to play something like old times. We even thought maybe you'd sing with us." },
    { time: 11.5, en: "Come on, fellas, you know that I haven't sung in public since Martha." },
    { time: 17, en: "Yeah, but we just thought that how much you know Mavis would love it. I said no!" },
    { time: 20, en: "Don't ask me again!" },
    { time: 21.8, en: "Okay, now let's hug these zombies. Let's all make up. Wow. He really scared you. I wasn't scared. I was being polite, okay?" },
    { time: 29.2, en: "Hey, what are you doing here? I thought you were planning. I uh, I never caught your name. My name's Mavis." },
    { time: 36.7, en: "Mavis, that's a pretty neat name. Yeah, my mom picked it." },
    { time: 41.3, en: "So are you gonna tell me your name? Me? Oh, my name?" },
    { time: 47.1, en: "Good question. Well, obviously I'm Frankenstein. No, you're not. Frankenstein is my uncle over there. The gentleman hugging zombie Mozart." },
    { time: 56.2, en: "Right, of course he's your uncle. Well," },
    { time: 59.2, en: "see, I'm not THE Frankenstein. I'm his cousin," },
    { time: 64.2, en: "Johnny Stein. Hey, Mavis!" },
    { time: 68.3, en: "Is that?" },
    { time: 72.9, en: "Are these monsters gonna kill me? Not as long as they think you're a monster. That's kind of racist. We'll talk later." },
    { time: 83.6, en: "Is he making fun of me? Oh, no!" },
    { time: 87.4, en: "Because he's your cousin. Johnny Stein." },
    { time: 90.5, en: "Yes, yes, yes! I don't have no cousin. No, no, you do. He's your six cousin three times removed on your right arm's side." },
    { time: 98.3, en: "You have a cousin?" },
    { time: 99.6, en: "Frank, if your arm could talk, he would tell you that the original owner of your arm had the brother. Who married a woman?" },
  ],
  'ht-part-19': [
    { time: 0, en: "I have pig strangling blood in my arm." },
    { time: 2.5, en: "That's kinda cool." },
    { time: 3.5, en: "Well, cuz." },
    { time: 4.2, en: "Great to meet ya." },
    { time: 6, en: "Aah!" },
    { time: 7.7, en: "So, I'll bring you here, John." },
    { time: 8.8, en: "Aah!" },
    { time: 9.3, en: "What was that?" },
    { time: 10, en: "Oh, sorry. I should really clear my throat before I speak." },
    { time: 13.1, en: "Anyway, what brings you here?" },
    { time: 14.5, en: "Oh, uh, party planters?" },
    { time: 17.7, en: "Yes, I have recruited Mr. Stein here to help me with Mavis' birthday party." },
    { time: 23.3, en: "Wait a minute." },
    { time: 23.9, en: "You asked someone to help you?" },
    { time: 26.1, en: "Captain Control Freak?" },
    { time: 27.6, en: "It's Count." },
    { time: 28, en: "And yes, I thought having a Mavis contemporary would be useful." },
    { time: 32.7, en: "Yeah, he totally needed a fresher perspective." },
    { time: 36.6, en: "Okay, Johnny." },
    { time: 37.6, en: "Mr. Titekothan over here was planning to have these powdered lemots play at the party." },
    { time: 41.9, en: "Aah!" },
    { time: 43.9, en: "So anyways, we thought we could liven things up a bit." },
    { time: 46.6, en: "Whoa! You all play?" },
    { time: 48.3, en: "Let's check you guys out!" },
    { time: 52.8, en: "Girl." },
    { time: 55.7, en: "I can't believe it's your big night." },
    { time: 58.7, en: "Ah!" },
    { time: 60.7, en: "Seems like only yesterday, you were eating the skills." },
    { time: 67.3, en: "But now you're eating frogs and mice," },
    { time: 70.8, en: "scoffing them down like Doritos." },
    { time: 74.8, en: "Tell me, where did the time go?" },
    { time: 79.8, en: "Whoa, whoa, whoa, hold on guys." },
    { time: 82.6, en: "That's cute, but kind of old school." },
    { time: 85, en: "Yes, thank you, Johnny." },
    { time: 86.9, en: "You gotta totally tempo things up." },
    { time: 88.4, en: "Here, let me show you." },
    { time: 90.7, en: "Werewolf Man, give me a jam!" },
  ],
  'ht-part-20': [
    { time: 12.7, en: "Awesome." },
    { time: 13.5, en: "I am so blown away right now." },
    { time: 15.5, en: "I think my cause is gonna make this the best party ever!" },
    { time: 21.9, en: "Maybe he can find a way to get me some of that!" },
    { time: 23.8, en: "It's a rule!" },
    { time: 25.3, en: "Yeah, we're not doing any of that." },
    { time: 27.9, en: "We've got to stay unscheduled, alright?" },
    { time: 29.9, en: "Alright, Dad, alright." },
    { time: 31.7, en: "Johnny, you're coming too!" },
    { time: 32.5, en: "I don't know, it's a cool track." },
    { time: 33.8, en: "I'm gonna make you a fool!" },
    { time: 45.8, en: "N27." },
    { time: 60.6, en: "G61." },
    { time: 61, en: "G61." },
    { time: 64.1, en: "Bingo! Bingo!" },
    { time: 66.4, en: "How dare you!" },
    { time: 67.5, en: "Do you know what dogs I made me?" },
    { time: 69.4, en: "I didn't do that." },
    { time: 72, en: "Circles." },
    { time: 73.6, en: "The fly." },
    { time: 78.9, en: "Film." },
    { time: 81.1, en: "The vomit." },
    { time: 82.1, en: "The vomit." },
    { time: 83, en: "No, that wasn't a clue." },
    { time: 92.8, en: "Nothing?" },
    { time: 93.8, en: "I am penis!" },
    { time: 95.1, en: "Glasses?" },
    { time: 96.1, en: "Glasses?" },
    { time: 97.2, en: "Glasses shaking!" },
    { time: 98.3, en: "Ooh!" },
    { time: 98.8, en: "Glasses shaking sideways!" },
    { time: 100.1, en: "Through the looking glass!" },
    { time: 101, en: "I think it is." },
  ],
  'ht-part-21': [
    { time: 29.5, en: "I didn't do that." },
    { time: 32.3, en: "And pull it back and up and push and twist and back and up and twist and push." },
    { time: 44, en: "No, don't copy that." },
    { time: 47.8, en: "And back and up and twist." },
    { time: 54.2, en: "Let me get a bubonic mouss no zamlut with cockroach paste and mouse jelly." },
    { time: 59.8, en: "Oh and with egg whites." },
    { time: 63.1, en: "Auntyum is your Dracula." },
    { time: 65.2, en: "May I make your own own land?" },
    { time: 67, en: "No, no, no, no, I'm not hungry." },
    { time: 69.4, en: "What? Esmeralda, Esmeralda, Esmeralda again?" },
    { time: 72.6, en: "Yummy!" },
    { time: 74.9, en: "Oh Johnny, you're a fan of the Taj Mahal." },
    { time: 78.3, en: "Come on, no monsters been to the Taj?" },
    { time: 80.7, en: "Man, I wish I could go there." },
    { time: 83, en: "You know what, I'll take 50 of them." },
    { time: 86.2, en: "Good, man, man!" },
    { time: 88.2, en: "You're a young man!" },
    { time: 90, en: "How did you deal with the mobs?" },
    { time: 91.9, en: "Yeah, it does get pretty crazy in the summer, but you know, you just got a roll." },
    { time: 96.3, en: "He just rolls." },
    { time: 97.3, en: "That's cool that he rolls." },
    { time: 98.7, en: "Yes, yes, cool." },
    { time: 99.6, en: "Look love, Japanese." },
    { time: 101.2, en: "I brought you a bagel with your favorite scream cheese." },
    { time: 104.6, en: "Holy babies, thanks." },
  ],
  'ht-part-22': [
    { time: 0, en: "Oh cool, but I'm a scream cheese intolerant." },
    { time: 4.1, en: "So, flight pass." },
    { time: 5.5, en: "Yes, of course you are." },
    { time: 6.8, en: "Janie, can we party plant off for a minute?" },
    { time: 10.4, en: "What are you doing?" },
    { time: 11.7, en: "If they find out you are a human, they'll go bad poo." },
    { time: 14.3, en: "Relax! No one suspects anything." },
    { time: 16.2, en: "The only thing that looks weird is how much whispering you're doing." },
    { time: 21, en: "Slap it up." },
    { time: 21.8, en: "You will say you are going in the pool and act excited." },
    { time: 24.5, en: "And then you will say you hurt your back and you have to leave." },
    { time: 30.3, en: "You're come good time!" },
    { time: 32.6, en: "Oh, dude, oh, my back." },
    { time: 34.8, en: "I have to be back?" },
    { time: 35.8, en: "No, no, he said, oh, my back." },
    { time: 38, en: "You're not my back!" },
    { time: 39.2, en: "Let's do it." },
    { time: 40, en: "Oh, here we go." },
    { time: 41.3, en: "Chicken flying." },
    { time: 42.7, en: "Push him off." },
    { time: 43.8, en: "Chicken flying." },
    { time: 46.8, en: "Got you, Janie." },
    { time: 47.8, en: "You're going down." },
    { time: 49.2, en: "Oh, yeah, we'll see." },
    { time: 51.2, en: "Baby, baby." },
    { time: 54.1, en: "Okay, I'm down with the fight tickets." },
    { time: 58.2, en: "Everyone stop the rough housing." },
    { time: 69.2, en: "I got it, honey." },
    { time: 70.9, en: "The Stein Boys of Breadfin is kind of thing." },
    { time: 73.8, en: "It's runny ball!" },
    { time: 87.2, en: "You can't." },
    { time: 88.1, en: "Why'd you do that?" },
    { time: 89.8, en: "I was just in the pool." },
    { time: 91.2, en: "The water's cold." },
    { time: 92.3, en: "Don't judge me." },
    { time: 95.1, en: "Janie, don't take off." },
    { time: 97.5, en: "You're me, cold." },
    { time: 99.1, en: "I'm out now." },
    { time: 100.6, en: "Oh, man." },
    { time: 101.2, en: "I'm out." },
    { time: 102.1, en: "Oh, man." },
    { time: 103.4, en: "I guess the cat wanted to go for a swim." },
    { time: 105.2, en: "Oh, man." },
  ],
  'ht-part-23': [
    { time: 40.5, en: "You messed up, baby. You messed up big time." },
    { time: 43, en: "I told you to take it down." },
    { time: 45, en: "You'll ruin my hotel if they find out." },
    { time: 46.9, en: "Maybe you're just jealous that people are finally having fun at this place." },
    { time: 50.1, en: "Oh, that was not fun." },
    { time: 52.6, en: "Everyone running, jumping, swimming with no order." },
    { time: 56, en: "That was the opposite of fun." },
    { time: 57.5, en: "Do you even know what fun is?" },
    { time: 59.4, en: "I invented fun." },
    { time: 60.6, en: "Boy, the wrong people get to be immortal." },
    { time: 63.6, en: "Look at me." },
    { time: 65.4, en: "You'll remember nothing of this in the counter." },
    { time: 70, en: "You have no memory of this place or the monsters who met." },
    { time: 75.8, en: "Now go and never return." },
    { time: 80.2, en: "Wait, never return to the hotel?" },
    { time: 82.7, en: "What?" },
    { time: 83.5, en: "You were supposed to forget the hotel." },
    { time: 85.4, en: "I just used my powers to erase your memory." },
    { time: 87.6, en: "I looked straight into your eyes." },
    { time: 89.8, en: "Oh, maybe it's the contact lenses." },
    { time: 91.9, en: "These little plasticky doodads that help me see better." },
    { time: 94.4, en: "Here, let me just try and get them out real quick." },
    { time: 96.5, en: "Oh, that is the most disgusting thing I've ever seen." },
    { time: 99.5, en: "Almost got it." },
    { time: 100.6, en: "Stop doing that." },
    { time: 101.2, en: "Please stop doing that." },
    { time: 102.7, en: "Fingers away from the animals." },
  ],
  'ht-part-24': [
    { time: 0.5, en: "Listen to me. You are never to return here." },
    { time: 5.2, en: "You are to stay away and never tell humans about this place." },
    { time: 9.4, en: "Or I will track you down and suck every ounce of blood from your body until you look like a deflated whoopie cushion." },
    { time: 18.6, en: "Be gone." },
    { time: 27.7, en: "Can't wait on leaving, man. That could have been so great!" },
    { time: 31.2, en: "Dude ruined everything! Suck my blood." },
    { time: 34.3, en: "I should have just said, I'm staying old, man!" },
    { time: 36.6, en: "Give him a boob-slee-can't!" },
    { time: 38.6, en: "Boo! Right in the foot!" },
    { time: 40.1, en: "Oh my god! Don't drag you! Please don't kill me! I'm leaving!" },
    { time: 44.1, en: "Sheh-heh." },
    { time: 44.9, en: "Huh. Follow me." },
    { time: 47.4, en: "Oh! No, no, Mavis, I can't. I have to leave." },
    { time: 50.9, en: "You sure? It'll be fun." },
    { time: 52.7, en: "Okay. He's not gonna see me, is he?" },
    { time: 80, en: "Ha ha! Wow, did you look at the view from up here?" },
    { time: 83.2, en: "You can almost see Budapest." },
    { time: 85.2, en: "Budapest? Is that near Wi-Fi?" },
    { time: 88.4, en: "Huh? Oh, you mean Hawaii." },
    { time: 90.5, en: "Yeah, that place is a knockout. I just went to a music festival there." },
    { time: 94.4, en: "A human music festival?" },
    { time: 96.3, en: "Uh, I believe so." },
    { time: 98.2, en: "So did they all bite your toes and shove garlic bread in your face?" },
    { time: 101.1, en: "No. Well, one dude took a bigger bite out of my energy bar than I expected, but I blame that on..." },
  ],
  'ht-part-25': [
    { time: 0.3, en: "It's amazing. You've been everywhere." },
    { time: 3, en: "Well, you know, it's the alternative." },
    { time: 4.9, en: "Just staying at home, never exploring, never seeing what's out there." },
    { time: 8.6, en: "I'm only gonna be, uh, 121 once, right?" },
    { time: 12.9, en: "Gotta live it." },
    { time: 14.5, en: "Yeah." },
    { time: 17.7, en: "Oh, man." },
    { time: 19.2, en: "The sunrise from here must be..." },
    { time: 22.4, en: "Ow." },
    { time: 22.8, en: "Oh, I'm sorry." },
    { time: 24.4, en: "Man, you've probably never even seen a sunrise, have you?" },
    { time: 27, en: "No, not really." },
    { time: 28.6, en: "Bye." },
    { time: 28.9, en: "Come on, I have an idea." },
    { time: 32.9, en: "Watch." },
    { time: 60.9, en: "Didn't I tell you guys we'd have fun in here?" },
    { time: 64.1, en: "Is this not the best?" },
    { time: 69.1, en: "Yeah, I'm working up a nice one." },
    { time: 71.3, en: "Once that Johnny kid gonna be done party-branding, he's a great hang." },
    { time: 74.8, en: "Yeah, he's an animal." },
    { time: 76.2, en: "And it was so nice seeing Mavis laughing and hitting it off with him." },
    { time: 79.1, en: "Who's sitting, what, off, please?" },
    { time: 82, en: "Mavis could never be with someone of his kind." },
    { time: 85.9, en: "That's all right?" },
    { time: 87.3, en: "His kind?" },
    { time: 88.1, en: "I think..." },
    { time: 89.4, en: "You see, in our kind, is not good enough for you?" },
    { time: 91.6, en: "Your lordship?" },
    { time: 92.7, en: "No, no, no, Frank, I didn't." },
    { time: 94.6, en: "I meant that she wouldn't be into someone with such red curly hair." },
    { time: 99.6, en: "What's wrong with red curly hair?" },
    { time: 102, en: "Why are you getting upset?" },
    { time: 103.4, en: "I have red curly hair." },
    { time: 105.5, en: "Well, I..." },
  ],
  'ht-part-26': [
    { time: 0, en: "I have read curly hair." },
    { time: 2.3, en: "Well, how was I supposed to know that?" },
    { time: 4.2, en: "It's the most incredible thing I've ever seen." },
    { time: 26.2, en: "Look, settle down, fellas. This is all a moot point, because Johnny... he left." },
    { time: 31.3, en: "Wait a minute, he left? Yes, he decided he didn't like Mavis or anything about..." },
    { time: 36.3, en: "Ooh!" },
    { time: 38, en: "Hi." },
    { time: 39.1, en: "Oh, I guess Johnny had second thoughts." },
    { time: 52.3, en: "I can't believe you stuck around, man. You don't get it." },
    { time: 55.9, en: "Bad things are coming your way." },
    { time: 58.3, en: "I gotta get my thoughts together." },
    { time: 61.5, en: "Okay." },
    { time: 62.8, en: "You see these tables? You can spend the entire day pulling them out and placing them. Party planner." },
    { time: 69.7, en: "Fantastic. I'm trapped here. Now I know how your daughter feels." },
    { time: 83.5, en: "Go to a corner. You're in the time out." },
    { time: 85.8, en: "Time out. I'm a grown man." },
    { time: 92.8, en: "Okay." },
    { time: 94.1, en: "Table 57, please move to position 23." },
    { time: 97.9, en: "Ooh, that is cool." },
    { time: 103, en: "Face the wall." },
    { time: 104.7, en: "17 to 4." },
  ],
  'ht-part-27': [
    { time: 0.1, en: "17 to 48 16 to 47 19 to 50" },
    { time: 6.5, en: "Awesomeness. Let me do my work." },
    { time: 8.6, en: "29 to 35 42 to 18" },
    { time: 11.7, en: "10 to 40" },
    { time: 16, en: "36 up" },
    { time: 27.3, en: "30 1 to 19" },
    { time: 35.8, en: "24 up" },
    { time: 37, en: "7 to 25 14 to 30" },
    { time: 40.3, en: "God, I'm in these days" },
    { time: 52.3, en: "I eat my just briefing" },
    { time: 53.9, en: "56 and 43 to my side" },
    { time: 67.7, en: "Prepare to cry" },
    { time: 69.3, en: "Dilly back back" },
    { time: 70.9, en: "That's how we do it" },
    { time: 74.8, en: "Have I baby?" },
    { time: 76.1, en: "Whatever" },
    { time: 80.2, en: "Yes, keep filling" },
    { time: 82, en: "You catch the human" },
    { time: 83.6, en: "And then I eat with the human" },
    { time: 85.3, en: "What?" },
    { time: 86.2, en: "Hey" },
    { time: 90.1, en: "47, 45, 70 days" },
    { time: 92.5, en: "48" },
    { time: 93, en: "Lock his back" },
    { time: 94, en: "Lock his back" },
    { time: 97.8, en: "Oh, come on now" },
  ],
  'ht-part-28': [
    { time: 1.7, en: "You're supposed to start people trying to sleep here." },
    { time: 16.2, en: "Guys, the brain's a lot." },
    { time: 33.3, en: "Oh boy, I have to say that was fun." },
    { time: 38.7, en: "Okay, the fun you were talking about earlier." },
    { time: 42.3, en: "Nailed it." },
    { time: 44.6, en: "Johnny?" },
    { time: 49.5, en: "Quasimoto." },
    { time: 56.6, en: "Oh, no." },
    { time: 58.8, en: "Babies?" },
    { time: 60, en: "Why are you still out?" },
    { time: 61.5, en: "The sun is out." },
    { time: 62.6, en: "That could kill you, my honey gods." },
    { time: 64.3, en: "I couldn't sleep." },
    { time: 65.5, en: "Do you know where Johnny went?" },
    { time: 66.2, en: "I don't know." },
    { time: 67.8, en: "Why do you want to know?" },
    { time: 69.2, en: "Oh, uh..." },
    { time: 70.2, en: "Do you like him?" },
    { time: 71.2, en: "What?" },
    { time: 72.1, en: "No, come on, daddy." },
    { time: 73.8, en: "He's so weird and awkward." },
    { time: 75.7, en: "It's like, are you an idiot or do you know you're adorable?" },
    { time: 81.8, en: "Uh..." },
    { time: 82.2, en: "Hold that." },
    { time: 83.1, en: "Do you have an occasion of Quasimoto?" },
    { time: 85.4, en: "Yes, sir." },
    { time: 86.1, en: "They're hitting through the lobby." },
    { time: 87.1, en: "It's wounds the kitchen." },
    { time: 87.8, en: "I need them stuck immediately." },
    { time: 89.2, en: "Is that clear?" },
    { time: 89.9, en: "Yes, Quat." },
    { time: 90.7, en: "We are running." },
    { time: 92.9, en: "At least." },
    { time: 103, en: "What is that meaning of this?" },
    { time: 104.3, en: "Is that because?" },
  ],
  'ht-part-29': [
    { time: 0, en: "See, now, now, Wilson, you are coming with us." },
    { time: 4.6, en: "Why did that hurt me?" },
    { time: 9.5, en: "Look, honey, there's no falling in love at your age." },
    { time: 13.4, en: "What was my age?" },
    { time: 14.7, en: "You and us as mom kissed you first," },
    { time: 16.2, en: "because you were too scared to make the first move." },
    { time: 18.3, en: "Yeah, yeah, yeah, yeah." },
    { time: 19.7, en: "Don't forget about me and mom and kissy." },
    { time: 22.1, en: "Dad, at some point, I'm going to get married." },
    { time: 24.7, en: "I can't be here forever." },
    { time: 26.1, en: "Ah, why not?" },
    { time: 27.4, en: "You're barely out of your training fangs." },
    { time: 34.6, en: "Oh!" },
    { time: 36.2, en: "Ah!" },
    { time: 37, en: "Aw, come on." },
    { time: 38, en: "Ah!" },
    { time: 55.6, en: "When you'll bump with the hump," },
    { time: 67.3, en: "you'll land on your ramp!" },
    { time: 76, en: "But why all these sudden interests?" },
    { time: 78.6, en: "Every time we used to talk about love," },
    { time: 80.5, en: "it was always, ooh, Dad, let's grouse" },
    { time: 82.9, en: "and do that!" },
    { time: 84.1, en: "I don't want to know about that." },
    { time: 85.7, en: "Ah, I don't know." },
    { time: 88.6, en: "He might into the kitchen." },
    { time: 90, en: "What?" },
    { time: 90.6, en: "What do I pay you for?" },
    { time: 91.9, en: "I'm sorry, honey." },
    { time: 92.8, en: "I have to go." },
    { time: 95.3, en: "He doesn't pay me." },
    { time: 101.4, en: "Before you kill me, can I please talk to my backpack one more time?" },
    { time: 105.5, en: "I don't..." },
  ],
  'ht-part-30': [
    { time: 0, en: "Not your home court!" },
    { time: 1.5, en: "Now you are helping him!" },
    { time: 3.2, en: "What is it with your insists, human?" },
    { time: 5.2, en: "He is not human!" },
    { time: 6.3, en: "He's a Stein!" },
    { time: 7.4, en: "That's right, little man! I'm a Stein!" },
    { time: 9.9, en: "If he is a monster, let him scare his berelda!" },
    { time: 14, en: "The mouse?" },
    { time: 15.6, en: "Boo!" },
    { time: 16.2, en: "Without a doubt." },
    { time: 18, en: "Okay, here we go." },
    { time: 21.8, en: "Arrr!" },
    { time: 22.3, en: "Wellie!" },
    { time: 57.3, en: "Hey, thanks for saving me back there. That guy's crazy!" },
    { time: 60.5, en: "Trying to eat me?" },
    { time: 61.7, en: "That's only happening to me one other time. This weird dude at a slip-knock concert." },
    { time: 65.8, en: "There's something I need to show you." },
    { time: 68.3, en: "Oh." },
    { time: 79.9, en: "Hey, are we at a funeral right now?" },
    { time: 82.3, en: "Oh, wait no. It's your bed." },
    { time: 85.4, en: "So creepy and cool." },
    { time: 87.9, en: "Wow! I know her!" },
    { time: 90.9, en: "I've seen that picture at the ruins of LuBove." },
    { time: 93.2, en: "That's my favorite castle." },
    { time: 94.9, en: "There's a whole legend around that lady." },
    { time: 96.7, en: "A legend?" },
    { time: 99.7, en: "The lady LuBove." },
    { time: 101.5, en: "The story is that a lonely count met her by chance." },
    { time: 104.4, en: "And they say..." },
  ],
  'ht-part-31': [
    { time: 0.6, en: "The story is that a lonely count met her by chance, and they say that no two souls were ever more meant for each other." },
    { time: 8.3, en: "Eventually they settled down at Castle Lubov and had a child." },
    { time: 12.2, en: "But then a horrible tragedy happened. A fire started mysteriously one night, and it killed both of them." },
    { time: 22.6, en: "When I was at the castle, I could still feel their powerful love." },
    { time: 27.5, en: "They say it's as if a soul is still trapped in the ruins themselves." },
    { time: 31.3, en: "The legend is wrong." },
    { time: 37.1, en: "It was only the wife that died, and it was no mystery who killed her." },
    { time: 55, en: "She was killed by your kind." },
    { time: 63.4, en: "Take care of this. They are the real monsters." },
    { time: 86.8, en: "I built this place for my love to protect her child." },
    { time: 91.5, en: "As a father, you do everything to keep your family safe." },
    { time: 95.8, en: "Even if you have to break their trust." },
    { time: 99.5, en: "But now, maybe this has feelings for you." },
    { time: 104.4, en: "What?" },
  ],
  'ht-part-32': [
    { time: 0, en: "What? I... I just... Awesome." },
    { time: 6.3, en: "It's alright. You are a good one." },
    { time: 9.1, en: "If the world was different, maybe it would be possible." },
    { time: 12.5, en: "Drak, this is the 21st century. People aren't the same as they were back then." },
    { time: 16.8, en: "Can you tell me for certain that if we came out in the open, everyone would accept us?" },
    { time: 22, en: "Everyone?" },
    { time: 26.1, en: "No. You're right." },
    { time: 28.9, en: "I'll go for good this time." },
    { time: 31.1, en: "You can just say I had some emergency here." },
    { time: 33.8, en: "The Gramlin lady ate me or something." },
    { time: 36.3, en: "No, no, no, no, no. I don't want to ruin her birthday party." },
    { time: 40.5, en: "You can sneak out after it's all done." },
    { time: 43.8, en: "I'm sorry." },
    { time: 45.9, en: "The last thing I wanted was to hurt her." },
    { time: 49.5, en: "Or you." },
    { time: 51.8, en: "You know, you're not the smoothest Frankenstein, but you'd make a great vampire." },
    { time: 58.6, en: "For real?" },
    { time: 59.7, en: "Because I think I kind of got your hypnoe eyes down." },
    { time: 61.5, en: "Oh boy, here we go. Let me see it." },
    { time: 64.4, en: "Beware! For you are in my power." },
    { time: 67.9, en: "I got a man you to be the werewolf man." },
    { time: 71, en: "Oh, yay!" },
    { time: 72.5, en: "I have too many kids." },
    { time: 75.7, en: "Someone scratch me. I have fleas." },
    { time: 79.5, en: "Because he's a wovey get the..." },
    { time: 81.4, en: "Get the..." },
    { time: 82.3, en: "Get the..." },
    { time: 83.1, en: "Get the..." },
    { time: 83.4, en: "Get the..." },
    { time: 83.4, en: "Get the..." },
  ],
  'ht-part-33': [
    { time: 1, en: "I didn't order a wake-up call" },
    { time: 5.2, en: "Mmm." },
    { time: 7.8, en: "That's a smooth button!" },
    { time: 9.4, en: "There would be no snoozing!" },
    { time: 10.5, en: "The party's today!" },
    { time: 23.4, en: "Hahahaha!" },
    { time: 33.1, en: "Yeah! Perfecto!" },
  ],
  'ht-part-34': [
    { time: 11.9, en: "You can find me!" },
    { time: 13.1, en: "You made this." },
    { time: 47.7, en: "I'm crazily scared right now." },
    { time: 49.8, en: "Maybe that's a good thing." },
    { time: 66.7, en: "And with you!" },
    { time: 67.8, en: "Dad, if it's just a kiss..." },
    { time: 69.5, en: "No, you're not allowed to kiss!" },
    { time: 71.2, en: "Dad, I'm allowed to do things." },
    { time: 73, en: "I'm not 83 anymore." },
    { time: 74.5, en: "I'm allowed to like people or go see the world again." },
    { time: 77.1, en: "What? You saw it! You said you didn't like it!" },
    { time: 79.7, en: "Maybe I want to give the village another chance." },
    { time: 81.7, en: "I just need to learn, you know, just how to roll with it, like Johnny does." },
    { time: 84.7, en: "No, no! You can't go to the village again!" },
    { time: 87.6, en: "Maybe you can make them see that we could be friends." },
    { time: 89.2, en: "No, that isn't possible." },
    { time: 90.7, en: "You can't be sure. It's all in how you present yourself." },
    { time: 92.8, en: "No, that won't make a difference." },
    { time: 94.5, en: "How do you know?" },
    { time: 95, en: "Because it just won't." },
    { time: 95.8, en: "Why won't it?" },
    { time: 96.8, en: "Because that village doesn't really exist!" },
    { time: 103.6, en: "What do you mean, doesn't exist?" },
  ],
  'ht-part-35': [
    { time: 0, en: "What did you do? I did what I had to do." },
    { time: 4.5, en: "What was it? What exactly did you have to do? Tell me." },
    { time: 11.1, en: "I built the town. The staff put it all together. The zombies dressed up as the townspeople." },
    { time: 23.9, en: "Please, if you really went out there and something happened to you, I just couldn't live with myself." },
    { time: 30.2, en: "But you can live with this, lying to me, tricking me, keeping me here forever when you knew my dream was to go." },
    { time: 42.7, en: "Oof! English please, your voice is really annoying." },
    { time: 51.3, en: "Wait, I speak frozen. He says Dracula has brought a human into the hotel." },
    { time: 56.4, en: "A human? Stay close, pookey." },
    { time: 61.9, en: "He says there is the human. He has a French accent." },
    { time: 71.7, en: "Johnny's not a human. He's my right arms cousin. He's lying." },
    { time: 75.7, en: "Yeah. And why is he picking his nose?" },
    { time: 79.3, en: "He says it's a long story." },
    { time: 81.5, en: "Hey, wait, no! Get off me!" },
    { time: 85.6, en: "And hurt!" },
    { time: 87.7, en: "He says behold the human." },
    { time: 90.9, en: "I don't believe him." },
    { time: 100.7, en: "Is it true? Are you a human?" },
  ],
  'ht-part-36': [
    { time: 0.6, en: "Yes, I'm so sorry. I don't care. I still want to be with you" },
    { time: 19.7, en: "Well tough" },
    { time: 21.5, en: "Because I don't want to be with you because you're a monster and I hate monsters" },
    { time: 29.2, en: "Goodbye" },
    { time: 60.7, en: "I'm just glad my eyes are stitched shut" },
    { time: 66.2, en: "May be sunny are you in there" },
    { time: 75.4, en: "May be" },
  ],
  'ht-part-37': [
    { time: 0, en: "Yes, yes, of course, darling, anything." },
    { time: 3.4, en: "Will you erase my mind?" },
    { time: 7.5, en: "No, no, no, no, I won't do that." },
    { time: 10.6, en: "There's too much I want you to remember." },
    { time: 13.6, en: "You were right, Dad. The humans hate us." },
    { time: 17, en: "Sweetheart, there are so many eligible monsters out there, you're so young to..." },
    { time: 23.8, en: "What is it? What are you reading?" },
    { time: 33.5, en: "Two lonely bats crashed in the night." },
    { time: 37.8, en: "They felt a zing love at first sight." },
    { time: 42.4, en: "They knew right then they would be husband and wife." },
    { time: 47.7, en: "For a zing only happens once in your life." },
    { time: 52.9, en: "Your zing will come, my love." },
    { time: 55.1, en: "Cherish it. Love, money." },
    { time: 62.5, en: "I thought we zing to Dad." },
    { time: 64.1, en: "Oh, you and Johnny?" },
    { time: 66.4, en: "I guess it was only me." },
    { time: 68.9, en: "But you should be happy, Dad." },
    { time: 70.7, en: "There's no reason for me to leave. I have no more dreams." },
    { time: 75.8, en: "I'm just like you now." },
    { time: 104.4, en: "Martha, what have you..." },
  ],
  'ht-part-38': [
    { time: 7.2, en: "Hey, what's my cake?" },
    { time: 8.5, en: "I got a lot of money." },
    { time: 11, en: "This is Mini Bartron." },
    { time: 12.7, en: "It's funny, they keep feeling the Mini Bart got out the window." },
    { time: 15.1, en: "And that's our fault?" },
    { time: 17.1, en: "Excuse me, I'm in the park." },
    { time: 18.9, en: "Yes, excuse me. I've got a couple of people to express, man." },
    { time: 24.4, en: "Friends, please stop." },
    { time: 26.6, en: "It's too late, rat bats." },
    { time: 28.4, en: "Please, I'm begging you. I need you to help me find Johnny." },
    { time: 32.8, en: "The human? He could have killed us. He touched my guitar." },
    { time: 36.6, en: "He put his hand in my mouth to see if it would disappear." },
    { time: 41.3, en: "He let me eat his scooter." },
    { time: 44.7, en: "I know I lied. I was wrong, but you have to believe this Johnny wasn't a bad guy." },
    { time: 56.5, en: "The truth is, I don't even know if humans are bad anymore." },
    { time: 63.8, en: "Frank, come on, buddy. You understand?" },
    { time: 67.5, en: "He's not talking to you. First you tell us humans are bad." },
    { time: 71, en: "Now they're good. What else?" },
    { time: 72.3, en: "Up is down, cold is hot, gremlins don't smell." },
    { time: 75.1, en: "Hey! I really like Johnny, cousin or no." },
    { time: 80.8, en: "He told fun stories. I think they zined." },
    { time: 84.7, en: "They zined? But I got in the way." },
    { time: 88.4, en: "You only zing once in your life." },
    { time: 92.5, en: "All right, now you're short circuiting." },
    { time: 94.4, en: "I don't care." },
    { time: 95.6, en: "What are we doing? Let's get Johnny. Come on!" },
    { time: 98.6, en: "Yeah, let's go!" },
  ],
  'ht-part-39': [
    { time: 23.1, en: "before Johnny's gone forever." },
    { time: 25.3, en: "But what about the sun?" },
    { time: 27.1, en: "I don't know. I'll just have to roll." },
    { time: 30.5, en: "He just rolls. Roll-a-dilly." },
    { time: 33, en: "So we follow with boot prints." },
    { time: 35.1, en: "When they run out, that's where you come in Wayne." },
    { time: 37.3, en: "Me? Me?" },
    { time: 41.1, en: "Yes, I knew something would fall out of that backpack." },
    { time: 46.3, en: "Yowch! That stinks!" },
    { time: 48.3, en: "Work your magic." },
    { time: 49.7, en: "Wait, you want me to trap the smell?" },
    { time: 51.8, en: "No, no, no. My snipping tracking days are way behind me." },
    { time: 54.1, en: "Do you know how many diapers I've changed?" },
    { time: 56.2, en: "How many number twos have destroyed this thing?" },
    { time: 59.6, en: "But..." },
    { time: 74.5, en: "Whoa!" },
    { time: 76.7, en: "Sit. Smell. I said smell." },
    { time: 83.7, en: "Not me, the shirt! The shirt!" },
    { time: 86.8, en: "Do any of your kids still respect you?" },
    { time: 89.3, en: "Give me a second." },
    { time: 91, en: "Oh, yeah." },
    { time: 92.5, en: "Winnie! Front-dense center!" },
    { time: 104.4, en: "He got into a..." },
  ],
  'ht-part-40': [
    { time: 0, en: "He got into a cart at 86 feet." },
    { time: 2.8, en: "I need a little transmission work, but otherwise okay." },
    { time: 7.2, en: "It drove through town to the airport." },
    { time: 10.5, en: "Flight 497, 8 AM departure." },
    { time: 14.5, en: "That's in 15 minutes." },
    { time: 16.4, en: "See, 23 AM." },
    { time: 18.5, en: "He ordered a vegetarian meal." },
    { time: 20.5, en: "Okay, thank you, QT." },
    { time: 22.7, en: "Now all of you, go back to your mother." },
    { time: 33.5, en: "Chief! High five!" },
    { time: 45, en: "Don't let me hang it." },
    { time: 47.3, en: "Oh, lots of cheese!" },
    { time: 49.1, en: "I got this one." },
    { time: 53.9, en: "Now there's no sheep in the road. Let's go." },
    { time: 60.2, en: "That was pretty sick, man." },
    { time: 62, en: "You eat lamb chops, it's the same thing." },
    { time: 64.6, en: "We're gonna have time for this. Come on, let's move it." },
    { time: 70.4, en: "Look, a human." },
    { time: 74.4, en: "Welcome to Transylvania!" },
    { time: 78.3, en: "That was trippy." },
    { time: 84.5, en: "Monster Festival?" },
    { time: 86.1, en: "What's a monster festival? Did they know we were coming?" },
  ],
  'ht-part-41': [
    { time: 0, en: "BLUE!" },
    { time: 0.9, en: "Well, the best way to the airport?" },
    { time: 20.8, en: "Yes, fellow Dracula." },
    { time: 22.3, en: "There's only one way, blah, blah, blah." },
    { time: 25.1, en: "But it's all blocked." },
    { time: 26.7, en: "We'll never make it in time." },
    { time: 28.2, en: "You should have left an hour earlier, blah, blah, blah." },
    { time: 31.1, en: "I do not say blah, blah, blah." },
    { time: 34.1, en: "Alright, let's just run through it on foot." },
    { time: 43.9, en: "This will protect you." },
    { time: 45.5, en: "Blah, blah, blah." },
    { time: 46.9, en: "Imagine if that guy knew he was talking to the real Dracula." },
    { time: 49.8, en: "He'd run for the hills." },
    { time: 51.8, en: "Hold it now." },
    { time: 52.8, en: "Hold it now." },
    { time: 53.4, en: "That sounds flat on!" },
    { time: 55.5, en: "But the only way they know the real us is if we show the real us." },
    { time: 59.6, en: "It's good work." },
    { time: 61, en: "You mean I'm scared?" },
    { time: 62.1, en: "We haven't scared people in centuries." },
    { time: 64, en: "I don't need to have it in me anymore." },
    { time: 66.1, en: "I got nothin'." },
    { time: 70, en: "I really got nothin'." },
    { time: 70.8, en: "Let's just move this along." },
    { time: 73.8, en: "Frankenstein!" },
    { time: 101.6, en: "We know who we love you." },
    { time: 103.7, en: "Can you stand by torch?" },
  ],
  'ht-part-42': [
    { time: 1.4, en: "Listen before anything else down. There's the real Dracula" },
    { time: 7.7, en: "Prove it" },
    { time: 9.8, en: "All right continue" },
    { time: 11.4, en: "Drax daughters in love and he's got to get to the airport and he can't get through this crowd" },
    { time: 17.1, en: "What doesn't he fly the Sun you idiot. He's a vampire. That's right. Thank you monster nerd" },
    { time: 23.5, en: "So people if you really are our friends clear a path for the man" },
    { time: 29.3, en: "Okay, all Dracula's line up" },
    { time: 36.4, en: "Everyone else" },
    { time: 39, en: "It's all for you, buddy" },
    { time: 72, en: "There's no choice" },
  ],
  'ht-part-43': [
    { time: 53.3, en: "This is how we're represented. Unbelievable." },
    { time: 56.6, en: "John, I've been. John, I've..." },
    { time: 62.1, en: "Wait, it's talking. Dracula, is that you?" },
    { time: 65.9, en: "Huh? Dracula?" },
    { time: 70.8, en: "What? My hand's in a tanshew?" },
    { time: 73.8, en: "What? Japan's eating lamb stew?" },
    { time: 78, en: "Hey, do you know you're smoking? Sorry, excuse me. Whoa! Excuse me." },
    { time: 104.2, en: "What the heck? I don't..." },
  ],
  'ht-part-44': [
    { time: 0, en: "What the heck? How'd a bad get up his eye?" },
    { time: 3.3, en: "Folks, I'm gonna turn on the seatbelt sign, just a precaution while we..." },
    { time: 9.2, en: "While we hear a special announcement for my dear friend John... Dracula?" },
    { time: 16.1, en: "My dear boy, I have made a terrible mistake. I was trying to keep my baby to my self, because I knew I would always protect her." },
    { time: 26.8, en: "But I realize now children need to discover things for themselves." },
    { time: 32.8, en: "They'll stumble and fall, laugh and cry. But such is life." },
    { time: 38.5, en: "The truth is you and Mavis are meant to be, you sing." },
    { time: 43, en: "If she must give her trust to someone else, I'm thankful that it is you, Jonathan. I hope you can hear me and forgive me." },
    { time: 67.8, en: "Okay, folks, we're going to make a quick turnaround to refuel, and then we'll be back on our way." },
    { time: 75.2, en: "With your whining, I'm burning up out here." },
    { time: 92.4, en: "Dad?" },
    { time: 93.6, en: "Oh, I'm fine. I'm just a little sunburned. Honey. I always thought..." },
  ],
  'ht-part-45': [
    { time: 0, en: "Is seeing you unhappy." },
    { time: 2.8, en: "Maybe I want you to live your life." },
    { time: 7.8, en: "I don't know how I'm supposed to do that." },
    { time: 11.5, en: "You know, Mommy already gave you her birthday present." },
    { time: 15, en: "Can I now give you mine?" },
    { time: 19.4, en: "What do I need this for?" },
    { time: 20.9, en: "Oh, it comes with an accessory." },
    { time: 25.2, en: "You?" },
    { time: 26.5, en: "You?" },
    { time: 28.3, en: "Why are you back?" },
    { time: 33.9, en: "Because you're my zing, Mayvis." },
    { time: 35.7, en: "I'm your zing." },
    { time: 37.8, en: "But you told me you hate monsters." },
    { time: 40.4, en: "Yeah, well, I was afraid your dad was going to suck all the blood out of my body if I didn't say that." },
    { time: 46.4, en: "I wouldn't have that." },
    { time: 48.1, en: "Hey, no, he's right. I would have done that." },
    { time: 50, en: "Dad?" },
    { time: 50.6, en: "I was wrong, Devil Charles." },
    { time: 53.1, en: "Me and a dad?" },
    { time: 60, en: "Go make your own paradise." },
    { time: 66.1, en: "Can we try that kiss over again?" },
    { time: 68.6, en: "I think we can." },
    { time: 75.9, en: "Sorry, I just got to get used to that." },
    { time: 79.2, en: "Go, go, do your thing." },
    { time: 100.1, en: "You know, she was just a fling." },
    { time: 101.3, en: "And then I met a girl and felt a different thing." },
    { time: 103.1, en: "It's like a hit in the ring like you're pulled by a string." },
    { time: 105.1, en: "Can't breathe." },
  ],
  'ht-part-46': [
    { time: 0.2, en: "I'm looking on a chicken way" },
    { time: 1.1, en: "It was a thing called a saying" },
    { time: 2.2, en: "And I wanted to sing" },
    { time: 3.1, en: "And listen to the balance of the man who's singing" },
    { time: 5.1, en: "Baby, look in your eyes and it's only spring" },
    { time: 7, en: "Like what's hollow, it just happened in the Lion King" },
    { time: 30.7, en: "Throw down?" },
    { time: 31.6, en: "No, no, I just came closer to hear you, then" },
    { time: 34.5, en: "Aw, come on, just give it a try!" },
    { time: 36.9, en: "Alright, maybe just a little" },
    { time: 38.3, en: "So listen, all you singers from here to Beijing, you better catch the b-" },
  ],
  'ht-part-47': [
    { time: 53.9, en: "Salved" },
  ],
  'ht-part-48': [
    { time: 0, en: "I'm gonna give up that nest, oh, something I wanna be the first dude to love a Martian" },
    { time: 5.6, en: "Mmm, she'll ever make of the splash that I'm dropping" },
    { time: 9.4, en: "I kill a game, kill a show in the coffin" },
    { time: 11.5, en: "When I start it ain't no stopping" },
    { time: 14.2, en: "I didn't do that" },
  ],
}
