import type { UnitQuiz } from '../types/content'

/**
 * Dedicated end-of-unit assessment quizzes.
 * Curated from the audited, book-derived lesson content in src/content/units.
 * Every question has a single defensible answer.
 * Categories and skills only use what the lesson material actually supports.
 */

export const UNIT_QUIZZES: UnitQuiz[] = [
  {
    id: 'quiz-lead-in',
    unitId: 'lead-in',
    title: 'Lead-in Quiz',
    description: 'Personal information, common objects, countries and numbers.',
    skills: ['be and possessive adjectives', 'question words', 'everyday objects', 'countries and nationalities', 'numbers and days'],
    questions: [
      {
        id: 'li-q1',
        unitId: 'lead-in',
        lessonId: 'li',
        category: 'grammar',
        difficulty: 'easy',
        skill: "be and possessive adjectives",
        page: 7,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018___ name is Greta.\u2019 (Greta is a woman.)",
          options: [
            { label: 'Her', correct: true },
            { label: 'His', correct: false },
            { label: 'Your', correct: false },
          ],
        },
        explanation: "Her is the possessive adjective for a woman or girl.",
      },
      {
        id: 'li-q2',
        unitId: 'lead-in',
        lessonId: 'li',
        category: 'grammar',
        difficulty: 'easy',
        skill: "be and possessive adjectives",
        page: 7,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018They\u2019re married. ___ live in Cairo.\u2019",
          options: [
            { label: 'They\u2019re', correct: true },
            { label: 'Their', correct: false },
            { label: 'There', correct: false },
          ],
        },
        explanation: "They\u2019re = they are. Use it before a verb like \u2018live\u2019.",
      },
      {
        id: 'li-q3',
        unitId: 'lead-in',
        lessonId: 'li',
        category: 'grammar',
        difficulty: 'easy',
        skill: "be and possessive adjectives",
        page: 7,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018That\u2019s my phone. ___ expensive.\u2019",
          options: [
            { label: 'It\u2019s', correct: true },
            { label: 'It', correct: false },
            { label: 'Is', correct: false },
          ],
        },
        explanation: "It\u2019s = it is. The sentence needs the verb is.",
      },
      {
        id: 'li-q4',
        unitId: 'lead-in',
        lessonId: 'li',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'question words',
        page: 7,
        question: {
          kind: 'mcq',
          prompt: "Complete the question: \u2018___ are you from? \u2014 I\u2019m from Brazil.\u2019",
          options: [
            { label: 'Where', correct: true },
            { label: 'What', correct: false },
            { label: 'How', correct: false },
          ],
        },
        explanation: "Where asks about a place \u2014 here, the country someone is from.",
      },
      {
        id: 'li-q5',
        unitId: 'lead-in',
        lessonId: 'li',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'everyday objects',
        page: 7,
        question: {
          kind: 'mcq',
          prompt: 'Which thing do you use for cutting paper?',
          options: [
            { label: 'scissors', correct: true },
            { label: 'tissues', correct: false },
            { label: 'stamps', correct: false },
          ],
        },
        explanation: "Scissors are the cutting tool from the everyday objects vocabulary.",
      },
      {
        id: 'li-q6',
        unitId: 'lead-in',
        lessonId: 'li',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'everyday objects',
        page: 7,
        question: {
          kind: 'mcq',
          prompt: 'You stick one of these on a letter before you post it:',
          options: [
            { label: 'a stamp', correct: true },
            { label: 'a battery', correct: false },
            { label: 'a tissue', correct: false },
          ],
        },
        explanation: "A stamp is the small sticker you put on a letter.",
      },
      {
        id: 'li-q7',
        unitId: 'lead-in',
        lessonId: 'li',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'countries and nationalities',
        page: 7,
        question: {
          kind: 'mcq',
          prompt: 'Someone from Turkey is ___?',
          options: [
            { label: 'Turkish', correct: true },
            { label: 'Brazilian', correct: false },
            { label: 'Spanish', correct: false },
          ],
        },
        explanation: "Turkey \u2192 Turkish, following the same pattern as Brazil \u2192 Brazilian.",
      },
      {
        id: 'li-q8',
        unitId: 'lead-in',
        lessonId: 'li',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'days of the week',
        page: 7,
        question: {
          kind: 'mcq',
          prompt: 'Which day comes between Friday and Sunday?',
          options: [
            { label: 'Saturday', correct: true },
            { label: 'Thursday', correct: false },
            { label: 'Monday', correct: false },
          ],
        },
        explanation: "The week runs Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.",
      },
      {
        id: 'li-q9',
        unitId: 'lead-in',
        lessonId: 'li',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'numbers',
        page: 7,
        question: {
          kind: 'mcq',
          prompt: 'Complete the sequence: eleven, twelve, thirteen, fourteen, ___',
          options: [
            { label: 'fifteen', correct: true },
            { label: 'sixteen', correct: false },
            { label: 'fifty', correct: false },
          ],
        },
        explanation: "After fourteen comes fifteen.",
      },
      {
        id: 'li-q10',
        unitId: 'lead-in',
        lessonId: 'li',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'classroom language',
        page: 7,
        question: {
          kind: 'mcq',
          prompt: "In class you ask: \u2018How do you ___ that word?\u2019",
          options: [
            { label: 'spell', correct: true },
            { label: 'spells', correct: false },
            { label: 'learning', correct: false },
          ],
        },
        explanation: "After \u2018How do you\u2026?\u2019 we use the base form: spell.",
      },
    ],
  },

  {
    id: 'quiz-unit-1',
    unitId: 'unit-1',
    title: 'Unit 1 Quiz',
    description: 'Present simple, suggesting things, possessive \u2019s, and talking about people.',
    skills: ['present simple', "possessive 's and s'", "Let's / How about...?", 'jobs and feelings', 'family words'],
    questions: [
      {
        id: '1-q1',
        unitId: 'unit-1',
        lessonId: '1a',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'present simple',
        page: 10,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018Do you ___ near here?\u2019",
          options: [
            { label: 'live', correct: true },
            { label: 'lives', correct: false },
            { label: 'living', correct: false },
          ],
        },
        explanation: "After do we use the base form of the verb.",
      },
      {
        id: '1-q2',
        unitId: 'unit-1',
        lessonId: '1b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'present simple',
        page: 10,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018Sam ___ in a small village.\u2019",
          options: [
            { label: 'lives', correct: true },
            { label: 'live', correct: false },
            { label: 'is live', correct: false },
          ],
        },
        explanation: "With he/she/it the present simple verb takes -s.",
      },
      {
        id: '1-q3',
        unitId: 'unit-1',
        lessonId: '1b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'present simple',
        page: 10,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018He ___ a full-time job.\u2019",
          options: [
            { label: 'doesn\u2019t have', correct: true },
            { label: 'don\u2019t have', correct: false },
            { label: 'hasn\u2019t', correct: false },
          ],
        },
        explanation: "In the present simple, the negative with he is doesn\u2019t + base form: doesn\u2019t have.",
      },
      {
        id: '1-q4',
        unitId: 'unit-1',
        lessonId: '1b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'present simple',
        page: 10,
        question: {
          kind: 'mcq',
          prompt: "Complete the short answer: \u2018Does she live near here? \u2014 Yes, she ___.\u2019",
          options: [
            { label: 'does', correct: true },
            { label: 'do', correct: false },
            { label: 'is', correct: false },
          ],
        },
        explanation: "Short answers to yes/no questions with do/did repeat the auxiliary: Yes, she does.",
      },
      {
        id: '1-q5',
        unitId: 'unit-1',
        lessonId: '1c',
        category: 'communication',
        difficulty: 'easy',
        skill: "Let's / making suggestions",
        page: 12,
        question: {
          kind: 'mcq',
          prompt: "Complete the suggestion: \u2018Let\u2019s ___ at seven at the cinema.\u2019",
          options: [
            { label: 'meet', correct: true },
            { label: 'to meet', correct: false },
            { label: 'meeting', correct: false },
          ],
        },
        explanation: "Let\u2019s is followed by the base form of the verb: Let\u2019s meet.",
      },
      {
        id: '1-q6',
        unitId: 'unit-1',
        lessonId: '1c',
        category: 'communication',
        difficulty: 'medium',
        skill: "How about...? / suggestions",
        page: 12,
        question: {
          kind: 'mcq',
          prompt: "You want to suggest a time. Which phrase fits? \u2018___ about Monday morning?\u2019",
          options: [
            { label: 'How', correct: true },
            { label: 'Would you', correct: false },
            { label: 'Let\u2019s', correct: false },
          ],
        },
        explanation: "How about + a day/time is a natural way to suggest something.",
      },
      {
        id: '1-q7',
        unitId: 'unit-1',
        lessonId: '1c',
        category: 'communication',
        difficulty: 'medium',
        skill: 'inviting with Would you like',
        page: 12,
        question: {
          kind: 'mcq',
          prompt: "Which is the correct invite? \u2018___ you like to come?\u2019",
          options: [
            { label: 'Would', correct: true },
            { label: 'Do', correct: false },
            { label: 'Are', correct: false },
          ],
        },
        explanation: "Would you like + to + verb is the polite way to invite someone.",
      },
      {
        id: '1-q8',
        unitId: 'unit-1',
        lessonId: '1d',
        category: 'grammar',
        difficulty: 'hard',
        skill: "possessive 's",
        page: 14,
        question: {
          kind: 'mcq',
          prompt: "Pete owns one laptop. You say: \u2018It\u2019s ___ laptop.\u2019",
          options: [
            { label: "Pete's", correct: true },
            { label: "Petes'", correct: false },
            { label: 'Petes', correct: false },
          ],
        },
        explanation: "One owner = \u2019s after the noun: Pete\u2019s.",
      },
      {
        id: '1-q9',
        unitId: 'unit-1',
        lessonId: '1d',
        category: 'grammar',
        difficulty: 'hard',
        skill: "possessive s'",
        page: 14,
        question: {
          kind: 'mcq',
          prompt: "Two parents own a house together. You say: \u2018It\u2019s my ___ house.\u2019",
          options: [
            { label: "parents'", correct: true },
            { label: "parent's", correct: false },
            { label: "parents's", correct: false },
          ],
        },
        explanation: "With plural words ending in -s, the apostrophe comes after the s: parents\u2019.",
      },
      {
        id: '1-q10',
        unitId: 'unit-1',
        lessonId: '1b',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'feelings',
        page: 11,
        question: {
          kind: 'mcq',
          prompt: 'I want to sleep \u2014 I feel ___.',
          options: [
            { label: 'tired', correct: true },
            { label: 'angry', correct: false },
            { label: 'thirsty', correct: false },
          ],
        },
        explanation: "Tired is the feeling when you need to sleep.",
      },
      {
        id: '1-q11',
        unitId: 'unit-1',
        lessonId: '1r',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'family words',
        page: 15,
        question: {
          kind: 'mcq',
          prompt: "My mother\u2019s brother is my:",
          options: [
            { label: 'uncle', correct: true },
            { label: 'grandfather', correct: false },
            { label: 'cousin', correct: false },
          ],
        },
        explanation: "Your mother or father\u2019s brother is your uncle.",
      },
      {
        id: '1-q12',
        unitId: 'unit-1',
        lessonId: '1r',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'jobs',
        page: 15,
        question: {
          kind: 'mcq',
          prompt: "My dad is 67 and he doesn\u2019t work now. He\u2019s ___.",
          options: [
            { label: 'retired', correct: true },
            { label: 'unemployed', correct: false },
            { label: 'bored', correct: false },
          ],
        },
        explanation: "Retired means you have stopped working because of age.",
      },
    ],
  },

  {
    id: 'quiz-unit-2',
    unitId: 'unit-2',
    title: 'Unit 2 Quiz',
    description: 'Countable and uncountable food, frequency adverbs, love + -ing, and restaurants.',
    skills: ['countable and uncountable nouns', 'frequency adverbs', 'love / like + -ing', 'food and drink', 'in a restaurant'],
    questions: [
      {
        id: '2-q1',
        unitId: 'unit-2',
        lessonId: '2a',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'a / an',
        page: 18,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018I eat ___ apple every day.\u2019",
          options: [
            { label: 'an', correct: true },
            { label: 'a', correct: false },
            { label: 'some', correct: false },
          ],
        },
        explanation: "Apple starts with a vowel sound, so we use an.",
      },
      {
        id: '2-q2',
        unitId: 'unit-2',
        lessonId: '2a',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'some / any',
        page: 18,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018We don\u2019t have ___ strawberries in the fridge.\u2019",
          options: [
            { label: 'any', correct: true },
            { label: 'some', correct: false },
            { label: 'a', correct: false },
          ],
        },
        explanation: "In negative sentences with plural nouns we use any, not some.",
      },
      {
        id: '2-q3',
        unitId: 'unit-2',
        lessonId: '2a',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'countable and uncountable',
        page: 18,
        question: {
          kind: 'mcq',
          prompt: 'Which food is usually uncountable?',
          options: [
            { label: 'broccoli', correct: true },
            { label: 'an onion', correct: false },
            { label: 'a cucumber', correct: false },
          ],
        },
        explanation: "Broccoli has no plural form, so it is uncountable.",
      },
      {
        id: '2-q4',
        unitId: 'unit-2',
        lessonId: '2c',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'in a restaurant',
        page: 20,
        question: {
          kind: 'mcq',
          prompt: 'You finish your meal and ask for ___.',
          options: [
            { label: 'the bill', correct: true },
            { label: 'the menu', correct: false },
            { label: 'the recipe', correct: false },
          ],
        },
        explanation: "The bill is the paper that shows what you must pay.",
      },
      {
        id: '2-q5',
        unitId: 'unit-2',
        lessonId: '2c',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'in a restaurant',
        page: 20,
        question: {
          kind: 'mcq',
          prompt: "A vegetarian starter contains ___, but no ___.",
          options: [
            { label: 'vegetables, meat', correct: true },
            { label: 'meat, vegetables', correct: false },
            { label: 'sugar, salt', correct: false },
          ],
        },
        explanation: "Vegetarian food has no meat or fish.",
      },
      {
        id: '2-q6',
        unitId: 'unit-2',
        lessonId: '2b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'frequency adverbs',
        page: 19,
        question: {
          kind: 'mcq',
          prompt: "It happens 100% of the time. The frequency word is:",
          options: [
            { label: 'always', correct: true },
            { label: 'sometimes', correct: false },
            { label: 'never', correct: false },
          ],
        },
        explanation: "Always = 100%, sometimes = about 50%, never = 0%.",
      },
      {
        id: '2-q7',
        unitId: 'unit-2',
        lessonId: '2b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'frequency adverbs',
        page: 19,
        question: {
          kind: 'mcq',
          prompt: "\u2018I hardly ever have dessert\u2019 means I have it:",
          options: [
            { label: 'almost never', correct: true },
            { label: 'every day', correct: false },
            { label: 'all the time', correct: false },
          ],
        },
        explanation: "Hardly ever is the same as almost never \u2014 about 10% of the time.",
      },
      {
        id: '2-q8',
        unitId: 'unit-2',
        lessonId: '2d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'love / like + -ing',
        page: 22,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018I love ___ with my horses.\u2019",
          options: [
            { label: 'working', correct: true },
            { label: 'to working', correct: false },
            { label: 'work', correct: false },
          ],
        },
        explanation: "After love / like / don\u2019t mind we use the -ing form.",
      },
      {
        id: '2-q9',
        unitId: 'unit-2',
        lessonId: '2d',
        category: 'grammar',
        difficulty: 'hard',
        skill: 'spelling -ing forms',
        page: 22,
        question: {
          kind: 'mcq',
          prompt: 'Write the -ing form: write \u2192 ___',
          options: [
            { label: 'writing', correct: true },
            { label: 'writting', correct: false },
            { label: 'wrote', correct: false },
          ],
        },
        explanation: "Write drops the final -e before adding -ing: writing.",
      },
      {
        id: '2-q10',
        unitId: 'unit-2',
        lessonId: '2b',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'online tasks',
        page: 19,
        question: {
          kind: 'mcq',
          prompt: "You go online to ___ your messages.",
          options: [
            { label: 'check', correct: true },
            { label: 'charge', correct: false },
            { label: 'choose', correct: false },
          ],
        },
        explanation: "Check your messages means look at them to see if there is anything new.",
      },
      {
        id: '2-q11',
        unitId: 'unit-2',
        lessonId: '2c',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'in a restaurant',
        page: 20,
        question: {
          kind: 'mcq',
          prompt: 'The person who serves your food in a restaurant is the:',
          options: [
            { label: 'waiter', correct: true },
            { label: 'customer', correct: false },
            { label: 'cook', correct: false },
          ],
        },
        explanation: "The waiter brings the food; the customer eats it; the cook prepares it.",
      },
      {
        id: '2-q12',
        unitId: 'unit-2',
        lessonId: '2a',
        category: 'grammar',
        difficulty: 'hard',
        skill: 'countable and uncountable',
        page: 18,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018We eat ___ rice in my family.\u2019",
          options: [
            { label: 'a lot of', correct: true },
            { label: 'many', correct: false },
            { label: 'a few', correct: false },
          ],
        },
        explanation: "Rice is uncountable, so we use a lot of, not many or a few.",
      },
    ],
  },

  {
    id: 'quiz-unit-3',
    unitId: 'unit-3',
    title: 'Unit 3 Quiz',
    description: 'this / these / those, have got, there is / are, invitations and the home.',
    skills: ['this / that / these / those', 'have got', 'there is / there are', 'invitations and offers', 'rooms and furniture'],
    questions: [
      {
        id: '3-q1',
        unitId: 'unit-3',
        lessonId: '3a',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'this / that / these / those',
        page: 26,
        question: {
          kind: 'mcq',
          prompt: "A door is right next to you. Complete: \u2018___ door is heavy.\u2019",
          options: [
            { label: 'This', correct: true },
            { label: 'That', correct: false },
            { label: 'Those', correct: false },
          ],
        },
        explanation: "We use this for things that are close to us and singular.",
      },
      {
        id: '3-q2',
        unitId: 'unit-3',
        lessonId: '3a',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'this / that / these / those',
        page: 26,
        question: {
          kind: 'mcq',
          prompt: "The towels are across the room. Complete: \u2018Can you see ___ towels over there?\u2019",
          options: [
            { label: 'those', correct: true },
            { label: 'these', correct: false },
            { label: 'this', correct: false },
          ],
        },
        explanation: "Those is for plural things that are not close to us.",
      },
      {
        id: '3-q3',
        unitId: 'unit-3',
        lessonId: '3b',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'have got',
        page: 27,
        question: {
          kind: 'mcq',
          prompt: "Complete the question: \u2018___ you got any money?\u2019",
          options: [
            { label: 'Have', correct: true },
            { label: 'Has', correct: false },
            { label: 'Are', correct: false },
          ],
        },
        explanation: "Have got needs the auxiliary have in questions: Have you got\u2026?",
      },
      {
        id: '3-q4',
        unitId: 'unit-3',
        lessonId: '3b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'have got',
        page: 27,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018She ___ got a sister.\u2019",
          options: [
            { label: 'has', correct: true },
            { label: 'have', correct: false },
            { label: 'is', correct: false },
          ],
        },
        explanation: "With he / she / it, have got becomes has got.",
      },
      {
        id: '3-q5',
        unitId: 'unit-3',
        lessonId: '3d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'there is / there are',
        page: 30,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018___ a park near my house.\u2019",
          options: [
            { label: 'There\u2019s', correct: true },
            { label: 'There are', correct: false },
            { label: 'Is', correct: false },
          ],
        },
        explanation: "A park is singular, so we use there\u2019s (there is).",
      },
      {
        id: '3-q6',
        unitId: 'unit-3',
        lessonId: '3d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'there is / there are',
        page: 30,
        question: {
          kind: 'mcq',
          prompt: "Complete the question: \u2018___ there any restaurants near here?\u2019",
          options: [
            { label: 'Are', correct: true },
            { label: 'Is', correct: false },
            { label: 'Do', correct: false },
          ],
        },
        explanation: "Restaurants is plural, so the question form is Are there\u2026?",
      },
      {
        id: '3-q7',
        unitId: 'unit-3',
        lessonId: '3c',
        category: 'communication',
        difficulty: 'medium',
        skill: 'inviting with Would you like',
        page: 28,
        question: {
          kind: 'mcq',
          prompt: "Complete the invitation: \u2018Would you like ___ come to dinner on Friday?\u2019",
          options: [
            { label: 'to', correct: true },
            { label: 'can', correct: false },
            { label: 'coming', correct: false },
          ],
        },
        explanation: "Would you like is followed by to + base form: Would you like to come\u2026?",
      },
      {
        id: '3-q8',
        unitId: 'unit-3',
        lessonId: '3c',
        category: 'communication',
        difficulty: 'easy',
        skill: 'making offers',
        page: 28,
        question: {
          kind: 'mcq',
          prompt: "Offering a guest a drink: \u2018___ I get you something?\u2019",
          options: [
            { label: 'Can', correct: true },
            { label: 'Do', correct: false },
            { label: 'Am', correct: false },
          ],
        },
        explanation: "Can I\u2026? is a friendly way to offer something.",
      },
      {
        id: '3-q9',
        unitId: 'unit-3',
        lessonId: '3a',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'rooms',
        page: 26,
        question: {
          kind: 'mcq',
          prompt: 'The room with a bath and a shower is the:',
          options: [
            { label: 'bathroom', correct: true },
            { label: 'bedroom', correct: false },
            { label: 'kitchen', correct: false },
          ],
        },
        explanation: "You wash and shower in the bathroom.",
      },
      {
        id: '3-q10',
        unitId: 'unit-3',
        lessonId: '3b',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'adjectives: opposites',
        page: 27,
        question: {
          kind: 'mcq',
          prompt: 'The opposite of \u2018small\u2019 is:',
          options: [
            { label: 'large', correct: true },
            { label: 'short', correct: false },
            { label: 'easy', correct: false },
          ],
        },
        explanation: "Large means the same as big \u2014 the opposite of small.",
      },
      {
        id: '3-q11',
        unitId: 'unit-3',
        lessonId: '3c',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'hosting and visits',
        page: 28,
        question: {
          kind: 'mcq',
          prompt: 'Someone who visits your house for dinner is a:',
          options: [
            { label: 'guest', correct: true },
            { label: 'host', correct: false },
            { label: 'neighbour', correct: false },
          ],
        },
        explanation: "The guest is the visitor; the host is the person who invites them.",
      },
      {
        id: '3-q12',
        unitId: 'unit-3',
        lessonId: '3b',
        category: 'grammar',
        difficulty: 'hard',
        skill: 'have got: has got',
        page: 27,
        question: {
          kind: 'mcq',
          prompt: "In the sentence \u2018He\u2019s got a bike\u2019, \u2019s means:",
          options: [
            { label: 'has', correct: true },
            { label: 'is', correct: false },
            { label: 'does', correct: false },
          ],
        },
        explanation: "He\u2019s got = he has got. The \u2019s here is short for has.",
      },
    ],
  },

  {
    id: 'quiz-unit-4',
    unitId: 'unit-4',
    title: 'Unit 4 Quiz',
    description: 'Past simple of be, dates and numbers, should, shops and the seasons.',
    skills: ['past simple of be', 'dates and ordinal numbers', 'how much / how many', 'should', 'places in town'],
    questions: [
      {
        id: '4-q1',
        unitId: 'unit-4',
        lessonId: '4a',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'past simple of be',
        page: 34,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018The first photo ___ taken in 2010.\u2019",
          options: [
            { label: 'was', correct: true },
            { label: 'were', correct: false },
            { label: 'is', correct: false },
          ],
        },
        explanation: "The first photo is singular and we are talking about the past, so the verb is was.",
      },
      {
        id: '4-q2',
        unitId: 'unit-4',
        lessonId: '4a',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'past simple of be',
        page: 34,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018The first selfies ___ not popular at first.\u2019",
          options: [
            { label: 'were', correct: true },
            { label: 'was', correct: false },
            { label: 'are', correct: false },
          ],
        },
        explanation: "Selfies is plural, so the past form is were.",
      },
      {
        id: '4-q3',
        unitId: 'unit-4',
        lessonId: '4a',
        category: 'grammar',
        difficulty: 'hard',
        skill: 'dates',
        page: 34,
        question: {
          kind: 'mcq',
          prompt: 'How do you say the date 4 May?',
          options: [
            { label: 'the fourth of May', correct: true },
            { label: 'the four of May', correct: false },
            { label: 'May four', correct: false },
          ],
        },
        explanation: "Dates use ordinal numbers: the fourth of May.",
      },
      {
        id: '4-q4',
        unitId: 'unit-4',
        lessonId: '4b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'how much / how many',
        page: 35,
        question: {
          kind: 'mcq',
          prompt: "Complete the question: \u2018How ___ water do you drink a day?\u2019",
          options: [
            { label: 'much', correct: true },
            { label: 'many', correct: false },
            { label: 'a lot', correct: false },
          ],
        },
        explanation: "Water is uncountable, so we use how much.",
      },
      {
        id: '4-q5',
        unitId: 'unit-4',
        lessonId: '4b',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'numbers: approximate',
        page: 35,
        question: {
          kind: 'mcq',
          prompt: "\u2018Our school has ___ a thousand students\u2019. 98% of a thousand is about:",
          options: [
            { label: 'nearly', correct: true },
            { label: 'over', correct: false },
            { label: 'exactly', correct: false },
          ],
        },
        explanation: "'Nearly a thousand' means a little less than a thousand. 'Over' would be more.",
      },
      {
        id: '4-q6',
        unitId: 'unit-4',
        lessonId: '4d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'should / shouldn\u2019t',
        page: 38,
        question: {
          kind: 'mcq',
          prompt: "Complete the advice: \u2018You ___ walk around the city late at night if you don\u2019t know it.\u2019",
          options: [
            { label: 'shouldn\u2019t', correct: true },
            { label: 'should', correct: false },
            { label: 'don\u2019t', correct: false },
          ],
        },
        explanation: "Shouldn\u2019t gives negative advice: it\u2019s not a good idea.",
      },
      {
        id: '4-q7',
        unitId: 'unit-4',
        lessonId: '4d',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'imperatives',
        page: 38,
        question: {
          kind: 'mcq',
          prompt: "Complete the instruction: \u2018___ me tomorrow!\u2019",
          options: [
            { label: 'Call', correct: true },
            { label: 'Calling', correct: false },
            { label: 'To call', correct: false },
          ],
        },
        explanation: "Instructions and advice use the base form of the verb: Call me.",
      },
      {
        id: '4-q8',
        unitId: 'unit-4',
        lessonId: '4c',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'places in town',
        page: 36,
        question: {
          kind: 'mcq',
          prompt: 'You buy bread and cakes here:',
          options: [
            { label: 'the bakery', correct: true },
            { label: 'the bookshop', correct: false },
            { label: "the chemist's", correct: false },
          ],
        },
        explanation: "A bakery sells bread and cakes.",
      },
      {
        id: '4-q9',
        unitId: 'unit-4',
        lessonId: '4c',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'places in town',
        page: 36,
        question: {
          kind: 'mcq',
          prompt: "You buy medicine and toothpaste here:",
          options: [
            { label: "the chemist's", correct: true },
            { label: 'the bakery', correct: false },
            { label: "the newsagent's", correct: false },
          ],
        },
        explanation: "A chemist\u2019s (or pharmacy) sells medicine and toiletries.",
      },
      {
        id: '4-q10',
        unitId: 'unit-4',
        lessonId: '4d',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'the seasons',
        page: 38,
        question: {
          kind: 'mcq',
          prompt: 'Complete the seasons of the year: spring, summer, autumn, ___',
          options: [
            { label: 'winter', correct: true },
            { label: 'November', correct: false },
            { label: 'night', correct: false },
          ],
        },
        explanation: "The four seasons are spring, summer, autumn and winter.",
      },
      {
        id: '4-q11',
        unitId: 'unit-4',
        lessonId: '4b',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'writing numbers',
        page: 35,
        question: {
          kind: 'fill-blank',
          before: '2,500 =',
          answer: 'two thousand five hundred',
          accept: ['two thousand and five hundred', 'twothousandfivehundred'],
          after: '',
        },
        explanation: "2,500 in words is two thousand five hundred.",
      },
      {
        id: '4-q12',
        unitId: 'unit-4',
        lessonId: '4d',
        category: 'reading',
        difficulty: 'medium',
        skill: 'reading: sakura',
        page: 38,
        question: {
          kind: 'true-false',
          statement: "In the sakura article, local people go to the parks to see the cherry blossom.",
          correct: true,
        },
        explanation: "The article tells how people visit the parks to enjoy the pink blossom.",
      },
    ],
  },

  {
    id: 'quiz-unit-5',
    unitId: 'unit-5',
    title: 'Unit 5 Quiz',
    description: 'Past simple, telling the time, and modifiers like quite and really.',
    skills: ['past simple', 'quite / very / really + adjectives', 'telling the time', 'life events'],
    questions: [
      {
        id: '5-q1',
        unitId: 'unit-5',
        lessonId: '5a',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'past simple',
        page: 49,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018Last year I ___ English every day.\u2019",
          options: [
            { label: 'studied', correct: true },
            { label: 'study', correct: false },
            { label: 'studies', correct: false },
          ],
        },
        explanation: "Last year is past time, so we use the past simple: studied.",
      },
      {
        id: '5-q2',
        unitId: 'unit-5',
        lessonId: '5a',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'past simple',
        page: 49,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018She ___ to work by bus yesterday.\u2019",
          options: [
            { label: 'went', correct: true },
            { label: 'goes', correct: false },
            { label: 'go', correct: false },
          ],
        },
        explanation: "Yesterday signals the past; the past simple of go is went.",
      },
      {
        id: '5-q3',
        unitId: 'unit-5',
        lessonId: '5b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'past simple: irregular verbs',
        page: 51,
        question: {
          kind: 'mcq',
          prompt: 'The past simple of take is:',
          options: [
            { label: 'took', correct: true },
            { label: 'taked', correct: false },
            { label: 'taken', correct: false },
          ],
        },
        explanation: "Take is an irregular verb: take \u2014 took \u2014 taken.",
      },
      {
        id: '5-q4',
        unitId: 'unit-5',
        lessonId: '5b',
        category: 'grammar',
        difficulty: 'hard',
        skill: 'past simple: questions',
        page: 51,
        question: {
          kind: 'mcq',
          prompt: "Complete the question: \u2018Why ___ the chef phone the supplier?\u2019",
          options: [
            { label: 'did', correct: true },
            { label: 'does', correct: false },
            { label: 'is', correct: false },
          ],
        },
        explanation: "Past simple questions use did + base form: Why did the chef phone\u2026?",
      },
      {
        id: '5-q5',
        unitId: 'unit-5',
        lessonId: '5b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'past simple: negatives',
        page: 51,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018He didn\u2019t ___ his ice-cream maker.\u2019",
          options: [
            { label: 'use', correct: true },
            { label: 'uses', correct: false },
            { label: 'used', correct: false },
          ],
        },
        explanation: "Didn\u2019t is followed by the base form of the verb: didn\u2019t use.",
      },
      {
        id: '5-q6',
        unitId: 'unit-5',
        lessonId: '5d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'modifiers: really',
        page: 54,
        question: {
          kind: 'mcq',
          prompt: "The band was amazing. You say it was ___ good.",
          options: [
            { label: 'really', correct: true },
            { label: 'quite', correct: false },
            { label: 'a bit', correct: false },
          ],
        },
        explanation: "Really makes the adjective stronger: really good.",
      },
      {
        id: '5-q7',
        unitId: 'unit-5',
        lessonId: '5d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'modifiers: quite',
        page: 54,
        question: {
          kind: 'mcq',
          prompt: "The weekend was OK \u2014 not very good, not bad. You say: \u2018It was ___ good.\u2019",
          options: [
            { label: 'quite', correct: true },
            { label: 'really', correct: false },
            { label: 'very', correct: false },
          ],
        },
        explanation: "Quite makes the adjective weaker: quite good = fairly good.",
      },
      {
        id: '5-q8',
        unitId: 'unit-5',
        lessonId: '5c',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'telling the time',
        page: 53,
        question: {
          kind: 'mcq',
          prompt: 'The time is 2:30. You say:',
          options: [
            { label: 'It\u2019s half past two.', correct: true },
            { label: 'It\u2019s half to three.', correct: false },
            { label: 'It\u2019s two past half.', correct: false },
          ],
        },
        explanation: "30 minutes past the hour is half past.",
      },
      {
        id: '5-q9',
        unitId: 'unit-5',
        lessonId: '5c',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'telling the time',
        page: 53,
        question: {
          kind: 'mcq',
          prompt: 'The time is 3:50. You say:',
          options: [
            { label: 'It\u2019s ten to four.', correct: true },
            { label: 'It\u2019s ten past four.', correct: false },
            { label: 'It\u2019s ten to three.', correct: false },
          ],
        },
        explanation: "10 minutes before the hour is ten to: ten to four.",
      },
      {
        id: '5-q10',
        unitId: 'unit-5',
        lessonId: '5b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'past simple: irregular verbs',
        page: 51,
        question: {
          kind: 'fill-blank',
          before: 'The chef (make)',
          answer: 'made',
          after: 'fresh pasta every evening.',
        },
        explanation: "Make is irregular in the past: made.",
      },
      {
        id: '5-q11',
        unitId: 'unit-5',
        lessonId: '5b',
        category: 'reading',
        difficulty: 'medium',
        skill: 'reading: a famous restaurant',
        page: 51,
        question: {
          kind: 'true-false',
          statement: "In the story, Park Mak-rye opened a restaurant and worked from 4 a.m. to 10 p.m.",
          correct: true,
        },
        explanation: "The article says she set up a restaurant and worked those very long hours.",
      },
      {
        id: '5-q12',
        unitId: 'unit-5',
        lessonId: '5b',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'phrases with get',
        page: 51,
        question: {
          kind: 'mcq',
          prompt: "Which phrase means \u2018stop being single\u2019?",
          options: [
            { label: 'get married', correct: true },
            { label: 'get up', correct: false },
            { label: 'get a job', correct: false },
          ],
        },
        explanation: "Get married = to take a husband or wife.",
      },
    ],
  },

  {
    id: 'quiz-unit-6',
    unitId: 'unit-6',
    title: 'Unit 6 Quiz',
    description: 'Present continuous, comparatives and prepositions of movement.',
    skills: ['present continuous', 'comparatives', 'prepositions of movement', 'clothes and shopping', 'describing places'],
    questions: [
      {
        id: '6-q1',
        unitId: 'unit-6',
        lessonId: '6a',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'present continuous',
        page: 58,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018I ___ looking at your photos now.\u2019",
          options: [
            { label: 'am', correct: true },
            { label: 'is', correct: false },
            { label: 'are', correct: false },
          ],
        },
        explanation: "With I we use am in the present continuous.",
      },
      {
        id: '6-q2',
        unitId: 'unit-6',
        lessonId: '6a',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'present continuous',
        page: 58,
        question: {
          kind: 'mcq',
          prompt: "Complete the question: \u2018What ___ she wearing today?\u2019",
          options: [
            { label: 'is', correct: true },
            { label: 'are', correct: false },
            { label: 'does', correct: false },
          ],
        },
        explanation: "She + present continuous uses is: What is she wearing?",
      },
      {
        id: '6-q3',
        unitId: 'unit-6',
        lessonId: '6b',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'comparatives',
        page: 59,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018The boat is ___ than the car.\u2019",
          options: [
            { label: 'slower', correct: true },
            { label: 'more slow', correct: false },
            { label: 'slowest', correct: false },
          ],
        },
        explanation: "Slower is the comparative of slow (than compares two things).",
      },
      {
        id: '6-q4',
        unitId: 'unit-6',
        lessonId: '6b',
        category: 'grammar',
        difficulty: 'hard',
        skill: 'comparatives',
        page: 59,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018The mountains are ___ than the city.\u2019",
          options: [
            { label: 'more beautiful', correct: true },
            { label: 'beautifuller', correct: false },
            { label: 'the most beautiful', correct: false },
          ],
        },
        explanation: "Long adjectives form the comparative with more: more beautiful.",
      },
      {
        id: '6-q5',
        unitId: 'unit-6',
        lessonId: '6b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'irregular comparatives',
        page: 59,
        question: {
          kind: 'mcq',
          prompt: "bad \u2192 worse. Good \u2192 ___",
          options: [
            { label: 'better', correct: true },
            { label: 'gooder', correct: false },
            { label: 'more good', correct: false },
          ],
        },
        explanation: "Good and bad have irregular comparatives: better and worse.",
      },
      {
        id: '6-q6',
        unitId: 'unit-6',
        lessonId: '6d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'prepositions of movement',
        page: 62,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018She left the shop and walked ___ it, across the street.\u2019",
          options: [
            { label: 'out of', correct: true },
            { label: 'into', correct: false },
            { label: 'along', correct: false },
          ],
        },
        explanation: "Leave a place = walk out of it.",
      },
      {
        id: '6-q7',
        unitId: 'unit-6',
        lessonId: '6d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'prepositions of movement',
        page: 62,
        question: {
          kind: 'mcq',
          prompt: "Cross a park from one side to the other: \u2018walk ___ the park.\u2019",
          options: [
            { label: 'through', correct: true },
            { label: 'into', correct: false },
            { label: 'at', correct: false },
          ],
        },
        explanation: "Through means in one side and out of the other.",
      },
      {
        id: '6-q8',
        unitId: 'unit-6',
        lessonId: '6a',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'describing clothes',
        page: 58,
        question: {
          kind: 'mcq',
          prompt: 'A pattern of small squares in two colours is:',
          options: [
            { label: 'checked', correct: true },
            { label: 'striped', correct: false },
            { label: 'plain', correct: false },
          ],
        },
        explanation: "Checked clothes have a pattern of squares.",
      },
      {
        id: '6-q9',
        unitId: 'unit-6',
        lessonId: '6b',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'transport: on foot',
        page: 59,
        question: {
          kind: 'mcq',
          prompt: "It takes ten minutes when you walk: \u2018It\u2019s ten minutes ___ foot.\u2019",
          options: [
            { label: 'on', correct: true },
            { label: 'by', correct: false },
            { label: 'at', correct: false },
          ],
        },
        explanation: "We say on foot, but by bus, by bike, by car.",
      },
      {
        id: '6-q10',
        unitId: 'unit-6',
        lessonId: '6b',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'adjectives: opposites',
        page: 59,
        question: {
          kind: 'mcq',
          prompt: 'A ___ ticket does not cost much money.',
          options: [
            { label: 'cheap', correct: true },
            { label: 'expensive', correct: false },
            { label: 'crowded', correct: false },
          ],
        },
        explanation: "Cheap means it costs very little.",
      },
      {
        id: '6-q11',
        unitId: 'unit-6',
        lessonId: '6c',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'describing places',
        page: 60,
        question: {
          kind: 'mcq',
          prompt: 'The place where two streets meet is the:',
          options: [
            { label: 'corner', correct: true },
            { label: 'bridge', correct: false },
            { label: 'crossing', correct: false },
          ],
        },
        explanation: "Two streets meet at a corner.",
      },
      {
        id: '6-q12',
        unitId: 'unit-6',
        lessonId: '6r',
        category: 'reading',
        difficulty: 'medium',
        skill: 'reading: the wolf story',
        page: 63,
        question: {
          kind: 'true-false',
          statement: 'In the story, the wolf chased the car.',
          correct: true,
        },
        explanation: "The wolf ran after them and they had to drive faster to escape.",
      },
    ],
  },

  {
    id: 'quiz-unit-7',
    unitId: 'unit-7',
    title: 'Unit 7 Quiz',
    description: 'Articles, the present simple vs present continuous, verb + to, and phrasal verbs.',
    skills: ['articles: a / an / the', 'present simple vs present continuous', 'verb + to + infinitive', 'phrasal verbs', 'telephoning'],
    questions: [
      {
        id: '7-q1',
        unitId: 'unit-7',
        lessonId: '7a',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'articles: a / an',
        page: 66,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018Stefano is ___ professional sleeper.\u2019",
          options: [
            { label: 'a', correct: true },
            { label: 'an', correct: false },
            { label: 'the', correct: false },
          ],
        },
        explanation: "We use a before a singular job or role mentioned for the first time.",
      },
      {
        id: '7-q2',
        unitId: 'unit-7',
        lessonId: '7a',
        category: 'grammar',
        difficulty: 'hard',
        skill: 'articles: zero article',
        page: 66,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018He spends more time writing reports than sleeping in ___ bed.\u2019",
          options: [
            { label: '(no article)', correct: true },
            { label: 'a', correct: false },
            { label: 'the', correct: false },
          ],
        },
        explanation: "We say in bed with no article.",
      },
      {
        id: '7-q3',
        unitId: 'unit-7',
        lessonId: '7b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'present simple vs continuous',
        page: 67,
        question: {
          kind: 'mcq',
          prompt: "A habit. Complete: \u2018She ___ in a big kitchen every day.\u2019",
          options: [
            { label: 'works', correct: true },
            { label: 'is working', correct: false },
            { label: 'work', correct: false },
          ],
        },
        explanation: "Every day + a permanent routine needs the present simple: works.",
      },
      {
        id: '7-q4',
        unitId: 'unit-7',
        lessonId: '7b',
        category: 'grammar',
        difficulty: 'hard',
        skill: 'present simple vs continuous',
        page: 67,
        question: {
          kind: 'mcq',
          prompt: "Right now. Complete: \u2018Today he ___ video.\u2019",
          options: [
            { label: 'is recording', correct: true },
            { label: 'records', correct: false },
            { label: 'record', correct: false },
          ],
        },
        explanation: "An action happening now uses the present continuous: is recording.",
      },
      {
        id: '7-q5',
        unitId: 'unit-7',
        lessonId: '7d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'verb + to + infinitive',
        page: 70,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018I\u2019d like ___ a foreign language.\u2019",
          options: [
            { label: 'to learn', correct: true },
            { label: 'learn', correct: false },
            { label: 'learning', correct: false },
          ],
        },
        explanation: "Would like is followed by to + infinitive: would like to learn.",
      },
      {
        id: '7-q6',
        unitId: 'unit-7',
        lessonId: '7c',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'telephoning',
        page: 68,
        question: {
          kind: 'mcq',
          prompt: "Complete the phone scene: \u2018Leave a ___ and we\u2019ll call you back.\u2019",
          options: [
            { label: 'message', correct: true },
            { label: 'menu', correct: false },
            { label: 'money', correct: false },
          ],
        },
        explanation: "On the phone you leave a message when the person is not there.",
      },
      {
        id: '7-q7',
        unitId: 'unit-7',
        lessonId: '7b',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'phrasal verbs',
        page: 67,
        question: {
          kind: 'mcq',
          prompt: "Care for animals. Complete: \u2018___ the elephants.\u2019",
          options: [
            { label: 'Look after', correct: true },
            { label: 'Give up', correct: false },
            { label: 'Pick up', correct: false },
          ],
        },
        explanation: "Look after = take care of.",
      },
      {
        id: '7-q8',
        unitId: 'unit-7',
        lessonId: '7b',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'phrasal verbs',
        page: 67,
        question: {
          kind: 'mcq',
          prompt: "Switch off your phone. Complete: \u2018Please ___ your phone in the cinema.\u2019",
          options: [
            { label: 'turn off', correct: true },
            { label: 'give up', correct: false },
            { label: 'look up', correct: false },
          ],
        },
        explanation: "Turn off = switch off (a device).",
      },
      {
        id: '7-q9',
        unitId: 'unit-7',
        lessonId: '7c',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'telephoning',
        page: 68,
        question: {
          kind: 'mcq',
          prompt: 'A system that records spoken messages:',
          options: [
            { label: 'voicemail', correct: true },
            { label: 'email', correct: false },
            { label: 'postcard', correct: false },
          ],
        },
        explanation: "Voicemail records a spoken message for you to listen to later.",
      },
      {
        id: '7-q10',
        unitId: 'unit-7',
        lessonId: '7d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'verb + to + infinitive',
        page: 70,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018It\u2019s important for me ___ good photos.\u2019",
          options: [
            { label: 'to take', correct: true },
            { label: 'taking', correct: false },
            { label: 'take', correct: false },
          ],
        },
        explanation: "It\u2019s important for me is followed by to + infinitive.",
      },
      {
        id: '7-q11',
        unitId: 'unit-7',
        lessonId: '7r',
        category: 'reading',
        difficulty: 'medium',
        skill: 'reading: from computers to pizzas',
        page: 71,
        question: {
          kind: 'true-false',
          statement: "In the story, J\u00e1nos left his computer job and started delivering pizzas.",
          correct: true,
        },
        explanation: "J\u00e1nos quit his IT work to run a pizza delivery business.",
      },
      {
        id: '7-q12',
        unitId: 'unit-7',
        lessonId: '7a',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'articles: the',
        page: 66,
        question: {
          kind: 'mcq',
          prompt: "We both know which man. Complete: \u2018That\u2019s ___ man in the grey suit.\u2019",
          options: [
            { label: 'the', correct: true },
            { label: 'a', correct: false },
            { label: 'an', correct: false },
          ],
        },
        explanation: "The is used when the listener knows which thing or person we mean.",
      },
    ],
  },

  {
    id: 'quiz-unit-8',
    unitId: 'unit-8',
    title: 'Unit 8 Quiz',
    description: 'Superlatives, be going to, adverbs of manner, and travel plans.',
    skills: ['superlatives', 'be going to (plans)', 'adverbs of manner', 'holidays and travel'],
    questions: [
      {
        id: '8-q1',
        unitId: 'unit-8',
        lessonId: '8a',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'superlatives',
        page: 78,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018The train is ___ way to get there. (cheap)\u2019",
          options: [
            { label: 'the cheapest', correct: true },
            { label: 'the cheaper', correct: false },
            { label: 'more cheap', correct: false },
          ],
        },
        explanation: "The + -est is the superlative of one-syllable adjectives: the cheapest.",
      },
      {
        id: '8-q2',
        unitId: 'unit-8',
        lessonId: '8a',
        category: 'grammar',
        difficulty: 'hard',
        skill: 'superlatives',
        page: 78,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018The Pena Palace is ___ place in Sintra. (beautiful)\u2019",
          options: [
            { label: 'the most beautiful', correct: true },
            { label: 'the beautifullest', correct: false },
            { label: 'more beautiful', correct: false },
          ],
        },
        explanation: "Long adjectives form the superlative with the most.",
      },
      {
        id: '8-q3',
        unitId: 'unit-8',
        lessonId: '8a',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'superlatives: irregular',
        page: 78,
        question: {
          kind: 'mcq',
          prompt: "Complete the question: \u2018What\u2019s ___ thing to do near Lisbon? (good)\u2019",
          options: [
            { label: 'the best', correct: true },
            { label: 'the goodest', correct: false },
            { label: 'the better', correct: false },
          ],
        },
        explanation: "Good has an irregular superlative: the best.",
      },
      {
        id: '8-q4',
        unitId: 'unit-8',
        lessonId: '8b',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'be going to',
        page: 79,
        question: {
          kind: 'mcq',
          prompt: "Complete the question about plans: \u2018What ___ you going to do at the weekend?\u2019",
          options: [
            { label: 'are', correct: true },
            { label: 'is', correct: false },
            { label: 'do', correct: false },
          ],
        },
        explanation: "With you, be going to uses are: What are you going to do\u2026?",
      },
      {
        id: '8-q5',
        unitId: 'unit-8',
        lessonId: '8b',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'be going to',
        page: 79,
        question: {
          kind: 'mcq',
          prompt: "Complete the plan: \u2018I ___ take a boat trip on Sunday.\u2019",
          options: [
            { label: "'m going to", correct: true },
            { label: "'m go to", correct: false },
            { label: 'will going to', correct: false },
          ],
        },
        explanation: "Be going to + base form describes a plan: I\u2019m going to take\u2026",
      },
      {
        id: '8-q6',
        unitId: 'unit-8',
        lessonId: '8d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'adverbs of manner',
        page: 82,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018They know the area ___.\u2019",
          options: [
            { label: 'well', correct: true },
            { label: 'good', correct: false },
            { label: 'nicely', correct: false },
          ],
        },
        explanation: "Well is the adverb of good: \u2018know well\u2019 is correct.",
      },
      {
        id: '8-q7',
        unitId: 'unit-8',
        lessonId: '8d',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'adverbs of manner',
        page: 82,
        question: {
          kind: 'mcq',
          prompt: "Complete the sentence: \u2018They walk ___ in the snow.\u2019",
          options: [
            { label: 'slowly', correct: true },
            { label: 'slow', correct: false },
            { label: 'slowness', correct: false },
          ],
        },
        explanation: "Slowly is the adverb of manner from slow.",
      },
      {
        id: '8-q8',
        unitId: 'unit-8',
        lessonId: '8c',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'hotel phrases',
        page: 80,
        question: {
          kind: 'mcq',
          prompt: "To get a hotel room you need to ___ a room.",
          options: [
            { label: 'book', correct: true },
            { label: 'borrow', correct: false },
            { label: 'make', correct: false },
          ],
        },
        explanation: "Book a room = reserve a room before you arrive.",
      },
      {
        id: '8-q9',
        unitId: 'unit-8',
        lessonId: '8c',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'travel',
        page: 80,
        question: {
          kind: 'mcq',
          prompt: 'Transport that takes you between the city and the airport is:',
          options: [
            { label: 'an airport transfer', correct: true },
            { label: 'a city break', correct: false },
            { label: 'a sightseeing trip', correct: false },
          ],
        },
        explanation: "An airport transfer is the service that connects you to the airport.",
      },
      {
        id: '8-q10',
        unitId: 'unit-8',
        lessonId: '8b',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'holiday activities',
        page: 79,
        question: {
          kind: 'mcq',
          prompt: 'To visit famous places on holiday you go ___',
          options: [
            { label: 'sightseeing', correct: true },
            { label: 'shopping', correct: false },
            { label: 'swimming', correct: false },
          ],
        },
        explanation: "Go sightseeing = visit the well-known places of a city.",
      },
      {
        id: '8-q11',
        unitId: 'unit-8',
        lessonId: '8a',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'describing places',
        page: 78,
        question: {
          kind: 'mcq',
          prompt: 'The land that is next to the sea is:',
          options: [
            { label: 'the coast', correct: true },
            { label: 'the forest', correct: false },
            { label: 'the desert', correct: false },
          ],
        },
        explanation: "The coast is the land beside the sea.",
      },
      {
        id: '8-q12',
        unitId: 'unit-8',
        lessonId: '8c',
        category: 'reading',
        difficulty: 'easy',
        skill: 'reading: the Arctic expedition',
        page: 80,
        question: {
          kind: 'true-false',
          statement: "In the article, Craig Mathieson took ten teenagers on a ten-day expedition.",
          correct: true,
        },
        explanation: "The article describes a ten-day Arctic expedition with ten teenagers.",
      },
    ],
  },
  {
    id: 'quiz-final-review',
    unitId: 'final-review',
    title: 'Final Review Quiz',
    description:
      'The big end-of-course check \u2013 25 questions covering the grammar and vocabulary of every unit, Units 1-8.',
    maxQuestions: 30,
    skills: [
      'present simple and continuous',
      'narrative tenses',
      'question forms',
      'modals and superlatives',
      'relative clauses',
      'used to and comparison',
      'conditionals',
      'ability and the passive',
      'words from Units 1-8',
    ],
    questions: [
      {
        id: 'fr-q1',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'Unit 1: present simple',
        question: {
          kind: 'mcq',
          prompt: 'Water ___ at 100 degrees.',
          options: [
            { label: 'boils', correct: true },
            { label: 'is boiling', correct: false },
            { label: 'boil', correct: false },
          ],
        },
        explanation: 'Facts and general truths use the present simple: water boils.',
      },
      {
        id: 'fr-q3',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'Unit 1: adverbs of frequency',
        question: {
          kind: 'mcq',
          prompt: 'Choose the correct sentence with the frequency adverb.',
          options: [
            { label: 'I am always tired in the morning.', correct: true },
            { label: 'I always am tired in the morning.', correct: false },
            { label: 'I always tired in the morning.', correct: false },
          ],
        },
        explanation: 'With the verb be, the adverb of frequency comes after it: am always.',
      },
      {
        id: 'fr-q5',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'Unit 2: past continuous and past simple',
        question: {
          kind: 'mcq',
          prompt: 'They were having dinner when the phone ___ .',
          options: [
            { label: 'rang', correct: true },
            { label: 'was ringing', correct: false },
            { label: 'has rung', correct: false },
          ],
        },
        explanation: 'A long action (past continuous) is interrupted by a short one (past simple): rang.',
      },
      {
        id: 'fr-q7',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'Unit 2: prepositions of time',
        question: {
          kind: 'mcq',
          prompt: 'I usually relax ___ the weekend.',
          options: [
            { label: 'at', correct: true },
            { label: 'in', correct: false },
            { label: 'on', correct: false },
          ],
        },
        explanation: 'We say at the weekend (and at night, at Christmas).',
      },
      {
        id: 'fr-q9',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'Unit 3: future arrangements',
        question: {
          kind: 'mcq',
          prompt: 'We ___ Sarah at the airport tomorrow \u2013 her flight arrives at six.',
          options: [
            { label: 'are meeting', correct: true },
            { label: 'meet', correct: false },
            { label: 'met', correct: false },
          ],
        },
        explanation: 'Arrangements with a fixed time use the present continuous: are meeting.',
      },
      {
        id: 'fr-q10',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'Unit 3: indirect questions',
        question: {
          kind: 'mcq',
          prompt: 'Could you tell me when the train ___?',
          options: [
            { label: 'leaves', correct: true },
            { label: 'does it leave', correct: false },
            { label: 'does leave', correct: false },
          ],
        },
        explanation: 'In an indirect question the word order stays normal: when the train leaves.',
      },
      {
        id: 'fr-q11',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'Unit 4: modals for rules',
        question: {
          kind: 'mcq',
          prompt: 'In the library you ___ be quiet \u2013 it\u2019s the rule.',
          options: [
            { label: 'must', correct: true },
            { label: 'mustn\u2019t', correct: false },
            { label: 'might', correct: false },
          ],
        },
        explanation: 'Must expresses a strong rule; the opposite would be mustn\u2019t make noise.',
      },
      {
        id: 'fr-q12',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'Unit 4: present perfect + superlative',
        question: {
          kind: 'mcq',
          prompt: 'That\u2019s the funniest joke I ___ ever heard.',
          options: [
            { label: 'have', correct: true },
            { label: 'did', correct: false },
            { label: 'am', correct: false },
          ],
        },
        explanation: 'A superlative with experience uses the present perfect: I have ever heard.',
      },
      {
        id: 'fr-q13',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'Unit 5: relative clauses',
        question: {
          kind: 'mcq',
          prompt: 'The woman ___ lives next door is a nurse.',
          options: [
            { label: 'who', correct: true },
            { label: 'which', correct: false },
            { label: 'where', correct: false },
          ],
        },
        explanation: 'Who refers to a person: the woman who lives next door.',
      },
      {
        id: 'fr-q14',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'Unit 5: reported speech',
        question: {
          kind: 'mcq',
          prompt: 'She said she ___ at a conference the following week.',
          options: [
            { label: 'would be', correct: true },
            { label: 'will be', correct: false },
            { label: 'were', correct: false },
          ],
        },
        explanation: 'In reported speech will moves back to would: said she would be.',
      },
      {
        id: 'fr-q15',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'Unit 6: used to',
        question: {
          kind: 'mcq',
          prompt: 'We ___ live in a small town, but we moved here in 2019.',
          options: [
            { label: 'used to', correct: true },
            { label: 'use to', correct: false },
            { label: 'are used to', correct: false },
          ],
        },
        explanation: 'Used to + infinitive describes past habits or states that are no longer true.',
      },
      {
        id: 'fr-q17',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'Unit 7: first conditional',
        question: {
          kind: 'mcq',
          prompt: 'If we ___ hard, we\u2019ll finish on time.',
          options: [
            { label: 'work', correct: true },
            { label: 'will work', correct: false },
            { label: 'worked', correct: false },
          ],
        },
        explanation: 'First conditional: if + present simple, will + infinitive.',
      },
      {
        id: 'fr-q18',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'Unit 7: second conditional',
        question: {
          kind: 'mcq',
          prompt: 'If I ___ a millionaire, I\u2019d travel around the world.',
          options: [
            { label: 'were', correct: true },
            { label: 'am', correct: false },
            { label: 'will be', correct: false },
          ],
        },
        explanation: 'Second conditional uses the past simple (were) with would in the main clause.',
      },
      {
        id: 'fr-q19',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'easy',
        skill: 'Unit 8: can, could, be able to',
        question: {
          kind: 'mcq',
          prompt: 'I ___ swim when I was five years old.',
          options: [
            { label: 'could', correct: true },
            { label: 'can', correct: false },
            { label: 'am able to', correct: false },
          ],
        },
        explanation: 'Could is the past of can for ability: I could swim.',
      },
      {
        id: 'fr-q20',
        unitId: 'final-review',
        lessonId: 'grammar',
        category: 'grammar',
        difficulty: 'medium',
        skill: 'Unit 8: passive',
        question: {
          kind: 'mcq',
          prompt: 'Portuguese ___ in Brazil.',
          options: [
            { label: 'is spoken', correct: true },
            { label: 'speaks', correct: false },
            { label: 'speaking', correct: false },
          ],
        },
        explanation: 'Passive present: be + past participle \u2013 is spoken.',
      },
      {
        id: 'fr-q21',
        unitId: 'final-review',
        lessonId: 'vocabulary',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'Unit 1: people at work',
        question: {
          kind: 'mcq',
          prompt: 'The person you work with is your ___.',
          options: [
            { label: 'colleague', correct: true },
            { label: 'teammate', correct: false },
            { label: 'manager', correct: false },
          ],
        },
        explanation: 'A colleague is a person you work with.',
      },
      {
        id: 'fr-q22',
        unitId: 'final-review',
        lessonId: 'vocabulary',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'Unit 2: feelings',
        question: {
          kind: 'mcq',
          prompt: 'The film was really boring, so we felt ___.',
          options: [
            { label: 'bored', correct: true },
            { label: 'boring', correct: false },
            { label: 'amazed', correct: false },
          ],
        },
        explanation: '-ed adjectives describe how we feel: we felt bored.',
      },
      {
        id: 'fr-q23',
        unitId: 'final-review',
        lessonId: 'vocabulary',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'Unit 2: make collocations',
        question: {
          kind: 'fill-blank',
          before: 'I',
          answer: 'made',
          after: ' a mistake in my email and sent it to the wrong person.',
        },
        explanation: 'We make a mistake (not do a mistake).',
      },
      {
        id: 'fr-q24',
        unitId: 'final-review',
        lessonId: 'vocabulary',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'Unit 3: learning',
        question: {
          kind: 'fill-blank',
          before: 'Before the exam I',
          answer: 'revised',
          after: ' all my notes from the whole year.',
        },
        explanation: 'To revise = to prepare for a test by studying your notes.',
      },
      {
        id: 'fr-q25',
        unitId: 'final-review',
        lessonId: 'vocabulary',
        category: 'vocabulary',
        difficulty: 'hard',
        skill: 'Unit 4: success',
        question: {
          kind: 'fill-blank',
          before: 'She never gives up \u2013 she always',
          answer: 'carries on',
          after: ' even when things are difficult.',
        },
        explanation: 'To carry on = to continue. It goes with the success vocabulary of Unit 4.',
      },
      {
        id: 'fr-q26',
        unitId: 'final-review',
        lessonId: 'vocabulary',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'Unit 5: news',
        question: {
          kind: 'fill-blank',
          before: "The",
          answer: 'headline',
          after: " of the story was \u2018Shark spotted on the beach!\u2019",
        },
        explanation: 'A headline is the title of a news story, printed in large letters.',
      },
      {
        id: 'fr-q27',
        unitId: 'final-review',
        lessonId: 'vocabulary',
        category: 'vocabulary',
        difficulty: 'easy',
        skill: 'Unit 6: the arts',
        question: {
          kind: 'fill-blank',
          before: 'Beethoven was a famous',
          answer: 'composer',
          after: ' who wrote music.',
        },
        explanation: 'A composer is someone who writes music.',
      },
      {
        id: 'fr-q28',
        unitId: 'final-review',
        lessonId: 'vocabulary',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'Unit 6: extreme adjectives',
        question: {
          kind: 'mcq',
          prompt: 'The palace was absolutely ___ \u2013 we couldn\u2019t believe how big it was.',
          options: [
            { label: 'huge', correct: true },
            { label: 'big', correct: false },
            { label: 'good', correct: false },
          ],
        },
        explanation: 'Extreme adjectives like huge are used with absolutely, not very.',
      },
      {
        id: 'fr-q29',
        unitId: 'final-review',
        lessonId: 'vocabulary',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'Unit 7: travel',
        question: {
          kind: 'fill-blank',
          before: 'We only had one day, so we',
          answer: 'went sightseeing',
          after: ' around the old town.',
        },
        explanation: 'To go sightseeing = to visit the famous places of a town.',
      },
      {
        id: 'fr-q30',
        unitId: 'final-review',
        lessonId: 'vocabulary',
        category: 'vocabulary',
        difficulty: 'medium',
        skill: 'Unit 8: technology problems',
        question: {
          kind: 'fill-blank',
          before: 'My computer keeps',
          answer: 'crashing',
          after: ' in the middle of meetings.',
        },
        explanation: 'To crash = to stop working suddenly (of a computer).',
      },
    ],
  },
]

const QUIZ_BY_UNIT = new Map(UNIT_QUIZZES.map((q) => [q.unitId, q]))

export function getUnitQuiz(unitId: string): UnitQuiz | undefined {
  return QUIZ_BY_UNIT.get(unitId)
}