// استوديو الشادونج — مصادر الفيديوهات.
// الكرتون والأفلام: بتشتغل مباشرة من يوتيوب (حط videoId في youtube ولا يلزم أي ملف).
// كل "مشهد" فيه سطر الحوار + معناه بالعربي + التايم اللي يبدأ فيه:
//   scenes: [
//     { time: 2, en: "Oh no! The sofa is gone!", ar: "أوه لأ! الكنبة اختفت!" },
//   ],

export type ShadowKind = 'course' | 'cartoon' | 'movie' | 'series'

export interface ShadowScene {
  en: string
  ar?: string
  /** الثانية اللي يبدأ فيها المشهد */
  time: number
  /** نهاية المشهد (اختياري) — لو مش موجودة، هتاخد بداية المشهد اللي بعده */
  end?: number
}

export interface ShadowClip {
  id: string
  title: string
  kind: ShadowKind
  /** اسم ملف mp4 جوه public/videos/ (لو الفيديو ملف على الموقع) — أو حط youtube بداله */
  file?: string
  /** آي دي فيديو يوتيوب — بيشتغل مباشرة من يوتيوب من غير أي ملفات */
  youtube?: string
  source: string
  note?: string
  /** مشاهد بتاعة المقطع — كل مشهد له سطر حوار وزر شادونج */
  scenes?: ShadowScene[]
}

export const SHADOWING_CLIPS: ShadowClip[] = []

export function getShadowClip(id: string): ShadowClip | undefined {
  return SHADOWING_CLIPS.find((c) => c.id === id)
}

// ---------------------------------------------------------------------------
// بلاي ليست: Hotel Transylvania 2 (Full movie in English)
// الجزء التاني من فيلم Hotel Transylvania — مشاهد مختارة بتشتغل مباشرة من يوتيوب.
// ---------------------------------------------------------------------------

const HOTEL2_CLIPS: ShadowClip[] = [
  {
    id: "ht2-intros",
    title: "Wedding Scene · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "idwFe11xq0E",
    source: 'YouTube',
    note: "مشهد العرس الكامل — مافيس وجوناثان وإعلان الحب قدام العيلة — النص الأوتوماتيكي للمشهد (18 سطر من الكلام)",

  scenes: [
    { time: 109.0, en: "everything you wanted, my little poison berry." },
    { time: 112.0, en: "Oh, it is, Daddy." },
    { time: 114.0, en: "Except where's Grandpa Vlad?" },
    { time: 116.0, en: "Honey, your gramps would not have been cool with this." },
    { time: 119.0, en: "He's old school." },
    { time: 121.0, en: "How do we know?" },
    { time: 122.0, en: "If he could just meet Johnny?" },
    { time: 123.0, en: "He would have eaten him." },
    { time: 125.0, en: "He's not as enlightened as your hip, Daddy." },
    { time: 128.0, en: "So you're really OK with him not being a monster?" },
    { time: 131.0, en: "Human, monster, unicorn, as long as you're happy." },
    { time: 136.0, en: "Thanks, Dad." },
    { time: 140.0, en: "And you'll always be my moonlight." },
    { time: 144.0, en: "But now on wings of love you soar." },
    { time: 148.0, en: "Now that you're Johnny's girl, Johnny's girl, and kind of Daddy's too, her" },
    { time: 155.0, en: "mom would be so happy because she always knew." },
    { time: 159.0, en: "Love is making room for all the best in you." },
    { time: 163.0, en: "Thank you." },
  ],
  },
  {
    id: "ht2-gift",
    title: "A Growing Family · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "4a-qIYMSre4",
    source: 'YouTube',
    note: "دينيس اللي فيه نص دم بشري — دراكولا مش مسيطر على الموقف زي ما هو فاكر — النص الأوتوماتيكي للمشهد (83 سطر من الكلام)",

  scenes: [
    { time: 0.0, en: "Cuz you're daddy's girl or boy daddy's girl or boy I'm hungry" },
    { time: 7.0, en: "again, honey." },
    { time: 8.0, en: "Can you give me some ice cream with anchovies?" },
    { time: 12.0, en: "No, no, no, no, you mustn't give in to your cravings." },
    { time: 15.0, en: "It's not good for the baby You need to increase your spider intake." },
    { time: 19.0, en: "So he'll be able to climb ceilings properly and eat lots of sheep." },
    { time: 23.0, en: "I Love you dad, but we don't even know what the kid's gonna be a vampire I'd be thrilled if the baby's" },
    { time: 30.0, en: "human." },
    { time: 30.0, en: "He just like Johnny humanity with thousands of years of Dracula jeans Not gonna happen as long as the" },
    { time: 37.0, en: "baby's healthy, of course a healthy little vampire or human Yes, a human who can fly as a bat" },
    { time: 44.0, en: "here." },
    { time: 45.0, en: "Just have some monster ball of soup." },
    { time: 47.0, en: "It's your mommy's recipe So" },
    { time: 87.0, en: "only the father is allowed the delivery room really I mean, okay, he's the family I guess No" },
    { time: 107.0, en: "one will ever harm you as long as I'm here my little devil dog Dad, can I hold my baby?" },
    { time: 115.0, en: "If I were dad, I'd say yes But I'm the nurse Francine." },
    { time: 120.0, en: "Hey, here you go." },
    { time: 121.0, en: "Anyways Little" },
    { time: 134.0, en: "Dennis is a year old now Wow Not" },
    { time: 141.0, en: "yeah, cute kid." },
    { time: 145.0, en: "Okay time for presents guys Oh Wow," },
    { time: 155.0, en: "is it cursed super cursed only the best straight from the crypt he's just starting to" },
    { time: 162.0, en: "walk So maybe it's heavier than His name" },
    { time: 170.0, en: "is Dennis named after my father, it's not his vampire name my little Denise a bitchy-weezy bitchy." },
    { time: 177.0, en: "Huh?" },
    { time: 178.0, en: "Are we sure he's a vampire?" },
    { time: 180.0, en: "I mean not that it's a bad thing But shouldn't have fangs and that pasty skin you guys have technically you have until you're" },
    { time: 187.0, en: "five to get your vampire fangs Oh, he'll get these fangs." },
    { time: 190.0, en: "He's a Dracula." },
    { time: 191.0, en: "He's also half lock run." },
    { time: 193.0, en: "Maybe he'd be better off where we live There's more humans there." },
    { time: 197.0, en: "What?" },
    { time: 198.0, en: "Look how well he's playing with the wolf pops We" },
    { time: 204.0, en: "have a present." },
    { time: 205.0, en: "I hope it's acceptable My first guillotine very educational." },
    { time: 212.0, en: "Well played Frank." },
    { time: 213.0, en: "It's great." },
    { time: 214.0, en: "Thank you We just have to baby-proof that honey." },
    { time: 219.0, en: "Do you know where you put the rubber guards, huh?" },
    { time: 222.0, en: "Baby-proofing a guillotine." },
    { time: 224.0, en: "So you cut your finger off." },
    { time: 226.0, en: "It's part of the fun She made me baby-proof the whole hotel someone's over-protective Stop" },
    { time: 262.0, en: "he's okay." },
    { time: 265.0, en: "He did it" },
    { time: 269.0, en: "again I don't say bleh bleh bleh Then where" },
    { time: 277.0, en: "did he get that Well, maybe sometimes you say it." },
    { time: 282.0, en: "I only say it when I say I don't say it Okay, kid we get it you can talk Just" },
    { time: 294.0, en: "checking for cavities Was" },
    { time: 310.0, en: "oh My goodness, if you really look that hideous," },
    { time: 317.0, en: "I don't think I can hang out with you Party pick up a phone." },
    { time: 323.0, en: "I don't care if Johnny said it's a cool app Johnny still new here Now part of Ted." },
    { time: 330.0, en: "Did you call a hearse for the Gremlin birds?" },
    { time: 332.0, en: "No, you're checking your Facebook page again Drag I told the guys social media is the best way to promote the hotel," },
    { time: 340.0, en: "right Clifton So drag I wanted to go through some thoughts I had as your new human relations coordinating" },
    { time: 347.0, en: "co-assistant Sure." },
    { time: 348.0, en: "It's a real job." },
    { time: 349.0, en: "Now the cheap excuse to keep maybes happy." },
    { time: 351.0, en: "So you'll never leave here, right?" },
    { time: 353.0, en: "So I was thinking since we have so many humans now, maybe Update some of the acts like maybe the magician." },
    { time: 361.0, en: "What's wrong with Harry 3i He might be a little old-school for the humans." },
    { time: 366.0, en: "Tell me sir." },
    { time: 367.0, en: "What was your card at the three of spades?" },
    { time: 372.0, en: "Is this your card my friend No, Harry's" },
    { time: 379.0, en: "great can't blame Harry for the crowd not being hip Okay, what about Wayne Wayne?" },
    { time: 384.0, en: "Are you Nazis my boy?" },
    { time: 385.0, en: "It may be something other than tennis Okay, so what you want to do is lift the racket right on impact so you get that nice topspin" },
    { time: 393.0, en: "try and hit one What" },
    { time: 403.0, en: "is that what's the noise it it's on me it's just the cell phone I got you Clifton sending you a text so you can practice how to write back" },
    { time: 416.0, en: "It's not doing it." },
    { time: 417.0, en: "I got it Dear drag Now you can text Clifton" },
    { time: 425.0, en: "all right fine How do you do this?" },
    { time: 429.0, en: "Maybe it's your fingernails." },
    { time: 431.0, en: "It's easy." },
    { time: 432.0, en: "Look." },
    { time: 432.0, en: "I'll text Mavis Psyched for date night." },
    { time: 436.0, en: "See and now look she texted right back." },
    { time: 439.0, en: "Got a cancel can't leave Dennis okay, are we Allowed to be" },
    { time: 446.0, en: "alone again." },
    { time: 447.0, en: "I need to feel loved too and sent Okay," },
    { time: 455.0, en: "all that taught me is that you're pathetic Yeah, got it." },
    { time: 458.0, en: "Maybe you should just get Bluetooth." },
    { time: 460.0, en: "Okay Bluetooth come over here." },
    { time: 465.0, en: "So now what?" },
  ],
  },
  {
    id: "ht2-mom-back",
    title: "Maman Returns · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "rNGxMhbbHtM",
    source: 'YouTube',
    note: "رجوع ماما د ووديسة السؤال اللي مفكرهم كله: دينيس وامبا ولا إنسان؟ — النص الأوتوماتيكي للمشهد (140 سطر من الكلام)",

  scenes: [
    { time: 4.0, en: "Rise and shine, my Denisovich." },
    { time: 7.0, en: "Hi, Papa." },
    { time: 8.0, en: "Hello, my little devil." },
    { time: 10.0, en: "Did you have sweet nightmares?" },
    { time: 12.0, en: "Uh-huh." },
    { time: 13.0, en: "I dreamed I saw a stegosaurus." },
    { time: 16.0, en: "Oh, and were you drinking his blood?" },
    { time: 19.0, en: "No." },
    { time: 20.0, en: "Just throwing it out there." },
    { time: 21.0, en: "Hey, you want to do something cool?" },
    { time: 24.0, en: "Yeah." },
    { time: 25.0, en: "I'm going to teach you how to turn into a bat, like me." },
    { time: 30.0, en: "See?" },
    { time: 31.0, en: "Cool." },
    { time: 32.0, en: "Yes, cool, like I said." },
    { time: 34.0, en: "Now you try." },
    { time: 36.0, en: "I'm a bat." },
    { time: 38.0, en: "I'm a bat." },
    { time: 39.0, en: "I'm a bat." },
    { time: 39.0, en: "I'm a bat." },
    { time: 40.0, en: "I'm a bat." },
    { time: 42.0, en: "I'm a bat." },
    { time: 43.0, en: "I mean, a real bat." },
    { time: 44.0, en: "I'm a bat." },
    { time: 47.0, en: "Denisovich, take a breath." },
    { time: 49.0, en: "You can really turn into a bat." },
    { time: 52.0, en: "Try." },
    { time: 53.0, en: "Feel the bat." },
    { time: 56.0, en: "Not a chicken." },
    { time: 60.0, en: "What's that?" },
    { time: 61.0, en: "The electric boogaloo?" },
    { time: 62.0, en: "If I show you I can bust a move, will you try to fly then?" },
    { time: 65.0, en: "Uh-huh." },
    { time: 66.0, en: "Dad, why are you guys dancing?" },
    { time: 69.0, en: "He was sleep dancing." },
    { time: 71.0, en: "Come on, sweetie, back to bed." },
    { time: 73.0, en: "Back to bed?" },
    { time: 73.0, en: "It's already after 8 p.m." },
    { time: 75.0, en: "Don't you remember the new sleep schedule?" },
    { time: 77.0, en: "He's going to human classes half the day." },
    { time: 80.0, en: "If he could just sleep till 2 a.m." },
    { time: 82.0, en: "tonight, it'd be so great for him." },
    { time: 83.0, en: "But honey, Dad, six of Wayne's wolf pups are having a birthday party tonight." },
    { time: 87.0, en: "You wouldn't want him to miss that." },
    { time: 89.0, en: "Dad, I love the wolf pups, but they're a little too rough for Denis." },
    { time: 94.0, en: "Too rough?" },
    { time: 94.0, en: "Haven't you noticed?" },
    { time: 96.0, en: "Denis is different." },
    { time: 97.0, en: "What are you saying?" },
    { time: 98.0, en: "Denisovich shouldn't be around monsters?" },
    { time: 101.0, en: "I love monsters!" },
    { time: 102.0, en: "Video!" },
    { time: 103.0, en: "Ha!" },
    { time: 104.0, en: "Oh, you want to show Papa Jack your monster video?" },
    { time: 110.0, en: "the coolest monster?" },
    { time: 115.0, en: "Cakey one, happy monster." },
    { time: 117.0, en: "Cakey love cake." },
    { time: 119.0, en: "Yummy!" },
    { time: 120.0, en: "Tommy good, a Tommy yay." },
    { time: 122.0, en: "Whoa, whoa, whoa, whoa." },
    { time: 123.0, en: "How is that a monster?" },
    { time: 125.0, en: "Have some cake was a lump-a-bum." },
    { time: 128.0, en: "Remember kids, a real monster always shares." },
    { time: 132.0, en: "Shares, yes." },
    { time: 133.0, en: "When I think monsters, I think shares." },
    { time: 136.0, en: "Now let me tell you what a real monster is, Denisovich." },
    { time: 140.0, en: "Dad, please, he's practically five already." },
    { time: 143.0, en: "Don't force it." },
    { time: 148.0, en: "Slow down was a lump-a-bum, the scariest monster of all is diabetes." },
    { time: 155.0, en: "Twinkle, twinkle little star, Mommy, I'm too old for lullabies." },
    { time: 161.0, en: "What?" },
    { time: 162.0, en: "That's not how that one goes." },
    { time: 163.0, en: "This is the way most people sing it." },
    { time: 165.0, en: "Most people?" },
    { time: 166.0, en: "What's wrong with..." },
    { time: 168.0, en: "Suffer, suffer, scream in pain, blood is spilling from your brain." },
    { time: 174.0, en: "Daddy." },
    { time: 175.0, en: "Come on, you know how I sang it to you." },
    { time: 177.0, en: "Zombies know you like a plum, piercing cries and you succumb." },
    { time: 185.0, en: "Suffer, suffer, scream in pain, you will never breathe again." },
    { time: 196.0, en: "Still works." },
    { time: 224.0, en: "We'd be in one." },
    { time: 227.0, en: "Mr." },
    { time: 227.0, en: "Ditch, my big boy, you made it." },
    { time: 230.0, en: "I thought about what you said, Dad." },
    { time: 233.0, en: "Maybe I was being a little overprotective." },
    { time: 235.0, en: "Thank you, Cop and Kick." },
    { time: 237.0, en: "Dennis, I'd love to use" },
    { time: 247.0, en: "that." },
    { time: 247.0, en: "Winnie, give him his space, hon." },
    { time: 250.0, en: "I'm sorry, Mavis." },
    { time: 251.0, en: "It's okay, Atwanda." },
    { time: 252.0, en: "They're just playing." },
    { time: 254.0, en: "Holy rabies, Limbo." },
    { time: 256.0, en: "I used to love that game." },
    { time: 257.0, en: "Get the nitter-baby." },
    { time: 259.0, en: "Really?" },
    { time: 260.0, en: "But I'm a parent now." },
    { time: 261.0, en: "Show them how it's done." },
    { time: 263.0, en: "Okay, okay." },
    { time: 274.0, en: "a piñata?" },
    { time: 278.0, en: "Mavis, honey, that's for later." },
    { time: 281.0, en: "We don't want the pups to have too much." },
    { time: 283.0, en: "Whoo-hoo!" },
    { time: 289.0, en: "Sugar." },
    { time: 298.0, en: "I'm sorry." },
    { time: 299.0, en: "Did I start all that?" },
    { time: 300.0, en: "Don't worry." },
    { time: 300.0, en: "There's a reason they call it a litter." },
    { time: 318.0, en: "Look!" },
    { time: 319.0, en: "Your tooth came out!" },
    { time: 320.0, en: "Are you kidding me?" },
    { time: 321.0, en: "He got his tooth knocked out?" },
    { time: 322.0, en: "Oh, yes, indeed." },
    { time: 324.0, en: "Here comes the fang." },
    { time: 325.0, en: "Dad, his baby tooth wasn't a fang." },
    { time: 327.0, en: "Why would this one be?" },
    { time: 329.0, en: "He's not a monster." },
    { time: 331.0, en: "Mm-hmm." },
    { time: 335.0, en: "The sun's gonna come out soon, and we gotta get to his classes." },
    { time: 338.0, en: "What's wrong with the classes we have here, like the kid's yoga?" },
    { time: 346.0, en: "This is Denisovich's home." },
    { time: 349.0, en: "I don't know, Dad." },
    { time: 350.0, en: "What don't you know?" },
    { time: 352.0, en: "Well, we've been talking about moving." },
    { time: 355.0, en: "Somewhere safer for Denis." },
    { time: 357.0, en: "Maybe where Johnny grew up in California." },
    { time: 360.0, en: "I'm sorry, but you can't just make somebody something they're not." },
    { time: 367.0, en: "Come on, honey." },
    { time: 367.0, en: "We have to go." },
    { time: 368.0, en: "Ting, ting." },
    { time: 370.0, en: "Maybe." },
    { time: 371.0, en: "Wait." },
    { time: 372.0, en: "You can't mean that." },
    { time: 377.0, en: "You're in on this, the leaving?" },
    { time: 379.0, en: "Uh, it's not definite at all." },
    { time: 381.0, en: "It's just something she's definitely talking about." },
    { time: 383.0, en: "But until we do it, it's not definite-tized." },
    { time: 388.0, en: "Did he just cover me with birdseed?" },
    { time: 391.0, en: "Yeah, he covered me." },
  ],
  },
  {
    id: "ht2-mummy",
    title: "Mummy Mistake · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "7y9stFHCvEY",
    source: 'YouTube',
    note: "غلطة الموميا — دراكولا بيحاول يعلّم دينيس يعمل \"أجزاء\" لكن النتيجة عالمية — النص الأوتوماتيكي للمشهد (33 سطر من الكلام)",

  scenes: [
    { time: 0.0, en: "OK, Murray, your turn." },
    { time: 3.0, en: "Uh, excuse us?" },
    { time: 5.0, en: "Do you know where someone can get a bite around here?" },
    { time: 7.0, en: "Did you seriously just ask a vampire where to get a bite?" },
    { time: 10.0, en: "Oh, gosh, I mean, we're not from around here." },
    { time: 13.0, en: "This is so embarrassing." },
    { time: 14.0, en: "Just keep going." },
    { time: 15.0, en: "Sorry to bother you." },
    { time: 16.0, en: "Love your chocolate cereal." },
    { time: 21.0, en: "So what do you want me to do now?" },
    { time: 23.0, en: "Denisovits, you won't believe it." },
    { time: 25.0, en: "The mummy can crash through walls and turn into a swarm of beetles and put the curse on anyone." },
    { time: 31.0, en: "That sounds mean." },
    { time: 33.0, en: "It's fun mean." },
    { time: 34.0, en: "OK, so check it out." },
    { time: 36.0, en: "Murray's going to conjure up the biggest sandstorm you've ever seen." },
    { time: 41.0, en: "Hidden sandstone?" },
    { time: 43.0, en: "It's been a while." },
    { time: 44.0, en: "Not my problem." },
    { time: 45.0, en: "Do it." },
    { time: 45.0, en: "Say your little spell." },
    { time: 47.0, en: "OK." },
    { time: 49.0, en: "I got this, Frank." },
    { time: 51.0, en: "Wayne." },
    { time: 52.0, en: "Just try not to faint." },
    { time: 61.0, en: "Two hot pots, battery." },
    { time: 63.0, en: "Ho, ho, soft alarm, terror of my sight." },
    { time: 65.0, en: "All men have craze on full moon-hood routine fact." },
    { time: 70.0, en: "Ho, ho, sharp alarm." },
    { time: 73.0, en: "We come of you." },
    { time: 86.0, en: "Oh, wait." },
    { time: 94.0, en: "Ooh." },
    { time: 95.0, en: "Ha, ha, ow, ow, ow." },
  ],
  },
  {
    id: "ht2-camp",
    title: "Camp Vamp · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "RkINjKcnVuY",
    source: 'YouTube',
    note: "يوم التخييم (Camp Winnepaku) — قواعد المخيم العجيب بتاعة الذلول — النص الأوتوماتيكي للمشهد (27 سطر من الكلام)",

  scenes: [
    { time: 0.0, en: "Wait and see fellas, this kid will be guzzling goat blood in no time Here" },
    { time: 9.0, en: "we are it's the vampire summer camp I went to as a kid What's it camp them?" },
    { time: 15.0, en: "No, who names their camp camp man?" },
    { time: 18.0, en: "It's camp Winnie pakaka You" },
    { time: 41.0, en: "see the needs of it." },
    { time: 42.0, en: "This is where I learned to catch mice and shape-shift And use my incredible powers and strength is" },
    { time: 49.0, en: "pretty cool." },
    { time: 51.0, en: "Ah Yes," },
    { time: 55.0, en: "I don't remember this bad Well, well, is this a night how you doing folks?" },
    { time: 62.0, en: "I'm Dana the director We're sure excited to have you legends visiting us." },
    { time: 66.0, en: "What can I do you for?" },
    { time: 68.0, en: "Well, I'm very interested in sending my grand boy Denis if it's you oh This little red-headed" },
    { time: 75.0, en: "non-fangy little guy." },
    { time: 78.0, en: "Oh, they're in there." },
    { time: 79.0, en: "He's a late fanger That's why we came here Can you show us some of the drills like where they catch the mice can" },
    { time: 86.0, en: "do of course now?" },
    { time: 87.0, en: "We call it tea mousy so" },
    { time: 100.0, en: "they don't have to catch the mice." },
    { time: 102.0, en: "No, we find This is a good way to build their confidence It's" },
    { time: 110.0, en: "right there." },
    { time: 110.0, en: "What's the matter with you?" },
    { time: 114.0, en: "Hokey-pokey." },
    { time: 118.0, en: "Here." },
    { time: 119.0, en: "It is Denis image where Papa learned to fly Yeah," },
    { time: 130.0, en: "we're over here now Had to scale it down insurance." },
    { time: 141.0, en: "Oh, you pokey." },
    { time: 143.0, en: "See you at the campfire" },
  ],
  },
  {
    id: "ht2-change",
    title: "You Can't Change Him · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "oOp7Q_xw94I",
    source: 'YouTube',
    note: "الجد فلاد بيلاقي دينيس إنسان — والمشكلة اللي بتزيد من الطرفين — النص الأوتوماتيكي للمشهد (46 سطر من الكلام)",

  scenes: [
    { time: 0.0, en: "What did you just do?" },
    { time: 1.0, en: "A few more seconds and the kid's fans would have popped right out!" },
    { time: 4.0, en: "I don't care, it's not worth it!" },
    { time: 6.0, en: "What's not worth it?" },
    { time: 8.0, en: "It was my last attempt to make the boy a vampire so you'd stay." },
    { time: 11.0, en: "By ruining his favorite thing?" },
    { time: 13.0, en: "How could you do that?" },
    { time: 14.0, en: "We were desperate!" },
    { time: 16.0, en: "You were in on this?" },
    { time: 17.0, en: "Dennis won't be happy in my town." },
    { time: 19.0, en: "Dennis hasn't been there!" },
    { time: 20.0, en: "Now has been done twice!" },
    { time: 23.0, en: "Feel the strain and the strife!" },
    { time: 25.0, en: "Shut up!" },
    { time: 27.0, en: "Johnny, Dennis is not a monster!" },
    { time: 31.0, en: "He likes avocado!" },
    { time: 32.0, en: "Because you don't let him eat anything fun!" },
    { time: 34.0, en: "I think Dennis just wants to be normal." },
    { time: 37.0, en: "Can we stop using the word normal?" },
    { time: 39.0, en: "Where we live now, he's normal." },
    { time: 41.0, en: "He is who he is!" },
    { time: 43.0, en: "And you can't change him, Dad!" },
    { time: 55.0, en: "At a place where we can hide!" },
    { time: 57.0, en: "Follow me!" },
    { time: 65.0, en: "If you didn't stop me, my great-grandson wouldn't have to be a wimp his whole life." },
    { time: 69.0, en: "Like Shlumpy over here." },
    { time: 71.0, en: "A wimp?" },
    { time: 72.0, en: "Johnny, be cool." },
    { time: 73.0, en: "You wanna throw it out, old man?" },
    { time: 75.0, en: "Certified yellow belt since 1997." },
    { time: 78.0, en: "No!" },
    { time: 79.0, en: "What's this now?" },
    { time: 80.0, en: "You're not a vampire?" },
    { time: 82.0, en: "Uh, Blair?" },
    { time: 84.0, en: "Of course he's human." },
    { time: 85.0, en: "He's our son." },
    { time: 86.0, en: "You think we're monsters?" },
    { time: 91.0, en: "You!" },
    { time: 92.0, en: "You let your daughter marry a human!" },
    { time: 95.0, en: "And have a human kid!" },
    { time: 96.0, en: "Why don't you just put a stake through my heart?" },
    { time: 99.0, en: "We don't hate humans anymore, and they don't hate us!" },
    { time: 110.0, en: "You're a fool!" },
    { time: 111.0, en: "Your great-grandson is the sweetest, kindest, most special boy I've ever met." },
    { time: 117.0, en: "And if you can't give him the love he deserves because he's half human, then you're the fool!" },
    { time: 123.0, en: "Oh, Daddy!" },
  ],
  },
  {
    id: "ht2-batfight",
    title: "Family Bat Fight · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "n1lQR-GjWYw",
    source: 'YouTube',
    note: "المعركة الجوية الأخيرة — الخفاشات المتحايلة والدفاع عن القلعة — النص الأوتوماتيكي للمشهد (5 سطر من الكلام)",

  scenes: [
    { time: 5.0, en: "this'll be fun." },
    { time: 68.0, en: "that?" },
    { time: 103.0, en: "That practice will pay off!" },
    { time: 128.0, en: "That's right!" },
    { time: 129.0, en: "You better fly away!" },
  ],
  },
  {
    id: "ht2-monster",
    title: "I'm in Love With a Monster (Ending) · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "D4_CGzg3fmQ",
    source: 'YouTube',
    note: "نهاية الفيلم — دراكولا بيتقبّل دينيس مثل ما هو وسعيد بحياتهم الجديدة — النص الأوتوماتيكي للمشهد (25 سطر من الكلام)",

  scenes: [
    { time: 1.0, en: "Papa Jock, I'm a vampire and a superhero." },
    { time: 4.0, en: "Am I cool now?" },
    { time: 6.0, en: "Now?" },
    { time: 7.0, en: "Dennis, you were always cool." },
    { time: 10.0, en: "Human, vampire, unicorn, you're perfect no matter what." },
    { time: 14.0, en: "But since I'm a vampire, can we stay here?" },
    { time: 19.0, en: "Yes." },
    { time: 20.0, en: "All right!" },
    { time: 22.0, en: "All right!" },
    { time: 23.0, en: "All right!" },
    { time: 24.0, en: "But you have to know we're going to visit you here every holiday." },
    { time: 29.0, en: "That's fine." },
    { time: 46.0, en: "Don't ever come near me or my family again." },
    { time: 65.0, en: "Daddy, you just saved a human." },
    { time: 69.0, en: "All this pressure about when the boys' fangs were coming out." },
    { time: 73.0, en: "Who cares?" },
    { time: 74.0, en: "Mine came out years ago." },
    { time: 76.0, en: "Look!" },
    { time: 79.0, en: "Okay, Dad, put them back in before we all barf." },
    { time: 82.0, en: "Hey, isn't it still somebody's birthday?" },
    { time: 91.0, en: "buy me a storm before you buy me a rose." },
    { time: 94.0, en: "We covered in dirt before we covered in gold." },
    { time: 98.0, en: "He's trying it off, yeah, he's taking me" },
    { time: 103.0, en: "over, be told." },
    { time: 104.0, en: "Cause I'm in love." },
  ],
  },
  {
    id: "ht2-credits",
    title: "I'm in Love With a Monster (End Credits) · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "1zkI6mn7Mio",
    source: 'YouTube',
    note: "أغنية النهاية من الفيلم — حط السماعات وردد الكلمات ورا الأغنية كتير — النص الأوتوماتيكي للمشهد (1 سطر من الكلام)",

  scenes: [
    { time: 27.0, en: "Be taking me out Say what you want, but I won't" },
  ],
  },
]

SHADOWING_CLIPS.push(...HOTEL2_CLIPS)
