// استوديو الشادونج — مصادر الفيديوهات.
// الكرتون والأفلام: بتشتغل مباشرة من يوتيوب (حط videoId في youtube ولا يلزم أي ملف).
// كل "مشهد" فيه سطر الحوار + معناه بالعربي + التايم اللي يبدأ فيه:
//   scenes: [
//     { time: 2, en: "Oh no! The sofa is gone!", ar: "أوه لأ! الكنبة اختفت!" },
//   ],

export type ShadowKind = 'course' | 'cartoon' | 'movie' | 'series'

export interface ShadowScene {
  en: string
  ar?: string
  /** الثانية اللي يبدأ فيها المشهد */
  time: number
  /** نهاية المشهد (اختياري) — لو مش موجودة، هتاخد بداية المشهد اللي بعده */
  end?: number
}

export interface ShadowClip {
  id: string
  title: string
  kind: ShadowKind
  /** اسم ملف mp4 جوه public/videos/ (لو الفيديو ملف على الموقع) — أو حط youtube بداله */
  file?: string
  /** آي دي فيديو يوتيوب — بيشتغل مباشرة من يوتيوب من غير أي ملفات */
  youtube?: string
  source: string
  note?: string
  /** مشاهد بتاعة المقطع — كل مشهد له سطر حوار وزر شادونج */
  scenes?: ShadowScene[]
}

export const SHADOWING_CLIPS: ShadowClip[] = []

export function getShadowClip(id: string): ShadowClip | undefined {
  return SHADOWING_CLIPS.find((c) => c.id === id)
}

// ---------------------------------------------------------------------------
// بلاي ليست: Hotel Transylvania 2 (Full movie in English)
// الجزء التاني من فيلم Hotel Transylvania — مشاهد مختارة بتشتغل مباشرة من يوتيوب.
// ---------------------------------------------------------------------------

const HOTEL2_CLIPS: ShadowClip[] = [
  {
    id: "ht2-gift",
    title: "A Growing Family · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "4a-qIYMSre4",
    source: 'YouTube',
    note: "دينيس اللي فيه نص دم بشري — دراكولا مش مسيطر على الموقف زي ما هو فاكر — النص الأوتوماتيكي للمشهد (83 سطر من الكلام)",

  scenes: [
    { time: 0.0, en: "Cuz you're daddy's girl or boy daddy's girl or boy I'm hungry", ar: "لأنك فتاة أو ولد أبي، فتاة أو ولد أبي، أنا جائع" },
    { time: 7.0, en: "again, honey.", ar: "مرة أخرى يا عزيزي." },
    { time: 8.0, en: "Can you give me some ice cream with anchovies?", ar: "هل يمكنك أن تعطيني بعض الآيس كريم مع الأنشوجة؟" },
    { time: 12.0, en: "No, no, no, no, you mustn't give in to your cravings.", ar: "لا، لا، لا، لا، لا يجب أن تستسلم لرغباتك." },
    { time: 15.0, en: "It's not good for the baby You need to increase your spider intake.", ar: "إنه ليس جيدًا للطفل. تحتاج إلى زيادة تناولك للعنكبوت." },
    { time: 19.0, en: "So he'll be able to climb ceilings properly and eat lots of sheep.", ar: "لذلك سيكون قادراً على تسلق الأسقف بشكل صحيح وأكل الكثير من الأغنام." },
    { time: 23.0, en: "I Love you dad, but we don't even know what the kid's gonna be a vampire I'd be thrilled if the baby's", ar: "أحبك يا أبي، لكننا لا نعرف حتى ما الذي سيصبح عليه الطفل مصاص دماء، وسأكون سعيدًا إذا كان الطفل" },
    { time: 30.0, en: "human.", ar: "بشر." },
    { time: 30.0, en: "He just like Johnny humanity with thousands of years of Dracula jeans Not gonna happen as long as the", ar: "إنه تمامًا مثل جوني الإنسانية مع آلاف السنين من جينز دراكولا لن يحدث طالما" },
    { time: 37.0, en: "baby's healthy, of course a healthy little vampire or human Yes, a human who can fly as a bat", ar: "الطفل يتمتع بصحة جيدة، بالطبع مصاص دماء صغير أو إنسان يتمتع بصحة جيدة نعم، إنسان يمكنه الطيران كالخفاش" },
    { time: 44.0, en: "here.", ar: "هنا." },
    { time: 45.0, en: "Just have some monster ball of soup.", ar: "فقط تناول بعض كرة الحساء الضخمة." },
    { time: 47.0, en: "It's your mommy's recipe So", ar: "إنها وصفة والدتك لذا" },
    { time: 87.0, en: "only the father is allowed the delivery room really I mean, okay, he's the family I guess No", ar: "الأب فقط هو المسموح له بدخول غرفة الولادة حقًا، حسنًا، إنه العائلة على ما أعتقد لا" },
    { time: 107.0, en: "one will ever harm you as long as I'm here my little devil dog Dad, can I hold my baby?", ar: "لن يؤذيك أحد طالما أنا هنا يا أبي، كلبي الشيطان الصغير، هل يمكنني أن أحمل طفلي؟" },
    { time: 115.0, en: "If I were dad, I'd say yes But I'm the nurse Francine.", ar: "لو كنت أبي لقلت نعم لكني الممرضة فرانسين." },
    { time: 120.0, en: "Hey, here you go.", ar: "مهلا، هنا تذهب." },
    { time: 121.0, en: "Anyways Little", ar: "على أي حال قليلا" },
    { time: 134.0, en: "Dennis is a year old now Wow Not", ar: "دينيس يبلغ من العمر عامًا الآن واو لا" },
    { time: 141.0, en: "yeah, cute kid.", ar: "نعم، طفل لطيف." },
    { time: 145.0, en: "Okay time for presents guys Oh Wow,", ar: "حسنًا، حان وقت الهدايا يا شباب، أوه واو،" },
    { time: 155.0, en: "is it cursed super cursed only the best straight from the crypt he's just starting to", ar: "هل هو ملعون ملعون للغاية فقط الأفضل مباشرة من القبو الذي بدأ فيه للتو" },
    { time: 162.0, en: "walk So maybe it's heavier than His name", ar: "يمشي فلعله أثقل من اسمه" },
    { time: 170.0, en: "is Dennis named after my father, it's not his vampire name my little Denise a bitchy-weezy bitchy.", ar: "هو اسم دينيس على اسم والدي، وليس اسم مصاص الدماء الخاص به، دينيس الصغير هو عاهرة مشاكسة." },
    { time: 177.0, en: "Huh?", ar: "هاه؟" },
    { time: 178.0, en: "Are we sure he's a vampire?", ar: "هل نحن متأكدون أنه مصاص دماء؟" },
    { time: 180.0, en: "I mean not that it's a bad thing But shouldn't have fangs and that pasty skin you guys have technically you have until you're", ar: "لا أقصد أن هذا أمر سيء ولكن لا ينبغي أن يكون لديك أنياب وهذا الجلد الفطير الذي تمتلكه يا رفاق من الناحية الفنية لديك حتى تصبح" },
    { time: 187.0, en: "five to get your vampire fangs Oh, he'll get these fangs.", ar: "خمسة للحصول على أنياب مصاص الدماء الخاص بك. أوه، سوف يحصل على هذه الأنياب." },
    { time: 190.0, en: "He's a Dracula.", ar: "إنه دراكولا." },
    { time: 191.0, en: "He's also half lock run.", ar: "إنه أيضًا نصف قفل." },
    { time: 193.0, en: "Maybe he'd be better off where we live There's more humans there.", ar: "ربما سيكون أفضل حالاً في المكان الذي نعيش فيه، فهناك المزيد من البشر." },
    { time: 197.0, en: "What?", ar: "ماذا؟" },
    { time: 198.0, en: "Look how well he's playing with the wolf pops We", ar: "انظر إلى مدى جودة لعبه مع الذئب بوبس نحن" },
    { time: 204.0, en: "have a present.", ar: "لديك هدية." },
    { time: 205.0, en: "I hope it's acceptable My first guillotine very educational.", ar: "أتمنى أن تكون مقبولة مقصلتي الأولى تعليمية للغاية." },
    { time: 212.0, en: "Well played Frank.", ar: "لعب فرانك بشكل جيد." },
    { time: 213.0, en: "It's great.", ar: "إنه لشيء رائع." },
    { time: 214.0, en: "Thank you We just have to baby-proof that honey.", ar: "شكرًا لك، علينا فقط أن نحمي هذا العسل." },
    { time: 219.0, en: "Do you know where you put the rubber guards, huh?", ar: "هل تعرف أين وضعت الحراس المطاطيين، هاه؟" },
    { time: 222.0, en: "Baby-proofing a guillotine.", ar: "حماية الطفل من المقصلة." },
    { time: 224.0, en: "So you cut your finger off.", ar: "لذلك قمت بقطع إصبعك." },
    { time: 226.0, en: "It's part of the fun She made me baby-proof the whole hotel someone's over-protective Stop", ar: "إنه جزء من المرح لقد جعلتني أحمي الفندق بأكمله من الإفراط في حماية شخص ما" },
    { time: 262.0, en: "he's okay.", ar: "انه بخير." },
    { time: 265.0, en: "He did it", ar: "لقد فعل ذلك" },
    { time: 269.0, en: "again I don't say bleh bleh bleh Then where", ar: "مرة أخرى لا أقول بليه بليه ثم أين" },
    { time: 277.0, en: "did he get that Well, maybe sometimes you say it.", ar: "هل فهم ذلك؟ حسنًا، ربما تقول ذلك أحيانًا." },
    { time: 282.0, en: "I only say it when I say I don't say it Okay, kid we get it you can talk Just", ar: "أنا أقول ذلك فقط عندما أقول أنني لا أقول ذلك حسنًا، يا فتى، لقد فهمنا أنه يمكنك التحدث فقط" },
    { time: 294.0, en: "checking for cavities Was", ar: "التحقق من وجود تجاويف كان" },
    { time: 310.0, en: "oh My goodness, if you really look that hideous,", ar: "يا إلهي، إذا كنت تبدو بشعًا حقًا،" },
    { time: 317.0, en: "I don't think I can hang out with you Party pick up a phone.", ar: "لا أعتقد أنني أستطيع قضاء الوقت معك في الحفلة والتقاط الهاتف." },
    { time: 323.0, en: "I don't care if Johnny said it's a cool app Johnny still new here Now part of Ted.", ar: "لا يهمني إذا قال جوني إنه تطبيق رائع. لا يزال جوني جديدًا هنا وهو الآن جزء من تيد." },
    { time: 330.0, en: "Did you call a hearse for the Gremlin birds?", ar: "هل اتصلت بعربة الموتى لطيور الجريملين؟" },
    { time: 332.0, en: "No, you're checking your Facebook page again Drag I told the guys social media is the best way to promote the hotel,", ar: "لا، أنت تقوم بفحص صفحتك على الفيسبوك مرة أخرى، لقد أخبرت الرفاق أن وسائل التواصل الاجتماعي هي أفضل طريقة للترويج للفندق،" },
    { time: 340.0, en: "right Clifton So drag I wanted to go through some thoughts I had as your new human relations coordinating", ar: "حسنًا يا كليفتون، لذا أردت أن أستعرض بعض الأفكار التي كانت لدي كمنسق جديد للعلاقات الإنسانية" },
    { time: 347.0, en: "co-assistant Sure.", ar: "مساعد بالتأكيد." },
    { time: 348.0, en: "It's a real job.", ar: "إنها وظيفة حقيقية." },
    { time: 349.0, en: "Now the cheap excuse to keep maybes happy.", ar: "الآن العذر الرخيص لإبقاء ربما سعيدًا." },
    { time: 351.0, en: "So you'll never leave here, right?", ar: "إذن لن تغادر هنا أبدًا، أليس كذلك؟" },
    { time: 353.0, en: "So I was thinking since we have so many humans now, maybe Update some of the acts like maybe the magician.", ar: "لذلك كنت أفكر بما أن لدينا الكثير من البشر الآن، ربما أقوم بتحديث بعض الأفعال مثل ربما الساحر." },
    { time: 361.0, en: "What's wrong with Harry 3i He might be a little old-school for the humans.", ar: "ما هو الخطأ في Harry 3i؟ قد يكون من المدرسة القديمة قليلاً بالنسبة للبشر." },
    { time: 366.0, en: "Tell me sir.", ar: "قل لي يا سيدي." },
    { time: 367.0, en: "What was your card at the three of spades?", ar: "ما هي بطاقتك في الثلاث البستوني؟" },
    { time: 372.0, en: "Is this your card my friend No, Harry's", ar: "هل هذه بطاقتك يا صديقي لا، هاري" },
    { time: 379.0, en: "great can't blame Harry for the crowd not being hip Okay, what about Wayne Wayne?", ar: "عظيم لا أستطيع إلقاء اللوم على هاري لأن الجمهور لم يكن مواكبًا للموضة حسنًا، ماذا عن واين واين؟" },
    { time: 384.0, en: "Are you Nazis my boy?", ar: "هل أنت نازيين يا ولدي؟" },
    { time: 385.0, en: "It may be something other than tennis Okay, so what you want to do is lift the racket right on impact so you get that nice topspin", ar: "قد يكون الأمر شيئًا آخر غير التنس حسنًا، ما تريد فعله هو رفع المضرب عند الاصطدام مباشرةً حتى تحصل على دوران علوي رائع" },
    { time: 393.0, en: "try and hit one What", ar: "حاول أن تضرب واحدًا ماذا" },
    { time: 403.0, en: "is that what's the noise it it's on me it's just the cell phone I got you Clifton sending you a text so you can practice how to write back", ar: "هو أن هذا هو سبب الضجيج الذي يحدث معي، إنه مجرد الهاتف الخلوي الذي أرسلته لك، كليفتون يرسل لك رسالة نصية حتى تتمكن من التدرب على كيفية الرد" },
    { time: 416.0, en: "It's not doing it.", ar: "انها لا تفعل ذلك." },
    { time: 417.0, en: "I got it Dear drag Now you can text Clifton", ar: "فهمت عزيزي دراج، الآن يمكنك إرسال رسالة نصية إلى كليفتون" },
    { time: 425.0, en: "all right fine How do you do this?", ar: "بخير بخير كيف تفعل هذا؟" },
    { time: 429.0, en: "Maybe it's your fingernails.", ar: "ربما هي أظافرك." },
    { time: 431.0, en: "It's easy.", ar: "إنه سهل." },
    { time: 432.0, en: "Look.", ar: "ينظر." },
    { time: 432.0, en: "I'll text Mavis Psyched for date night.", ar: "سأرسل رسالة نصية إلى Mavis Psyched من أجل موعد ليلي." },
    { time: 436.0, en: "See and now look she texted right back.", ar: "انظر وانظر الآن لقد أرسلت رسالة نصية مباشرة." },
    { time: 439.0, en: "Got a cancel can't leave Dennis okay, are we Allowed to be", ar: "حصلت على إلغاء لا يمكن أن أترك دينيس بخير، هل مسموح لنا أن نكون كذلك" },
    { time: 446.0, en: "alone again.", ar: "وحده مرة أخرى." },
    { time: 447.0, en: "I need to feel loved too and sent Okay,", ar: "أحتاج أن أشعر بالحب أيضًا وأرسله حسنًا،" },
    { time: 455.0, en: "all that taught me is that you're pathetic Yeah, got it.", ar: "كل ما علمني إياه هو أنك مثير للشفقة نعم، فهمت." },
    { time: 458.0, en: "Maybe you should just get Bluetooth.", ar: "ربما يجب عليك فقط الحصول على البلوتوث." },
    { time: 460.0, en: "Okay Bluetooth come over here.", ar: "حسنًا يا بلوتوث، تعال إلى هنا." },
    { time: 465.0, en: "So now what?", ar: "فماذا الآن؟" },
  ],
  },
  {
    id: "ht2-mom-back",
    title: "Maman Returns · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "rNGxMhbbHtM",
    source: 'YouTube',
    note: "رجوع ماما د ووديسة السؤال اللي مفكرهم كله: دينيس وامبا ولا إنسان؟ — النص الأوتوماتيكي للمشهد (140 سطر من الكلام)",

  scenes: [
    { time: 4.0, en: "Rise and shine, my Denisovich.", ar: "انهض وتألق يا دينيسوفيتش." },
    { time: 7.0, en: "Hi, Papa.", ar: "مرحبا بابا." },
    { time: 8.0, en: "Hello, my little devil.", ar: "مرحباً يا شيطاني الصغير." },
    { time: 10.0, en: "Did you have sweet nightmares?", ar: "هل كان لديك كوابيس حلوة؟" },
    { time: 12.0, en: "Uh-huh.", ar: "اه هاه." },
    { time: 13.0, en: "I dreamed I saw a stegosaurus.", ar: "حلمت أنني رأيت ستيجوسورس." },
    { time: 16.0, en: "Oh, and were you drinking his blood?", ar: "أوه، وكنت شرب دمه؟" },
    { time: 19.0, en: "No.", ar: "لا." },
    { time: 20.0, en: "Just throwing it out there.", ar: "مجرد رميها هناك." },
    { time: 21.0, en: "Hey, you want to do something cool?", ar: "مهلا، هل تريد أن تفعل شيئا رائعا؟" },
    { time: 24.0, en: "Yeah.", ar: "نعم." },
    { time: 25.0, en: "I'm going to teach you how to turn into a bat, like me.", ar: "سأعلمك كيف تتحول إلى خفاش، مثلي." },
    { time: 30.0, en: "See?", ar: "يرى؟" },
    { time: 31.0, en: "Cool.", ar: "رائع." },
    { time: 32.0, en: "Yes, cool, like I said.", ar: "نعم رائع كما قلت." },
    { time: 34.0, en: "Now you try.", ar: "الآن تحاول." },
    { time: 36.0, en: "I'm a bat.", ar: "أنا خفاش." },
    { time: 38.0, en: "I'm a bat.", ar: "أنا خفاش." },
    { time: 39.0, en: "I'm a bat.", ar: "أنا خفاش." },
    { time: 39.0, en: "I'm a bat.", ar: "أنا خفاش." },
    { time: 40.0, en: "I'm a bat.", ar: "أنا خفاش." },
    { time: 42.0, en: "I'm a bat.", ar: "أنا خفاش." },
    { time: 43.0, en: "I mean, a real bat.", ar: "أعني، خفاش حقيقي." },
    { time: 44.0, en: "I'm a bat.", ar: "أنا خفاش." },
    { time: 47.0, en: "Denisovich, take a breath.", ar: "دينيسوفيتش، خذ نفسا." },
    { time: 49.0, en: "You can really turn into a bat.", ar: "يمكنك حقا أن تتحول إلى خفاش." },
    { time: 52.0, en: "Try.", ar: "يحاول." },
    { time: 53.0, en: "Feel the bat.", ar: "اشعر بالمضرب." },
    { time: 56.0, en: "Not a chicken.", ar: "ليس دجاجة." },
    { time: 60.0, en: "What's that?", ar: "ما هذا؟" },
    { time: 61.0, en: "The electric boogaloo?", ar: "بوجالو الكهربائية؟" },
    { time: 62.0, en: "If I show you I can bust a move, will you try to fly then?", ar: "إذا أظهرت لك أنني أستطيع أن أفشل حركة، هل ستحاول الطيران بعد ذلك؟" },
    { time: 65.0, en: "Uh-huh.", ar: "اه هاه." },
    { time: 66.0, en: "Dad, why are you guys dancing?", ar: "أبي، لماذا ترقصون يا رفاق؟" },
    { time: 69.0, en: "He was sleep dancing.", ar: "كان يرقص أثناء النوم." },
    { time: 71.0, en: "Come on, sweetie, back to bed.", ar: "هيا يا عزيزتي، عد إلى السرير." },
    { time: 73.0, en: "Back to bed?", ar: "العودة إلى السرير؟" },
    { time: 73.0, en: "It's already after 8 p.m.", ar: "إنها بالفعل بعد الساعة 8 مساءً." },
    { time: 75.0, en: "Don't you remember the new sleep schedule?", ar: "ألا تتذكر جدول النوم الجديد؟" },
    { time: 77.0, en: "He's going to human classes half the day.", ar: "سيذهب إلى دروس البشر نصف اليوم." },
    { time: 80.0, en: "If he could just sleep till 2 a.m.", ar: "إذا كان بإمكانه النوم حتى الساعة الثانية صباحًا." },
    { time: 82.0, en: "tonight, it'd be so great for him.", ar: "الليلة، سيكون الأمر رائعًا جدًا بالنسبة له." },
    { time: 83.0, en: "But honey, Dad, six of Wayne's wolf pups are having a birthday party tonight.", ar: "لكن عزيزي يا أبي، ستة من صغار ذئاب واين سيقيمون حفلة عيد ميلاد الليلة." },
    { time: 87.0, en: "You wouldn't want him to miss that.", ar: "أنت لا تريده أن يفوتك ذلك." },
    { time: 89.0, en: "Dad, I love the wolf pups, but they're a little too rough for Denis.", ar: "أبي، أنا أحب صغار الذئاب، لكنها قاسية بعض الشيء بالنسبة لدينيس." },
    { time: 94.0, en: "Too rough?", ar: "خشنة جدًا؟" },
    { time: 94.0, en: "Haven't you noticed?", ar: "ألم تلاحظ؟" },
    { time: 96.0, en: "Denis is different.", ar: "دينيس مختلف." },
    { time: 97.0, en: "What are you saying?", ar: "ماذا تقول؟" },
    { time: 98.0, en: "Denisovich shouldn't be around monsters?", ar: "لا ينبغي أن يكون دينيسوفيتش حول الوحوش؟" },
    { time: 101.0, en: "I love monsters!", ar: "أنا أحب الوحوش!" },
    { time: 102.0, en: "Video!", ar: "فيديو!" },
    { time: 103.0, en: "Ha!", ar: "ها!" },
    { time: 104.0, en: "Oh, you want to show Papa Jack your monster video?", ar: "أوه، هل تريد أن تظهر لبابا جاك مقطع الفيديو الوحشي الخاص بك؟" },
    { time: 110.0, en: "the coolest monster?", ar: "أروع وحش؟" },
    { time: 115.0, en: "Cakey one, happy monster.", ar: "كيكي واحد، وحش سعيد." },
    { time: 117.0, en: "Cakey love cake.", ar: "كعكة الحب كيكي." },
    { time: 119.0, en: "Yummy!", ar: "لذيذ!" },
    { time: 120.0, en: "Tommy good, a Tommy yay.", ar: "تومي جيد، تومي نعم." },
    { time: 122.0, en: "Whoa, whoa, whoa, whoa.", ar: "قف، قف، قف، قف." },
    { time: 123.0, en: "How is that a monster?", ar: "كيف يكون ذلك وحشا؟" },
    { time: 125.0, en: "Have some cake was a lump-a-bum.", ar: "تناول بعض الكعك كان بمثابة مقطوعة." },
    { time: 128.0, en: "Remember kids, a real monster always shares.", ar: "تذكروا أيها الأطفال، الوحش الحقيقي يشارككم دائمًا." },
    { time: 132.0, en: "Shares, yes.", ar: "الأسهم، نعم." },
    { time: 133.0, en: "When I think monsters, I think shares.", ar: "عندما أفكر في الوحوش، أفكر في الأسهم." },
    { time: 136.0, en: "Now let me tell you what a real monster is, Denisovich.", ar: "الآن دعني أخبرك ما هو الوحش الحقيقي يا دينيسوفيتش." },
    { time: 140.0, en: "Dad, please, he's practically five already.", ar: "أبي، من فضلك، هو في الخامسة من عمره تقريبًا." },
    { time: 143.0, en: "Don't force it.", ar: "لا تجبرها." },
    { time: 148.0, en: "Slow down was a lump-a-bum, the scariest monster of all is diabetes.", ar: "كان التباطؤ بمثابة كتلة من بوم، والوحش الأكثر رعبا على الإطلاق هو مرض السكري." },
    { time: 155.0, en: "Twinkle, twinkle little star, Mommy, I'm too old for lullabies.", ar: "توينكل، توينكل أيها النجم الصغير، أمي، أنا كبير في السن على التهويدات." },
    { time: 161.0, en: "What?", ar: "ماذا؟" },
    { time: 162.0, en: "That's not how that one goes.", ar: "هذه ليست الطريقة التي تسير بها الأمور." },
    { time: 163.0, en: "This is the way most people sing it.", ar: "هذه هي الطريقة التي يغنيها معظم الناس." },
    { time: 165.0, en: "Most people?", ar: "معظم الناس؟" },
    { time: 166.0, en: "What's wrong with...", ar: "ما هو الخطأ في ..." },
    { time: 168.0, en: "Suffer, suffer, scream in pain, blood is spilling from your brain.", ar: "تعاني، تعاني، تصرخ من الألم، الدم يسيل من دماغك." },
    { time: 174.0, en: "Daddy.", ar: "بابي." },
    { time: 175.0, en: "Come on, you know how I sang it to you.", ar: "هيا، أنت تعرف كيف غنيتها لك." },
    { time: 177.0, en: "Zombies know you like a plum, piercing cries and you succumb.", ar: "يعرف الزومبي أنك تحب البرقوق، وتصرخ ثاقبة وتستسلم." },
    { time: 185.0, en: "Suffer, suffer, scream in pain, you will never breathe again.", ar: "عاني، عاني، اصرخ من الألم، ولن تتنفس مرة أخرى." },
    { time: 196.0, en: "Still works.", ar: "لا يزال يعمل." },
    { time: 224.0, en: "We'd be in one.", ar: "سنكون في واحدة." },
    { time: 227.0, en: "Mr.", ar: "السيد." },
    { time: 227.0, en: "Ditch, my big boy, you made it.", ar: "ديتش، يا ولدي الكبير، لقد نجحت." },
    { time: 230.0, en: "I thought about what you said, Dad.", ar: "فكرت فيما قلته يا أبي." },
    { time: 233.0, en: "Maybe I was being a little overprotective.", ar: "ربما كنت مفرطًا في الحماية قليلاً." },
    { time: 235.0, en: "Thank you, Cop and Kick.", ar: "شكرا لك أيها الشرطي وركلة." },
    { time: 237.0, en: "Dennis, I'd love to use", ar: "دينيس، وأنا أحب أن استخدامها" },
    { time: 247.0, en: "that.", ar: "الذي - التي." },
    { time: 247.0, en: "Winnie, give him his space, hon.", ar: "ويني، أعطيه مساحة له، عزيزتي." },
    { time: 250.0, en: "I'm sorry, Mavis.", ar: "أنا آسف، ميفيس." },
    { time: 251.0, en: "It's okay, Atwanda.", ar: "لا بأس يا أتواندا." },
    { time: 252.0, en: "They're just playing.", ar: "إنهم يلعبون فقط." },
    { time: 254.0, en: "Holy rabies, Limbo.", ar: "داء الكلب المقدس، ليمبو." },
    { time: 256.0, en: "I used to love that game.", ar: "كنت أحب تلك اللعبة." },
    { time: 257.0, en: "Get the nitter-baby.", ar: "احصل على الطفل القذر." },
    { time: 259.0, en: "Really?", ar: "حقًا؟" },
    { time: 260.0, en: "But I'm a parent now.", ar: "لكني والد الآن." },
    { time: 261.0, en: "Show them how it's done.", ar: "أظهر لهم كيف يتم ذلك." },
    { time: 263.0, en: "Okay, okay.", ar: "حسنا، حسنا." },
    { time: 274.0, en: "a piñata?", ar: "البنياتا؟" },
    { time: 278.0, en: "Mavis, honey, that's for later.", ar: "(مافيس)، عزيزتي، هذا لوقت لاحق." },
    { time: 281.0, en: "We don't want the pups to have too much.", ar: "لا نريد أن يكون لدى الجراء الكثير." },
    { time: 283.0, en: "Whoo-hoo!", ar: "ووو هوو!" },
    { time: 289.0, en: "Sugar.", ar: "سكر." },
    { time: 298.0, en: "I'm sorry.", ar: "أنا آسف." },
    { time: 299.0, en: "Did I start all that?", ar: "هل بدأتم بكل ذلك؟" },
    { time: 300.0, en: "Don't worry.", ar: "لا تقلق." },
    { time: 300.0, en: "There's a reason they call it a litter.", ar: "هناك سبب يسمونه القمامة." },
    { time: 318.0, en: "Look!", ar: "ينظر!" },
    { time: 319.0, en: "Your tooth came out!", ar: "أسنانك خرجت!" },
    { time: 320.0, en: "Are you kidding me?", ar: "هل تمزح معي؟" },
    { time: 321.0, en: "He got his tooth knocked out?", ar: "لقد تحطمت أسنانه؟" },
    { time: 322.0, en: "Oh, yes, indeed.", ar: "أوه، نعم، في الواقع." },
    { time: 324.0, en: "Here comes the fang.", ar: "هنا يأتي الناب." },
    { time: 325.0, en: "Dad, his baby tooth wasn't a fang.", ar: "أبي، أسنانه اللبنية لم تكن ناباً" },
    { time: 327.0, en: "Why would this one be?", ar: "لماذا يكون هذا واحد؟" },
    { time: 329.0, en: "He's not a monster.", ar: "انه ليس وحشا." },
    { time: 331.0, en: "Mm-hmm.", ar: "مم-هممم." },
    { time: 335.0, en: "The sun's gonna come out soon, and we gotta get to his classes.", ar: "سوف تشرق الشمس قريبًا، وعلينا أن نصل إلى فصوله." },
    { time: 338.0, en: "What's wrong with the classes we have here, like the kid's yoga?", ar: "ما العيب في الفصول التي لدينا هنا، مثل اليوغا للأطفال؟" },
    { time: 346.0, en: "This is Denisovich's home.", ar: "هذا هو منزل دينيسوفيتش." },
    { time: 349.0, en: "I don't know, Dad.", ar: "لا أعرف يا أبي." },
    { time: 350.0, en: "What don't you know?", ar: "ماذا لا تعرف؟" },
    { time: 352.0, en: "Well, we've been talking about moving.", ar: "حسنا، لقد كنا نتحدث عن التحرك." },
    { time: 355.0, en: "Somewhere safer for Denis.", ar: "في مكان أكثر أمانًا لدينيس." },
    { time: 357.0, en: "Maybe where Johnny grew up in California.", ar: "ربما حيث نشأ جوني في كاليفورنيا." },
    { time: 360.0, en: "I'm sorry, but you can't just make somebody something they're not.", ar: "أنا آسف، لكن لا يمكنك أن تجعل شخصًا ما ليس كذلك." },
    { time: 367.0, en: "Come on, honey.", ar: "هيا يا عزيزي." },
    { time: 367.0, en: "We have to go.", ar: "علينا أن نذهب." },
    { time: 368.0, en: "Ting, ting.", ar: "تينغ، تينغ." },
    { time: 370.0, en: "Maybe.", ar: "ربما." },
    { time: 371.0, en: "Wait.", ar: "انتظر." },
    { time: 372.0, en: "You can't mean that.", ar: "لا يمكنك أن تعني ذلك." },
    { time: 377.0, en: "You're in on this, the leaving?", ar: "أنت في هذا، والمغادرة؟" },
    { time: 379.0, en: "Uh, it's not definite at all.", ar: "اه، انها ليست محددة على الإطلاق." },
    { time: 381.0, en: "It's just something she's definitely talking about.", ar: "إنه مجرد شيء تتحدث عنه بالتأكيد." },
    { time: 383.0, en: "But until we do it, it's not definite-tized.", ar: "ولكن حتى نفعل ذلك، فإنه ليس محددا." },
    { time: 388.0, en: "Did he just cover me with birdseed?", ar: "هل غطاني ببذور الطيور فحسب؟" },
    { time: 391.0, en: "Yeah, he covered me.", ar: "نعم، لقد قام بتغطيتي." },
  ],
  },
  {
    id: "ht2-mummy",
    title: "Mummy Mistake · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "7y9stFHCvEY",
    source: 'YouTube',
    note: "غلطة الموميا — دراكولا بيحاول يعلّم دينيس يعمل \"أجزاء\" لكن النتيجة عالمية — النص الأوتوماتيكي للمشهد (33 سطر من الكلام)",

  scenes: [
    { time: 0.0, en: "OK, Murray, your turn.", ar: "حسنًا، موراي، دورك." },
    { time: 3.0, en: "Uh, excuse us?", ar: "اه، عذرا لنا؟" },
    { time: 5.0, en: "Do you know where someone can get a bite around here?", ar: "هل تعرف أين يمكن لأي شخص أن يحصل على قضمة هنا؟" },
    { time: 7.0, en: "Did you seriously just ask a vampire where to get a bite?", ar: "هل جدياً سألت مصاص دماء أين يمكنك أن تأكل؟" },
    { time: 10.0, en: "Oh, gosh, I mean, we're not from around here.", ar: "يا إلهي، أعني أننا لسنا من هنا." },
    { time: 13.0, en: "This is so embarrassing.", ar: "هذا محرج للغاية." },
    { time: 14.0, en: "Just keep going.", ar: "فقط استمر." },
    { time: 15.0, en: "Sorry to bother you.", ar: "آسف لإزعاجك." },
    { time: 16.0, en: "Love your chocolate cereal.", ar: "أحب حبوب الشوكولاتة الخاصة بك." },
    { time: 21.0, en: "So what do you want me to do now?", ar: "إذن ماذا تريد مني أن أفعل الآن؟" },
    { time: 23.0, en: "Denisovits, you won't believe it.", ar: "دينيسوفيتس، لن تصدق ذلك." },
    { time: 25.0, en: "The mummy can crash through walls and turn into a swarm of beetles and put the curse on anyone.", ar: "يمكن للمومياء أن تصطدم بالجدران وتتحول إلى سرب من الخنافس وتلحق اللعنة على أي شخص." },
    { time: 31.0, en: "That sounds mean.", ar: "هذا يبدو يعني." },
    { time: 33.0, en: "It's fun mean.", ar: "إنها متعة يعني." },
    { time: 34.0, en: "OK, so check it out.", ar: "حسنًا، تحقق من ذلك." },
    { time: 36.0, en: "Murray's going to conjure up the biggest sandstorm you've ever seen.", ar: "سوف يستحضر موراي أكبر عاصفة رملية رأيتها على الإطلاق." },
    { time: 41.0, en: "Hidden sandstone?", ar: "الحجر الرملي المخفي؟" },
    { time: 43.0, en: "It's been a while.", ar: "لقد مضى وقت طويل." },
    { time: 44.0, en: "Not my problem.", ar: "ليست مشكلتي." },
    { time: 45.0, en: "Do it.", ar: "افعلها." },
    { time: 45.0, en: "Say your little spell.", ar: "قل تعويذتك الصغيرة." },
    { time: 47.0, en: "OK.", ar: "نعم." },
    { time: 49.0, en: "I got this, Frank.", ar: "حصلت على هذا، فرانك." },
    { time: 51.0, en: "Wayne.", ar: "واين." },
    { time: 52.0, en: "Just try not to faint.", ar: "فقط حاول ألا تغمى عليك." },
    { time: 61.0, en: "Two hot pots, battery.", ar: "وعاءين ساخنين، بطارية." },
    { time: 63.0, en: "Ho, ho, soft alarm, terror of my sight.", ar: "هو، هو، إنذار ناعم، رعب بصري." },
    { time: 65.0, en: "All men have craze on full moon-hood routine fact.", ar: "جميع الرجال مهووسون بالحقيقة الروتينية الخاصة بغطاء القمر." },
    { time: 70.0, en: "Ho, ho, sharp alarm.", ar: "هو، هو، إنذار حاد." },
    { time: 73.0, en: "We come of you.", ar: "نأتي منك." },
    { time: 86.0, en: "Oh, wait.", ar: "أوه، انتظر." },
    { time: 94.0, en: "Ooh.", ar: "أوه." },
    { time: 95.0, en: "Ha, ha, ow, ow, ow.", ar: "ها، ها، أوه، أوه، أوه." },
  ],
  },
  {
    id: "ht2-camp",
    title: "Camp Vamp · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "RkINjKcnVuY",
    source: 'YouTube',
    note: "يوم التخييم (Camp Winnepaku) — قواعد المخيم العجيب بتاعة الذلول — النص الأوتوماتيكي للمشهد (27 سطر من الكلام)",

  scenes: [
    { time: 0.0, en: "Wait and see fellas, this kid will be guzzling goat blood in no time Here", ar: "انتظروا وانظروا يا رفاق، هذا الطفل سوف يستهلك دم الماعز في أي وقت من الأوقات هنا" },
    { time: 9.0, en: "we are it's the vampire summer camp I went to as a kid What's it camp them?", ar: "نحن، إنه المخيم الصيفي لمصاصي الدماء الذي ذهبت إليه عندما كنت طفلاً، ما هو معسكرهم؟" },
    { time: 15.0, en: "No, who names their camp camp man?", ar: "لا، من يسمي رجل معسكرهم؟" },
    { time: 18.0, en: "It's camp Winnie pakaka You", ar: "إنه معسكر ويني باكاكا أنت" },
    { time: 41.0, en: "see the needs of it.", ar: "رؤية احتياجات ذلك." },
    { time: 42.0, en: "This is where I learned to catch mice and shape-shift And use my incredible powers and strength is", ar: "هذا هو المكان الذي تعلمت فيه الإمساك بالفئران وتغيير شكلها واستخدام قواي وقوتي المذهلة" },
    { time: 49.0, en: "pretty cool.", ar: "رائع جدًا." },
    { time: 51.0, en: "Ah Yes,", ar: "اه نعم،" },
    { time: 55.0, en: "I don't remember this bad Well, well, is this a night how you doing folks?", ar: "لا أتذكر هذا الأمر السيئ حسنًا، حسنًا، هل هذه ليلة كيف حالكم يا رفاق؟" },
    { time: 62.0, en: "I'm Dana the director We're sure excited to have you legends visiting us.", ar: "أنا دانا المخرجة، نحن بالتأكيد متحمسون لزيارتكم أيها الأساطير." },
    { time: 66.0, en: "What can I do you for?", ar: "ماذا يمكنني أن أفعل لك؟" },
    { time: 68.0, en: "Well, I'm very interested in sending my grand boy Denis if it's you oh This little red-headed", ar: "حسنًا، أنا مهتم جدًا بإرسال ابني الكبير دينيس إذا كان أنت يا هذا الصغير ذو الرأس الأحمر" },
    { time: 75.0, en: "non-fangy little guy.", ar: "الرجل الصغير غير ناب." },
    { time: 78.0, en: "Oh, they're in there.", ar: "أوه، إنهم هناك." },
    { time: 79.0, en: "He's a late fanger That's why we came here Can you show us some of the drills like where they catch the mice can", ar: "إنه مهووس متأخر ولهذا السبب جئنا إلى هنا. هل يمكنك أن ترينا بعض التدريبات مثل المكان الذي يصطادون فيه الفئران؟" },
    { time: 86.0, en: "do of course now?", ar: "تفعل بالطبع الآن؟" },
    { time: 87.0, en: "We call it tea mousy so", ar: "نحن نسميها فأر الشاي هكذا" },
    { time: 100.0, en: "they don't have to catch the mice.", ar: "ليس عليهم الإمساك بالفئران." },
    { time: 102.0, en: "No, we find This is a good way to build their confidence It's", ar: "لا، نجد أن هذه طريقة جيدة لبناء ثقتهم" },
    { time: 110.0, en: "right there.", ar: "هناك." },
    { time: 110.0, en: "What's the matter with you?", ar: "ما خطبك؟" },
    { time: 114.0, en: "Hokey-pokey.", ar: "هوكي بوكي." },
    { time: 118.0, en: "Here.", ar: "هنا." },
    { time: 119.0, en: "It is Denis image where Papa learned to fly Yeah,", ar: "إنها صورة دينيس حيث تعلم بابا الطيران نعم،" },
    { time: 130.0, en: "we're over here now Had to scale it down insurance.", ar: "نحن هنا الآن وكان علينا تقليص التأمين." },
    { time: 141.0, en: "Oh, you pokey.", ar: "أوه، أنت بوكي." },
    { time: 143.0, en: "See you at the campfire", ar: "نراكم في نار المخيم" },
  ],
  },
  {
    id: "ht2-change",
    title: "You Can't Change Him · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "oOp7Q_xw94I",
    source: 'YouTube',
    note: "الجد فلاد بيلاقي دينيس إنسان — والمشكلة اللي بتزيد من الطرفين — النص الأوتوماتيكي للمشهد (46 سطر من الكلام)",

  scenes: [
    { time: 0.0, en: "What did you just do?", ar: "ماذا فعلت للتو؟" },
    { time: 1.0, en: "A few more seconds and the kid's fans would have popped right out!", ar: "بضع ثوانٍ أخرى وستخرج جماهير الطفل على الفور!" },
    { time: 4.0, en: "I don't care, it's not worth it!", ar: "لا أهتم، الأمر لا يستحق ذلك!" },
    { time: 6.0, en: "What's not worth it?", ar: "ما الذي لا يستحق كل هذا العناء؟" },
    { time: 8.0, en: "It was my last attempt to make the boy a vampire so you'd stay.", ar: "لقد كانت محاولتي الأخيرة لجعل الصبي مصاص دماء حتى تبقى أنت." },
    { time: 11.0, en: "By ruining his favorite thing?", ar: "عن طريق تدمير الشيء المفضل لديه؟" },
    { time: 13.0, en: "How could you do that?", ar: "كيف يمكنك أن تفعل ذلك؟" },
    { time: 14.0, en: "We were desperate!", ar: "كنا يائسين!" },
    { time: 16.0, en: "You were in on this?", ar: "كنت في هذا؟" },
    { time: 17.0, en: "Dennis won't be happy in my town.", ar: "دينيس لن يكون سعيدا في مدينتي." },
    { time: 19.0, en: "Dennis hasn't been there!", ar: "دينيس لم يكن هناك!" },
    { time: 20.0, en: "Now has been done twice!", ar: "لقد تم الآن مرتين!" },
    { time: 23.0, en: "Feel the strain and the strife!", ar: "تشعر بالتوتر والصراع!" },
    { time: 25.0, en: "Shut up!", ar: "اسكت!" },
    { time: 27.0, en: "Johnny, Dennis is not a monster!", ar: "جوني، دينيس ليس وحشا!" },
    { time: 31.0, en: "He likes avocado!", ar: "يحب الأفوكادو!" },
    { time: 32.0, en: "Because you don't let him eat anything fun!", ar: "لأنك لا تسمح له بتناول أي شيء ممتع!" },
    { time: 34.0, en: "I think Dennis just wants to be normal.", ar: "أعتقد أن دينيس يريد فقط أن يكون طبيعيًا." },
    { time: 37.0, en: "Can we stop using the word normal?", ar: "هل يمكننا التوقف عن استخدام كلمة عادي؟" },
    { time: 39.0, en: "Where we live now, he's normal.", ar: "حيث نعيش الآن، فهو طبيعي." },
    { time: 41.0, en: "He is who he is!", ar: "هو من هو!" },
    { time: 43.0, en: "And you can't change him, Dad!", ar: "ولا يمكنك تغييره يا أبي!" },
    { time: 55.0, en: "At a place where we can hide!", ar: "في مكان يمكننا أن نختبئ فيه!" },
    { time: 57.0, en: "Follow me!", ar: "اتبعني!" },
    { time: 65.0, en: "If you didn't stop me, my great-grandson wouldn't have to be a wimp his whole life.", ar: "إذا لم توقفني، فلن يكون حفيدتي ضعيفًا طوال حياته." },
    { time: 69.0, en: "Like Shlumpy over here.", ar: "مثل شلمبي هنا." },
    { time: 71.0, en: "A wimp?", ar: "واهن؟" },
    { time: 72.0, en: "Johnny, be cool.", ar: "جوني، كن هادئا." },
    { time: 73.0, en: "You wanna throw it out, old man?", ar: "هل تريد التخلص منها أيها الرجل العجوز؟" },
    { time: 75.0, en: "Certified yellow belt since 1997.", ar: "الحزام الأصفر المعتمد منذ عام 1997." },
    { time: 78.0, en: "No!", ar: "لا!" },
    { time: 79.0, en: "What's this now?", ar: "ما هذا الآن؟" },
    { time: 80.0, en: "You're not a vampire?", ar: "أنت لست مصاص دماء؟" },
    { time: 82.0, en: "Uh, Blair?", ar: "اه بلير؟" },
    { time: 84.0, en: "Of course he's human.", ar: "بالطبع هو إنسان." },
    { time: 85.0, en: "He's our son.", ar: "إنه ابننا." },
    { time: 86.0, en: "You think we're monsters?", ar: "هل تعتقد أننا وحوش؟" },
    { time: 91.0, en: "You!", ar: "أنت!" },
    { time: 92.0, en: "You let your daughter marry a human!", ar: "سمحت لابنتك أن تتزوج إنساناً!" },
    { time: 95.0, en: "And have a human kid!", ar: "ويكون لديك طفل الإنسان!" },
    { time: 96.0, en: "Why don't you just put a stake through my heart?", ar: "لماذا لا تضع وتدا في قلبي؟" },
    { time: 99.0, en: "We don't hate humans anymore, and they don't hate us!", ar: "لم نعد نكره البشر، وهم لا يكرهوننا!" },
    { time: 110.0, en: "You're a fool!", ar: "أنت أحمق!" },
    { time: 111.0, en: "Your great-grandson is the sweetest, kindest, most special boy I've ever met.", ar: "حفيدك هو ألطف وألطف وأكثر فتى مميزًا قابلته على الإطلاق." },
    { time: 117.0, en: "And if you can't give him the love he deserves because he's half human, then you're the fool!", ar: "وإذا كنت لا تستطيع أن تمنحه الحب الذي يستحقه لأنه نصف إنسان، فأنت الأحمق!" },
    { time: 123.0, en: "Oh, Daddy!", ar: "يا أبي!" },
  ],
  },
  {
    id: "ht2-batfight",
    title: "Family Bat Fight · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "n1lQR-GjWYw",
    source: 'YouTube',
    note: "المعركة الجوية الأخيرة — الخفاشات المتحايلة والدفاع عن القلعة — النص الأوتوماتيكي للمشهد (5 سطر من الكلام)",

  scenes: [
    { time: 5.0, en: "this'll be fun.", ar: "هذا سوف يكون ممتعا." },
    { time: 68.0, en: "that?", ar: "الذي - التي؟" },
    { time: 103.0, en: "That practice will pay off!", ar: "هذه الممارسة سوف تؤتي ثمارها!" },
    { time: 128.0, en: "That's right!", ar: "هذا صحيح!" },
    { time: 129.0, en: "You better fly away!", ar: "من الأفضل أن تطير بعيدًا!" },
  ],
  },
  {
    id: "ht2-monster",
    title: "I'm in Love With a Monster (Ending) · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "D4_CGzg3fmQ",
    source: 'YouTube',
    note: "نهاية الفيلم — دراكولا بيتقبّل دينيس مثل ما هو وسعيد بحياتهم الجديدة — النص الأوتوماتيكي للمشهد (25 سطر من الكلام)",

  scenes: [
    { time: 1.0, en: "Papa Jock, I'm a vampire and a superhero.", ar: "بابا جوك، أنا مصاص دماء وبطل خارق." },
    { time: 4.0, en: "Am I cool now?", ar: "هل أنا بارد الآن؟" },
    { time: 6.0, en: "Now?", ar: "الآن؟" },
    { time: 7.0, en: "Dennis, you were always cool.", ar: "دينيس، لقد كنت دائمًا رائعًا." },
    { time: 10.0, en: "Human, vampire, unicorn, you're perfect no matter what.", ar: "إنسان، مصاص دماء، وحيد القرن، أنت مثالي مهما حدث." },
    { time: 14.0, en: "But since I'm a vampire, can we stay here?", ar: "لكن بما أنني مصاص دماء، هل يمكننا البقاء هنا؟" },
    { time: 19.0, en: "Yes.", ar: "نعم." },
    { time: 20.0, en: "All right!", ar: "حسنًا!" },
    { time: 22.0, en: "All right!", ar: "حسنًا!" },
    { time: 23.0, en: "All right!", ar: "حسنًا!" },
    { time: 24.0, en: "But you have to know we're going to visit you here every holiday.", ar: "لكن عليك أن تعلم أننا سنقوم بزيارتك هنا في كل عطلة." },
    { time: 29.0, en: "That's fine.", ar: "هذا جيّد." },
    { time: 46.0, en: "Don't ever come near me or my family again.", ar: "لا تقترب مني أو من عائلتي مرة أخرى." },
    { time: 65.0, en: "Daddy, you just saved a human.", ar: "أبي، لقد أنقذت للتو إنسانًا." },
    { time: 69.0, en: "All this pressure about when the boys' fangs were coming out.", ar: "كل هذا الضغط بخصوص موعد خروج أنياب الأولاد." },
    { time: 73.0, en: "Who cares?", ar: "من يهتم؟" },
    { time: 74.0, en: "Mine came out years ago.", ar: "خرج خاصتي منذ سنوات." },
    { time: 76.0, en: "Look!", ar: "ينظر!" },
    { time: 79.0, en: "Okay, Dad, put them back in before we all barf.", ar: "حسنًا يا أبي، أعدهم إلى مكانهم قبل أن نتوقف جميعًا." },
    { time: 82.0, en: "Hey, isn't it still somebody's birthday?", ar: "مهلا، أليس لا يزال عيد ميلاد شخص ما؟" },
    { time: 91.0, en: "buy me a storm before you buy me a rose.", ar: "اشتري لي عاصفة قبل أن تشتري لي وردة." },
    { time: 94.0, en: "We covered in dirt before we covered in gold.", ar: "غطينا بالتراب قبل أن غطينا بالذهب." },
    { time: 98.0, en: "He's trying it off, yeah, he's taking me", ar: "إنه يحاول ذلك، نعم، إنه يأخذني" },
    { time: 103.0, en: "over, be told.", ar: "انتهى، يقال." },
    { time: 104.0, en: "Cause I'm in love.", ar: "لأنني في حالة حب." },
  ],
  },
  {
    id: "ht2-credits",
    title: "I'm in Love With a Monster (End Credits) · Hotel Transylvania 2",
    kind: 'movie',
    youtube: "1zkI6mn7Mio",
    source: 'YouTube',
    note: "أغنية النهاية من الفيلم — حط السماعات وردد الكلمات ورا الأغنية كتير — النص الأوتوماتيكي للمشهد (1 سطر من الكلام)",

  scenes: [
    { time: 27.0, en: "Be taking me out Say what you want, but I won't", ar: "أخرجني، قل ما تريد، لكنني لن أفعل" },
  ],
  },
]

SHADOWING_CLIPS.push(...HOTEL2_CLIPS)
