import type { ReviewVocabGroup } from "./types"

export const VOCAB_5_8: ReviewVocabGroup[] = [
  {
    unit: "الوحدة 5: news",
    tables: [
      {
        title: "الأخبار ووسائل التواصل الاجتماعي – news and social media (5A)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["publish", "ينشر", ""],
          ["journalist", "صحفي", ""],
          ["find out", "يكتشف / يعرف (معلومة)", ""],
          ["post", "ينشر / يرفع قصة على الإنترنت", ""],
          ["headline", "عنوان الخبر (بالخط الكبير)", ""],
          ["fake news", "أخبار مزيفة / كدابة", ""],
          ["the facts", "الحقائق", ""],
          ["blog post", "منشور / تدوينة على مدونة", ""],
          ["go viral", "ينتشر بسرعة على الإنترنت (فيروسي)", ""],
          ["spot", "يشوف / يلاحظ", "I think it’s pretty easy to spot this kind of story."],
        ],
      },
      {
        title: "قضايا اجتماعية؛ البيئة – social issues; the environment (5B)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["pollution", "تلوث", ""],
          ["level", "المستوى / الكمية", "Levels of pollution means the amount of dirt or unwanted objects in the environment."],
          ["recycle", "يعيد تدوير", ""],
          ["waste", "نفايات / زبالة", ""],
          ["campaign", "حملة (توعية / إعلانية)", ""],
          ["activists", "نشطاء", ""],
          ["collect", "يجمع", ""],
          ["charity", "جمعية خيرية", ""],
          ["donate", "يتبرع", ""],
          ["environment", "البيئة / الطبيعة حوالينا", ""],
        ],
      },
      {
        title: "الأحداث والمناسبات – events and occasions (5C)",
        headers: ["العبارة", "المعنى", "مثال"],
        rows: [
          ["pass your exams/driving test", "تنجح في الامتحانات / اختبار القيادة", "I passed my driving test."],
          ["fail your exams/driving test", "تسقط (تفشل) في الامتحانات / اختبار القيادة", "I failed my accountancy exams for the third time."],
          ["have a baby", "تخلف / عندك بيبي", "Lolita was born on Saturday."],
          ["lose your job", "تخسر شغلك / تشتغيلك", "I’m now worried I might lose my job."],
          ["get promoted / a new job", "تترقى / تاخد شغل جديد", "I got promoted, so I’m now earning more money."],
          ["have an argument", "تخانق / عندك خلاف", "I had an argument with a friend."],
          ["win a competition/match", "تكسب مسابقة / ماتش", "I won a competition and got a prize."],
          ["get engaged/married", "تُخطب / تتجوز", "We’re getting married in the summer."],
          ["break your phone/laptop", "تكسر موبايلك / لابتوبك", "I broke my phone."],
          ["get 2,000 likes", "تاخد 2000 لايك", "My video got over 2,000 likes!"],
          ["graduate from university", "تتخرج من الجامعة", "I graduated from university last year."],
          ["move house", "تنقل بيت جديد", "I’ve just moved into a really nice house."],
          ["have your birthday", "تعيد ميلادك", "How did you have your last birthday?"],
          ["quit your job", "تسيب شغلك", "I’m thinking about quitting my job."],
          ["celebrate", "تحتفل", "We’re having a party for my 40th."],
        ],
      },
    ],
  },
  {
    unit: "الوحدة 6: creators",
    tables: [
      {
        title: "الفنون – the arts (6A)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["musician", "عازف / موسيقي", ""],
          ["the arts", "الفنون (موسيقى، كتابة، رسم، أدب، سينما)", ""],
          ["performer", "مؤدي / فنان بيعزف أو بيمثل قدام الناس", ""],
          ["recording", "تسجيل", ""],
          ["painter", "رسام", ""],
          ["style", "أسلوب / ستايل", ""],
          ["subjects", "المواضيع", ""],
          ["composer", "ملحن / مؤلف موسيقى", ""],
          ["works", "الأعمال الفنية", ""],
          ["image", "صورة", ""],
        ],
      },
      {
        title: "تكوين الكلمات (الإبداع) – creativity: word building (6B)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["imagine / imagination / imaginative", "فعل / اسم / صفة", ""],
          ["create / creativity / creative", "فعل / اسم / صفة", ""],
          ["art / art / artistic", "اسم / اسم / صفة", ""],
          ["photograph / photography / photographic", "فعل / اسم / صفة", ""],
          ["skill / skill / skilful", "فعل / اسم / صفة", ""],
          ["talent / talent / talented", "فعل / اسم / صفة", ""],
        ],
      },
      {
        title: "صفات متطرفة – extreme adjectives (6C)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["good", "صفة عادية", "We can say 'very good'. We can't say 'very fantastic'."],
          ["fantastic", "صفة متطرفة (قوية)", "We can say 'absolutely fantastic'. We can't say 'absolutely good'."],
          ["bad / terrible", "عادية / متطرفة", ""],
          ["interesting / fascinating", "عادية / متطرفة", ""],
          ["big / huge", "عادية / متطرفة", ""],
          ["small / tiny", "عادية / متطرفة", ""],
          ["important / essential", "عادية / متطرفة", ""],
          ["difficult / impossible", "عادية / متطرفة", ""],
        ],
      },
      {
        title: "اطلب وادّي رأي وأسباب – Ask for and give opinions and reasons (6C)",
        headers: ["الموقف / العبارة", "الرد"],
        rows: [
          ["طلب رأي – Asking for an opinion (How about you? / What makes you say that? / What do/did you think of…?)", "فاكر إيه فيها؟ (What do you think about it?)"],
          ["إبداء رأي – Giving an opinion (Forme,… / In my view,… / I think… / I would say…)", "في رأيي، التصميم جديد ومثير فعلًا. (In my view, it’s a really new and exciting design.)"],
          ["طلب سبب – Asking for a reason (Why do you think that?)", "ليه فاكر كده؟ (Why do you think that?)"],
          ["إعطاء سبب – Giving a reason (The reason is… / It’s because…)", "عشانه مجاني. (It’s because it’s free.)"],
          ["الاتفاق على الاختلاف – Agreeing to disagree (I suppose we’re all different. / I guess it’s good we’re not all the same.)", "أعتقد إن كلنا بندوق حاجات مختلفة. (I guess we all like different things.)"],
        ],
      },
    ],
  },
  {
    unit: "الوحدة 7: travel",
    tables: [
      {
        title: "السفر والسياحة – travel and tourism (7A)",
        headers: ["العبارة", "المعنى", "مثال"],
        rows: [
          ["tradition / traditional", "تقليد / تقليدي", "It’s a local tradition in Poland for people to throw water at each other on ‘wet Monday’."],
          ["custom", "عُرف / عادة", "Family life is very important in Italian customs."],
          ["out of season", "خارج الموسم (سياح أقل)", "You can usually find much better prices if you travel out of season."],
          ["festival", "مهرجان / عيد", "Chinese New Year is one of China’s most important festivals."],
          ["tourist destination", "وجهة سياحية", "The USA, Spain and Japan are three of the most popular tourist destinations."],
          ["weekend trip / break", "رحلة / أجازة نهاية الأسبوع", "We're going for a short break to the Lake District this weekend."],
          ["go sightseeing", "تتفرج على المعالم السياحية", "We saw all the main sights yesterday."],
          ["queue", "طابور / دور", "I hate standing in queues with all those people."],
          ["traffic jams", "زحمة سير", "There are often traffic jams on the way to the beach."],
          ["attractions", "أماكن جذب سياحي", "Which attractions do you visit?"],
          ["trip", "رحلة", "We’re going on a trip to the Lake District."],
        ],
      },
      {
        title: "الطبيعة – the natural world (7B)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["coast", "ساحل", "I walked along the coast every morning."],
          ["beach", "شاطئ", "Those dogs on the beach were my friends."],
          ["landscape", "منظر طبيعي", "The landscape was never boring."],
          ["field", "حقل", "We walked through green fields."],
          ["valley", "وادي", "We went over hills, through valleys."],
          ["stream / river", "جدول / نهر", "We walked next to streams and rivers."],
          ["forest", "غابة", "The path led through a forest."],
        ],
      },
      {
        title: "وصف الأماكن – describing places (7C)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["vibrant", "نابض بالحياة / مليء بالطاقة", "It's worth a visit to experience this vibrant, exciting and modern city."],
          ["modern", "حديث / عصري", "The buildings are modern."],
          ["ancient", "قديم / أثري", "This ancient bridge is over 800 years old."],
          ["narrow / wide", "ضيق / واسع", "The streets are so narrow you can't drive down them."],
          ["peaceful", "هادئ / مريح", "I love sitting in the park - it’s so peaceful."],
          ["wooden", "خشبي", "There are some old wooden benches."],
          ["colourful", "ملوّن / بألوان زاهية", "The buildings are colourful."],
          ["historical", "تاريخي", "There are many historical buildings in Rome."],
          ["traditional", "تقليدي", "We saw traditional houses in the old town."],
          ["famous for", "مشهور بـ", "The city is famous for its beautiful views."],
        ],
      },
      {
        title: "اعمل وردّ على توصيات – make and respond to recommendations (7C)",
        headers: ["الموقف / العبارة", "الرد"],
        rows: [
          ["There are a few things you absolutely have to see/do… (توصية قوية)", "طريقة قوية للتوصية (a strong way to recommend)"],
          ["You must visit/try/see… (توصية قوية)", "استخدم must + فعل (use must + verb)"],
          ["You should definitely visit… (توصية قوية)", "استخدم should + definitely (use should + definitely)"],
          ["Make sure you… (تخليه ماينساش)", "يتبعه مضارع بسيط (make sure + present simple)"],
          ["… is one of the best things to do… (توصية بأفضل ما في المكان)", "حاجة من أحسن الحاجات (it's one of the best)"],
          ["It’s a lovely/great place to… (توصية بمكان لنشاط)", "مكان جميل ينفع + فعل (it's a lovely place to + verb)"],
          ["Don’t leave without visiting/seeing… (لا يفوتك)", "متفوتش من غير + ing (don't + without + -ing)"],
          ["Oh wow! How exciting! (الرد بحماس)", "الرد: فكرة عظيمة / فكرة كويسة / ده يبان مثير (responding: That's a great idea. / OK, that's a good idea. / That sounds interesting.)"],
        ],
      },
    ],
  },
  {
    unit: "الوحدة 8: know-how",
    tables: [
      {
        title: "قدرات عملية؛ أفعال مركبة للقدرات – practical abilities; abilities: phrasal verbs (8A)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["repair", "يصلح", "He sometimes has to repair things that go wrong."],
          ["replace", "يستبدل", "He replaced the old parts of his van."],
          ["upload", "يرفع حاجة على الإنترنت", "He uploads the videos to YouTube."],
          ["put up", "يثبّت / يعلّق على الحائط", "They put up shelves."],
          ["calculate", "يحسب", "He calculated what size it should be."],
          ["design", "يصمم / يرسم ويخطط", "He designed the tiny house."],
          ["install", "يركّب (تقنية)", "He installed electricity."],
          ["turn (something) into (something else)", "يحوّل (حاجة) إلى (حاجة تانية)", "He turned his van into a mobile studio."],
          ["solve a problem", "يحل مشكلة", "They had to solve a few problems."],
          ["arrange", "يرتب / ينسق", "They arranged access to running water."],
        ],
      },
      {
        title: "مصاحبات الفيديو – video collocations (8B)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["clip", "مقطع قصير من فيديو أطول", "A video clip is a short piece from a longer video."],
          ["share", "يشارك (فيديو) على السوشيال ميديا", "If you share a video, other people can watch it too."],
          ["edit", "يعدّل الفيديو / يقصه", "When you edit a video, you make it shorter."],
          ["like", "يعمل لايك / يبيّن إنه عاجبه", "You might like the video."],
          ["comment", "يكتب تعليق على فيديو", "You might comment on it."],
          ["make", "يعمل / بيصوّر فيديو", "A lot of people make videos to use for marketing."],
          ["vlog", "مدونة فيديو (فلوغ)", "A video podcast is often called a vlog."],
          ["upload", "يرفع الفيديو على الإنترنت", "Hundreds of hours of video are uploaded to YouTube every minute."],
        ],
      },
      {
        title: "مشاكل تقنية – technical problems (8C)",
        headers: ["العبارة", "المعنى", "مثال"],
        rows: [
          ["crash", "يعلّق / يقف فجأة (للجهاز)", "My computer keeps crashing in the middle of a meeting."],
          ["out of order", "معطل / مش شغال (للماكينة)", "The photocopier is out of order."],
          ["broken", "مكسور / معطل", "The printer is broken."],
          ["run out of charge", "البطارية تخلص (مفيش طاقة)", "My phone runs out of charge too quickly."],
          ["lose the wifi signal", "يفقد إشارة الواي فاي", "I lost the wifi signal."],
          ["open / download / attach a file", "يفتح / يحمّل / يرفق ملف", "I can’t open a file or attachment on my laptop."],
          ["create / change / forget a password", "يعمل / يغيّر / ينسى باسورد", "You can’t use your account until you log in and create a new password."],
          ["slow internet connection", "إنترنت بطيء", "You have a slow internet connection."],
          ["get cut off", "ينقطع عنك الكلام في المكالمة", "I get cut off after waiting for twenty minutes."],
        ],
      },
    ],
  },
]