import type { ReviewVocabGroup } from './types'

export const VOCAB_1_4: ReviewVocabGroup[] = [
  {
    unit: "الوحدة 1: People",
    tables: [
      {
        title: "الناس والعلاقات – People and relationships (1A)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["teammate", "زميل في نفس الفريق", "I get on well with my teammates on the football team."],
          ["colleague", "زميل في الشغل", "I'm friendly with most of my colleagues."],
          ["manager", "المدير", "I have a really good manager. I look up to her."],
          ["close friend", "صديق مقرّب", "I also have a group of close friends and we sometimes play music together."],
          ["partner", "شريك الحياة", "My partner is my best friend."],
          ["grandparent", "جد / جدة", "My grandparents were very important to me."],
          ["daughter", "بنت", "My daughter takes after my mother."],
          ["children", "أولاد", "I want my children to have a good relationship with my parents."],
        ],
      },
      {
        title: "صفات الشخصية – Personality adjectives (1A)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["funny", "مضحك", "They're so funny, and great to be with."],
          ["kind", "طيب", "She's such a kind and generous person."],
          ["generous", "كريم", "My grandfather is very generous with his time."],
          ["hard-working", "مجتهد / شغال بجد", "They are hard-working and very reliable."],
          ["reliable", "يمكن الاعتماد عليه", "She is a very reliable colleague."],
          ["cheerful", "مرح / دمه خفيف", "She's always cheerful."],
          ["calm", "هادي", "It’s amazing that he was so calm."],
        ],
      },
      {
        title: "الوظائف – Jobs (1B)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["chef", "شيف / طباخ", "A chef is responsible for planning the menu and creating new dishes."],
          ["musician", "موسيقي", "My brother is a musician."],
          ["mechanic", "ميكانيكي", "The mechanic fixed our car very quickly."],
          ["financial consultant", "مستشار مالي", "I'd like to be a financial consultant because they earn a good salary."],
          ["shop assistant", "بائع في محل", "The shop assistant recommended the blue jacket."],
          ["plumber", "سباك", "We called a plumber to fix the kitchen tap."],
          ["gardener", "بوستاني / عامل جنينة", "Our gardener looks after the plants once a week."],
          ["journalist", "صحفي", "My sister is a journalist."],
        ],
      },
      {
        title: "مواضيع المحادثة – Conversation topics (1C)",
        headers: ["العبارة", "المعنى", "مثال"],
        rows: [
          ["clothes and fashion", "الموضة والملابس", "That's a nice jacket. Where did you get it?"],
          ["food and eating out", "الأكل والخروج للأكل", "Have you tried these pastries? They look delicious."],
          ["hobbies and free-time activities", "الهوايات وأنشطة وقت الفراغ", "What kinds of things do you paint?"],
          ["holiday experiences", "تجارب الإجازات", "We've just got back from Corfu. It was wonderful."],
          ["politics", "السياسة", "So, who do you think will win the election?"],
          ["sport or music events", "ماتشات أو أحداث موسيقية", "It's the Big Music Live this weekend. Are you going?"],
          ["the news", "الأخبار", "Did you hear about the fire in town? It’s terrible."],
          ["the weather", "الطقس", "Lovely day, isn't it?"],
          ["work or studies", "الشغل والمذاكرة", "I hear you have a job in finance. Do you enjoy it?"],
        ],
      },
    ],
  },
  {
    unit: "الوحدة 2: Tale tellers",
    tables: [
      {
        title: "صفات المشاعر – Adjectives for feelings; -ed/-ing adjectives (2A)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["bored", "زهقان / حاسس بالملل", "We were bored, so we went into the garage."],
          ["exciting", "مثير", "We were really excited when we found all dad’s paints."],
          ["frightened", "خايف", "My sister and I were frightened."],
          ["embarrassed", "محرج", "I think he found it a bit embarrassing."],
          ["annoyed", "مضايق / زعلان", "Dad is going to be really annoyed!"],
          ["surprised", "متفاجئ", "I'm surprised you chose blue."],
          ["disappointed", "خايب أمل", "He was probably disappointed with us."],
          ["amazed", "مذهول / منبهر", "It's amazing that he was so calm."],
        ],
      },
      {
        title: "كلمات القصة – Story words (2B)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["hero", "بطل القصة", "The hero of the film saves the town."],
          ["characters", "شخصيات القصة", "The characters in this book are very realistic."],
          ["plot", "الحبكة / مجريات الأحداث", "I think having an exciting plot is important."],
          ["ending", "النهاية", "I like a happy ending, too."],
          ["storyteller", "الراوي", "The storyteller at the festival was amazing."],
          ["performances", "العروض / الأداء", "I love the actors' performances."],
          ["fairytales", "حكايات خرافية", "My grandmother told me fairytales."],
          ["TV shows", "برامج التليفزيون", "It's the same with TV shows and films."],
        ],
      },
      {
        title: "التوافقات مع get و make – Collocations with get and make (2C)",
        headers: ["العبارة", "المعنى", "مثال"],
        rows: [
          ["get off", "ينزل من مواصلة", "I got off at the wrong bus stop!"],
          ["get lost", "يضيع / يضل الطريق", "Sorry I’m late – I got lost!"],
          ["get held up", "يتأخر", "I got held up at work."],
          ["get the wrong day/time/date/address", "يفهم اليوم/الوقت/التاريخ/العنوان غلط", "I got the wrong day!"],
          ["make a mistake", "يعمل غلطة", "I made a mistake with the address."],
          ["make a call", "يعمل مكالمة / يتصل", "I had to make an urgent call."],
          ["make a plan", "يرتب خطة", "My partner made other plans and I didn’t know until it was too late."],
          ["make a mess", "يعمل فوضى", "My little sister made a mess and I had to clean it up."],
        ],
      },
    ],
  },
  {
    unit: "الوحدة 3: Questions",
    tables: [
      {
        title: "المعرفة: أفعال وأسماء – Knowledge: verbs and nouns (3A)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["note down", "يدوّن / يكتب عشان يفتكر", "I note down new information, and I use my notes to revise for exams."],
          ["revise", "يراجع (لفحص)", "I use my notes to revise for exams."],
          ["memory", "الذاكرة", "I read all the time and I have a good memory."],
          ["a mind", "العقل", "I think my mind works that way."],
          ["general knowledge", "ثقافة عامة", "My general knowledge is fine, although I don’t know much about sport!"],
          ["solve (a problem)", "يحل مشكلة", "I love to do quizzes and solve problems."],
          ["guess", "يخمّن", "If I don’t know the answer, I just guess!"],
          ["score", "النقاط / الدرجة", "Even if I get a good score, I forget everything immediately afterwards!"],
          ["data", "بيانات ومعلومات", "At work, I need to understand data and I’m quite good with numbers."],
          ["an option", "خيار", "I try to choose the best option."],
        ],
      },
      {
        title: "القرارات – Decisions (3B)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["communicate", "يتواصل / يتبادل المعلومات", "Good teams communicate well."],
        ],
      },
      {
        title: "المرافق – Facilities (3C)",
        headers: ["الكلمة", "المعنى", "مثال"],
        rows: [
          ["facilities", "المرافق والخدمات", "The university offers all the facilities you need."],
          ["campus", "الحرم الجامعي", "If you are studying at the University of Malta, the campus also has a sports centre."],
          ["library", "المكتبة", "There is a main library which has a huge selection of books."],
          ["sports centre", "مركز رياضي", "The campus has a sports centre with football pitches and a swimming pool."],
          ["gym", "صالة جيم / رياضة", "Can I use the gym? I’d like to know when the gym opens in the morning."],
          ["halls of residence", "سكن الجامعة", "You can stay in university halls of residence or with home-stay families."],
          ["study areas", "أماكن المذاكرة", "There are outside study areas where students can study together."],
          ["language schools", "معاهد اللغات", "You can register for a course at one of the many language schools on the island."],
          ["employment office", "مكتب التوظيف", "Jobs in finance or tourism are easy to find in Malta."],
          ["theatres", "المسارح", "The sports centre is in the town square, opposite the theatre."],
        ],
      },
    ],
  },
  {
    unit: "الوحدة 4: winners",
    tables: [
      {
        title: "النجاح – Success (4A)",
        headers: ["العبارة", "المعنى", "مثال"],
        rows: [
          ["talented", "موهوب", "She's a really talented dancer - she's so good!"],
          ["strict (with yourself)", "صارم مع نفسك", "He needs to be strict about when he starts work."],
          ["do well", "ينجح / يظبط", "She is doing well at school and getting good grades."],
          ["bad loser", "بزعل جدًا لما يخسر", "He hates it when his team doesn't win. He's a bad loser."],
          ["working hard", "شغال بجد / مجتهد", "She's working hard, so I'm sure she'll be successful."],
          ["competitive", "بيحب المنافسة", "The brothers are very competitive. They always want to win."],
          ["carry on", "يكمل / يستمر", "Carry on playing and do not stop until you win."],
          ["give up", "يستسلم / يبطل", "She is thinking about giving up her job."],
          ["failure", "فشل", "Do not be afraid of failure."],
          ["succeed", "ينجح / يحقق هدفه", "Only a few people achieve their dreams."],
        ],
      },
      {
        title: "توافقات التكنولوجيا وبناء الكلمات – Technology collocations; word building: suffixes (4B)",
        headers: ["العبارة", "المعنى", "مثال"],
        rows: [
          ["create a webpage", "ينشئ صفحة ويب", "Tim Berners-Lee showed how to create webpages."],
          ["send / receive a text", "يبعت / يستلم رسالة نصية", "Didn’t you receive all my texts?"],
          ["download an app", "ينزّل تطبيق", "You just use your email address and add a password."],
          ["launch a website", "يطلق موقع ويب", "When we launched a website last year, we didn’t expect so many people to visit it so quickly!"],
          ["post a photo", "ينشر صورة", "Do you post photos on social media?"],
          ["share a video or photo", "يتشارك فيديو أو صورة", "I shared a video with my friends on Instagram."],
          ["comment on a webpage", "يعلّق على صفحة ويب", "Please leave a comment on their website."],
          ["go viral", "ينتشر بسرعة (viral)", "It didn’t exactly go viral, but it did launch a website that has been incredibly popular."],
        ],
      },
      {
        title: "الرياضات والألعاب – Sports and games (4C)",
        headers: ["العبارة", "المعنى", "مثال"],
        rows: [
          ["take part in", "يشارك في", "Do you take part in any sports?"],
          ["support a team", "يشجع فريق", "I support Manchester United."],
          ["a fan of a team/player", "مشجع لفريق / لاعب", "Are you a fan of any teams or players?"],
          ["a champion", "بطل (الفائز)", "We're the champions!"],
          ["score points / goals", "يسجل نقاط / أهداف", "Do you know how you score points?"],
          ["board game", "لعبة لوحية", "Do you have any board games at home?"],
          ["e-sports", "رياضات إلكترونية", "He takes part in e-sports competitions."],
        ],
      },
      {
        title: "عبارات مفيدة: رحلة لا تُنسى – Key phrases: a memorable journey (4D)",
        headers: ["القاعدة", "مثال"],
        rows: [
          ["للتحدث عن أروع رحلة في حياتي", "The most memorable journey I've ever been on was…"],
          ["للتعبير عن أول مرة", "It was my first time…"],
          ["لوصف أنها كانت من أروع التجارب", "It was one of the most amazing…"],
          ["لبيان سبب عدم نسيانها", "It was memorable because…"],
          ["لذكر مدة الرحلة", "The journey took… days."],
          ["لوصف أكثر الأماكن إثارة للاهتمام", "… is definitely the most interesting place I've been to."],
        ],
      },
    ],
  },
]